In [1]:
!python --version

Python 3.11.14

## GDC

https://docs.gdc.cancer.gov/API/Users_Guide/Downloading_Files/

sample  
 ├── primary_site       (organ)  
 ├── disease_type       (broad class)  
 ├── subtype_global     (cross-cancer)  
 ├── subtype_tissue     (within-cancer)  
 └── histology          (biological family)

### TCGA / GDC Portal

https://portal.gdc.cancer.gov/

In [2]:
import os, sys
import pandas as pd

from pathlib import Path

ROOT = Path().resolve().parent.parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv
SRC added: /home/flavio/uv/src

### Defaults

In [3]:
ROOT = Path().resolve().parent
root_data = os.path.join(ROOT, "data/tcga")

gdc = GDC(root_data=root_data)

os.listdir(root_data)

['cases_for_PS_TCGA-LUAD.tsv',
 'subtype_for_PS_TCGA-ACC.tsv',
 'subtype_for_PS_TCGA-HNSC.tsv',
 'subtype_for_PS_TCGA-KIRP.tsv',
 'subtype_for_PS_TCGA-OV.tsv',
 'stage_for_PS_TCGA-UCEC_Subtype_basaloid squamous cell carcinoma.tsv',
 'subtype_for_PS_TCGA-UCS.tsv',
 'subtype_for_PS_TCGA-PAAD.tsv',
 'stage_for_PS_TCGA-UCEC_Subtype_papillary serous cystadenocarcinoma.tsv',
 'cases_for_PS_TCGA-BRCA.tsv',
 'subtype_for_PS_TCGA-LIHC.tsv',
 'subtype_for_PS_TCGA-STAD.tsv',
 'subtype_for_PS_TCGA-KIRC.tsv',
 'subtype_for_PS_TCGA-PRAD.tsv',
 'subtype_for_PS_TCGA-BLCA.tsv',
 'subtype_for_PS_TCGA-THYM.tsv',
 'subtype_for_PS_TCGA-COAD.tsv',
 'subtype_for_PS_TCGA-GBM.tsv',
 'subtype_for_PS_TCGA-PCPG.tsv',
 'programs.txt',
 'subtype_for_PS_TCGA-SKCM.tsv',
 'subtype_for_PS_TCGA-KICH.tsv',
 'subtype_for_PS_TCGA-CESC.tsv',
 'primary_site_program_TCGA.tsv',
 'subtype_for_PS_TCGA-TGCT.tsv',
 'subtype_for_PS_TCGA-THCA.tsv',
 'subtype_for_PS_TCGA-UVM.tsv',
 'subtype_for_PS_TCGA-LAML.tsv',
 'subtype_for_PS_TCGA-DLBC.tsv',
 'subtype_for_PS_TCGA-READ.tsv',
 'subtype_for_PS_TCGA-LUSC.tsv',
 'subtype_for_PS_TCGA-CHOL.tsv',
 'subtype_for_PS_TCGA-UCEC.tsv',
 'subtype_for_PS_TCGA-LGG.tsv',
 'cases_for_PS_TCGA-ACC.tsv',
 'subtype_for_PS_TCGA-SARC.tsv',
 'subtype_for_PS_TCGA-LUAD.tsv',
 'subtype_for_PS_TCGA-ESCA.tsv',
 'subtype_for_PS_TCGA-BRCA.tsv',
 'subtype_for_PS_TCGA-MESO.tsv']

### Get GDC programs - get_gdc_progams()

> end_point: url_gdc_project = "https://api.gdc.cancer.gov/projects"  
> "facets": "program.name"  

### Get valid primary sites - get_primary_sites()

> end_point: url_gdc_project = "https://api.gdc.cancer.gov/projects"  
> "fields": "project_id,name,primary_site,disease_type"  

### Get valid subtypes - get_subtypes()

> end_point: url_gdc_cases = "https://api.gdc.cancer.gov/cases"  
> facets = "diagnoses.primary_diagnosis"  

### For each subtype → get stages  - get_stages()

> end_point: url_gdc_cases = "https://api.gdc.cancer.gov/cases"  
> "field": "diagnoses.ajcc_pathologic_stage" - AJCC diagnoses   

### For each (subtype, stage) → get_samples()

> end_point: url_gdc_cases = "https://api.gdc.cancer.gov/cases"  
> given pid, subtype, stage  
> from cases   
> "samples.sample_id", "samples.submitter_id", "samples.sample_type"  

### get RNA-seq files - get_expression_files_given_samples()

> given: "field": "cases.case_id", "value": case_ids  
> end_point: url_gdc_files = "https://api.gdc.cancer.gov/files"

### All programs

In [4]:
force=False
verbose=True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

File read at '/home/flavio/uv/perturb_agent/data/tcga/programs.txt'

In [5]:
np.array(prog_list)

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a programa

In [6]:
gdc.url_gdc_project

'https://api.gdc.cancer.gov/projects'

In [7]:
force=False
verbose=True

program = 'TCGA'

dfc = gdc.get_primary_sites(program=program, force=force, verbose=verbose)

print(len(dfc))
dfc.head(12)

Table opened ((33, 5)) at '/home/flavio/uv/perturb_agent/data/tcga/primary_site_program_TCGA.tsv'
33

,pid,primary_site,project_id,disease_type,name
0,TCGA-ACC,Adrenal gland,TCGA-ACC,Adenomas and Adenocarcinomas,Adrenocortical Carcinoma
1,TCGA-PCPG,"Adrenal gland, Retroperitoneum and peritoneum,...",TCGA-PCPG,Paragangliomas and Glomus Tumors,Pheochromocytoma and Paraganglioma
2,TCGA-BLCA,Bladder,TCGA-BLCA,"Epithelial Neoplasms, NOS, Squamous Cell Neopl...",Bladder Urothelial Carcinoma
3,TCGA-LGG,Brain,TCGA-LGG,Gliomas,Brain Lower Grade Glioma
4,TCGA-GBM,Brain,TCGA-GBM,"Not Reported, Gliomas",Glioblastoma Multiforme
5,TCGA-BRCA,Breast,TCGA-BRCA,"Adnexal and Skin Appendage Neoplasms, Adenomas...",Breast Invasive Carcinoma
6,TCGA-LUAD,Bronchus and lung,TCGA-LUAD,"Ductal and Lobular Neoplasms, Cystic, Mucinous...",Lung Adenocarcinoma
7,TCGA-LUSC,Bronchus and lung,TCGA-LUSC,"Squamous Cell Neoplasms, Adenomas and Adenocar...",Lung Squamous Cell Carcinoma
8,TCGA-MESO,"Bronchus and lung, Heart, mediastinum, and pleura",TCGA-MESO,Mesothelial Neoplasms,Mesothelioma
9,TCGA-CESC,"Cervix uteri, Ovary",TCGA-CESC,"Squamous Cell Neoplasms, Cystic, Mucinous and ...",Cervical Squamous Cell Carcinoma and Endocervi...
10,TCGA-COAD,"Colon, Rectosigmoid junction",TCGA-COAD,"Cystic, Mucinous and Serous Neoplasms, Complex...",Colon Adenocarcinoma
11,TCGA-READ,"Colon, Rectosigmoid junction, Rectum, Connecti...",TCGA-READ,"Cystic, Mucinous and Serous Neoplasms, Adenoma...",Rectum Adenocarcinoma

In [8]:
dfc.tail(3)

,pid,primary_site,project_id,disease_type,name
30,TCGA-THCA,Thyroid gland,TCGA-THCA,"Squamous Cell Neoplasms, Epithelial Neoplasms,...",Thyroid Carcinoma
31,TCGA-UCS,"Uterus, NOS, Corpus uteri",TCGA-UCS,"Basal Cell Neoplasms, Complex Mixed and Stroma...",Uterine Carcinosarcoma
32,TCGA-UCEC,"Uterus, NOS, Corpus uteri",TCGA-UCEC,"Not Reported, Cystic, Mucinous and Serous Neop...",Uterine Corpus Endometrial Carcinoma

### Subtypes

👉 GDC does NOT give you clean biological subtypes
👉 You must derive them yourself

This is actually a feature, not a bug — because:

> you control granularity  
> you can harmonize across cancers  
> you avoid noisy labels  


💡 If you want to level this up

I can help you build:

🔬 A cross-TCGA subtype harmonizer
maps all projects → unified subtype ontology
handles synonyms (adenocarcinoma, NOS, etc.)
outputs clean ML-ready labels

👉 That would massively improve your perturbation analysis.

- Brain tumors do NOT use AJCC staging (3 - TCGA-LGG Brain)

In [16]:
force=True
verbose=True

i = 5
pid = dfc.iloc[i].pid
primary_site = dfc.iloc[i].primary_site

print(i, pid, primary_site)

df_cases, df_subt, df_prof = gdc.get_cases_and_subtypes(pid=pid, batch_size=200, do_filter=False, force=force, verbose=verbose)

print("df_cases", len(df_cases), "df_subt", len(df_subt))
df_subt

5 TCGA-BRCA Breast
.......

👉 Returned 1098 / Total paginated 1098
Table saved ((1098, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-BRCA.tsv'
Table saved ((12, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-BRCA.tsv'
df_cases 1098 df_subt 12

,pid,subtype_global,tumor_class,subtype_tissue,sstage,n
0,TCGA-BRCA,other,other,other,II,447
1,TCGA-BRCA,lobular,other,breast_lobular,missing,223
2,TCGA-BRCA,other,other,other,III,154
3,TCGA-BRCA,other,other,other,I,141
4,TCGA-BRCA,other,other,other,missing,85
5,TCGA-BRCA,adenocarcinoma_generic,adenocarcinoma,adenocarcinoma_generic,missing,19
6,TCGA-BRCA,other,other,other,IV,16
7,TCGA-BRCA,ductal,adenocarcinoma,breast_ductal,missing,6
8,TCGA-BRCA,ductal,other,breast_ductal,II,2
9,TCGA-BRCA,clear_cell,other,clear_cell,II,2
10,TCGA-BRCA,ductal,other,breast_ductal,missing,2
11,TCGA-BRCA,neuroendocrine,neuroendocrine_tumor,neuroendocrine,missing,1

In [17]:
cols = ["pid", "subtype_global", "tumor_class", "subtype_tissue", "stage"]

df_cases[cols].head(12)

          pid subtype_global tumor_class  subtype_tissue       stage
0   TCGA-BRCA          other       other           other     unknown
1   TCGA-BRCA          other       other           other  Stage IIIA
2   TCGA-BRCA          other       other           other    Stage IA
3   TCGA-BRCA          other       other           other   Stage IIB
4   TCGA-BRCA          other       other           other    Stage IA
5   TCGA-BRCA          other       other           other   Stage IIA
6   TCGA-BRCA          other       other           other    Stage IA
7   TCGA-BRCA          other       other           other  Stage IIIA
8   TCGA-BRCA          other       other           other   Stage IIA
9   TCGA-BRCA        lobular       other  breast_lobular     unknown
10  TCGA-BRCA          other       other           other  Stage IIIA
11  TCGA-BRCA          other       other           other   Stage IIB

In [ ]:
cols = ["case_id", "subtype_global", "tumor_class", "subtype_tissue", "stage"]
df_cases[cols]

In [18]:
df_prof

,primary_diagnosis,stage,tumor_grade,diagnosis_conflict,n_diagnoses
0,"Metaplastic carcinoma, NOS",Stage IIB,None,False,1
1,"Infiltrating duct carcinoma, NOS",Stage IIIA,None,True,2
2,"Infiltrating duct carcinoma, NOS",Stage IA,None,False,1
3,"Infiltrating duct carcinoma, NOS",Stage IIB,None,False,1
4,"Infiltrating duct carcinoma, NOS",Stage IA,None,False,1
...,...,...,...,...,...
1093,"Infiltrating duct carcinoma, NOS",Stage IIA,None,True,2
1094,"Infiltrating duct carcinoma, NOS",Stage IIA,None,False,1
1095,"Infiltrating duct carcinoma, NOS",Stage IIB,None,False,1
1096,"Lobular carcinoma, NOS",Stage IIB,None,False,1
1097,Invasive micropapillary carcinoma,Stage IIB,None,False,1

In [20]:
dfc.tail(3)

,pid,primary_site,project_id,disease_type,name
30,TCGA-THCA,Thyroid gland,TCGA-THCA,"Squamous Cell Neoplasms, Epithelial Neoplasms,...",Thyroid Carcinoma
31,TCGA-UCS,"Uterus, NOS, Corpus uteri",TCGA-UCS,"Basal Cell Neoplasms, Complex Mixed and Stroma...",Uterine Carcinosarcoma
32,TCGA-UCEC,"Uterus, NOS, Corpus uteri",TCGA-UCEC,"Not Reported, Cystic, Mucinous and Serous Neop...",Uterine Corpus Endometrial Carcinoma

In [21]:
force=False
verbose=True

for i in range(len(dfc)):
    print(i, end=' ')
    pid = dfc.iloc[i].pid
    primary_site = dfc.iloc[i].primary_site

    print(pid, primary_site)

    df_cases, df_subt, df_prof = gdc.get_cases_and_subtypes(pid=pid, batch_size=200, do_filter=False, force=force, verbose=verbose)

0 TCGA-ACC Adrenal gland
Table opened ((92, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-ACC.tsv'
1 TCGA-PCPG Adrenal gland, Retroperitoneum and peritoneum, Other endocrine glands and related structures, Other and ill-defined sites, Connective, subcutaneous and other soft tissues, Spinal cord, cranial nerves, and other parts of central nervous system, Heart, mediastinum, and pleura
Table opened ((179, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-PCPG.tsv'
2 TCGA-BLCA Bladder
Table opened ((412, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-BLCA.tsv'
3 TCGA-LGG Brain
Table opened ((516, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-LGG.tsv'
4 TCGA-GBM Brain
Table opened ((617, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-GBM.tsv'
5 TCGA-BRCA Breast
Table opened ((1098, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-BRCA.tsv'
6 TCGA-LUAD Bronchus and lung
Table opened ((585, 23)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-LUAD.tsv'
7 TCGA-LUSC Bronchus and lung
....

👉 Returned 504 / Total paginated 504
Table saved ((504, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-LUSC.tsv'
Table saved ((15, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-LUSC.tsv'
8 TCGA-MESO Bronchus and lung, Heart, mediastinum, and pleura
..

👉 Returned 87 / Total paginated 87
Table saved ((87, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-MESO.tsv'
Table saved ((7, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-MESO.tsv'
9 TCGA-CESC Cervix uteri, Ovary
...

👉 Returned 307 / Total paginated 307
Table saved ((307, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-CESC.tsv'
Table saved ((5, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-CESC.tsv'
10 TCGA-COAD Colon, Rectosigmoid junction
....

👉 Returned 461 / Total paginated 461
Table saved ((461, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-COAD.tsv'
Table saved ((18, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-COAD.tsv'
11 TCGA-READ Colon, Rectosigmoid junction, Rectum, Connective, subcutaneous and other soft tissues, Unknown
..

👉 Returned 172 / Total paginated 172
Table saved ((172, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-READ.tsv'
Table saved ((11, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-READ.tsv'
12 TCGA-DLBC Colon, Retroperitoneum and peritoneum, Heart, mediastinum, and pleura, Breast, Bones, joints and articular cartilage of other and unspecified sites, Lymph nodes, Small intestine, Stomach, Testis, Brain, Connective, subcutaneous and other soft tissues, Thyroid gland, Hematopoietic and reticuloendothelial systems, Other and unspecified major salivary glands
..

👉 Returned 58 / Total paginated 58
Table saved ((58, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-DLBC.tsv'
Table saved ((2, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-DLBC.tsv'
13 TCGA-SKCM Colon, Spinal cord, cranial nerves, and other parts of central nervous system, Vulva, Skin, Vagina, Bones, joints and articular cartilage of other and unspecified sites, Small intestine, Connective, subcutaneous and other soft tissues, Nasal cavity and middle ear, Anus and anal canal, Liver and intrahepatic bile ducts, Bronchus and lung, Other and ill-defined sites, Adrenal gland, Corpus uteri, Parotid gland, Retroperitoneum and peritoneum, Breast, Lymph nodes, Brain
....

👉 Returned 470 / Total paginated 470
Table saved ((470, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-SKCM.tsv'
Table saved ((14, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-SKCM.tsv'
14 TCGA-ESCA Esophagus, Stomach
..

👉 Returned 185 / Total paginated 185
Table saved ((185, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-ESCA.tsv'
Table saved ((11, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-ESCA.tsv'
15 TCGA-UVM Eye and adnexa
..

👉 Returned 80 / Total paginated 80
Table saved ((80, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-UVM.tsv'
Table saved ((6, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-UVM.tsv'
16 TCGA-LAML Hematopoietic and reticuloendothelial systems
..

👉 Returned 200 / Total paginated 200
Table saved ((200, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-LAML.tsv'
Table saved ((2, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-LAML.tsv'
17 TCGA-KICH Kidney
..

👉 Returned 113 / Total paginated 113
Table saved ((113, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-KICH.tsv'
Table saved ((12, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-KICH.tsv'
18 TCGA-KIRP Kidney
...

👉 Returned 291 / Total paginated 291
Table saved ((291, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-KIRP.tsv'
Table saved ((15, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-KIRP.tsv'
19 TCGA-KIRC Kidney
....

👉 Returned 537 / Total paginated 537
Table saved ((537, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-KIRC.tsv'
Table saved ((20, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-KIRC.tsv'
20 TCGA-HNSC Lip, Tonsil, Gum, Bones, joints and articular cartilage of other and unspecified sites, Palate, Other and unspecified parts of tongue, Floor of mouth, Other and ill-defined sites in lip, oral cavity and pharynx, Larynx, Base of tongue, Other and unspecified parts of mouth, Oropharynx, Hypopharynx
....

👉 Returned 528 / Total paginated 528
Table saved ((528, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-HNSC.tsv'
Table saved ((14, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-HNSC.tsv'
21 TCGA-LIHC Liver and intrahepatic bile ducts
...

👉 Returned 377 / Total paginated 377
Table saved ((377, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-LIHC.tsv'
Table saved ((19, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-LIHC.tsv'
22 TCGA-CHOL Liver and intrahepatic bile ducts, Other and unspecified parts of biliary tract, Pancreas
..

👉 Returned 51 / Total paginated 51
Table saved ((51, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-CHOL.tsv'
Table saved ((7, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-CHOL.tsv'
23 TCGA-PAAD Pancreas
..

👉 Returned 185 / Total paginated 185
Table saved ((185, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-PAAD.tsv'
Table saved ((10, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-PAAD.tsv'
24 TCGA-PRAD Prostate gland
....

👉 Returned 500 / Total paginated 500
Table saved ((500, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-PRAD.tsv'
Table saved ((6, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-PRAD.tsv'
25 TCGA-SARC Retroperitoneum and peritoneum, Colon, Other and unspecified male genital organs, Bones, joints and articular cartilage of limbs, Meninges, Stomach, Other and unspecified parts of tongue, Connective, subcutaneous and other soft tissues, Uterus, NOS, Kidney, Peripheral nerves and autonomic nervous system, Ovary, Corpus uteri
...

👉 Returned 261 / Total paginated 261
Table saved ((261, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-SARC.tsv'
Table saved ((7, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-SARC.tsv'
26 TCGA-OV Retroperitoneum and peritoneum, Ovary
.....

👉 Returned 608 / Total paginated 608
Table saved ((608, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-OV.tsv'
Table saved ((3, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-OV.tsv'
27 TCGA-STAD Stomach
....

👉 Returned 443 / Total paginated 443
Table saved ((443, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-STAD.tsv'
Table saved ((8, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-STAD.tsv'
28 TCGA-TGCT Testis
...

👉 Returned 263 / Total paginated 263
Table saved ((263, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-TGCT.tsv'
Table saved ((6, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-TGCT.tsv'
29 TCGA-THYM Thymus, Other and ill-defined sites, Heart, mediastinum, and pleura
..

👉 Returned 124 / Total paginated 124
Table saved ((124, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-THYM.tsv'
Table saved ((1, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-THYM.tsv'
30 TCGA-THCA Thyroid gland
....

👉 Returned 507 / Total paginated 507
Table saved ((507, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-THCA.tsv'
Table saved ((15, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-THCA.tsv'
31 TCGA-UCS Uterus, NOS, Corpus uteri
..

👉 Returned 57 / Total paginated 57
Table saved ((57, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-UCS.tsv'
Table saved ((4, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-UCS.tsv'
32 TCGA-UCEC Uterus, NOS, Corpus uteri
....

👉 Returned 560 / Total paginated 560
Table saved ((560, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_PS_TCGA-UCEC.tsv'
Table saved ((10, 6)) at '/home/flavio/uv/perturb_agent/data/tcga/subtype_for_PS_TCGA-UCEC.tsv'

### Given a PS, Subtype, and Stage --> return the SAMPLES

In [ ]:
force=False
verbose=True

print(pid, subtype, stage)

df_sample = gdc.get_samples(pid=pid, subtype=subtype, stage=stage, batch_size=200, force=force, verbose=verbose)
print(len(df_sample))
df_sample.head(8)

In [ ]:
force=False
verbose=True

case_ids = list(np.unique(df_sample.case_id))

print(pid, subtype, stage, f"cases {len(case_ids)}")

df_files = gdc.get_expression_files_given_samples(pid=pid, subtype=subtype, stage=stage, 
                                                  case_ids=case_ids, batch_size=20, force=force, verbose=verbose)
print(len(df_files))
df_files.head(6)

In [ ]:
case_ids[:10]