In [1]:
!python --version

Python 3.11.14

In [2]:
import os, sys
import pandas as pd
import requests
import time

from pathlib import Path

ROOT = Path().resolve().parent.parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.calc_degs_lib import CALC_DEGS
from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv
SRC added: /home/flavio/uv/src

### Defaults

In [3]:
ROOT_DATA = '../data'
ROOT_DATA = Path(ROOT_DATA)

gdc = GDC(ROOT_DATA0=ROOT_DATA)

os.listdir(ROOT_DATA)[:10]

['cancer', 'reactome', 'vector_store', 'TCGA', 'GTEx', 'gdc_programs.txt']

In [4]:
os.listdir(gdc.root_data)[:10]

['app_main_local.py',
 'gtex_normal_tissue.ipynb',
 'docker_config.ipynb',
 'tcga_gdc_run_R_expression_dvlp.ipynb']

### Get all programs

In [5]:
force=False
verbose=True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

np.array(prog_list)

File read at '../data/gdc_programs.txt'

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a program

In [6]:
gdc.url_gdc_project

'https://api.self.cancer.gov/projects'

In [7]:
prog_id = 'TCGA'

df_psi = gdc.get_primary_sites(prog_id=prog_id, force=False, verbose=verbose)
print(len(df_psi))

df_psi.head(3)

Table opened ((33, 5)) at '../data/TCGA/primary_site_program_TCGA.tsv'
33

,psi_id,primary_site,project_id,disease_type,name
0,TCGA-ACC,Adrenal gland,TCGA-ACC,Adenomas and Adenocarcinomas,Adrenocortical Carcinoma
1,TCGA-PCPG,"Adrenal gland, Retroperitoneum and peritoneum,...",TCGA-PCPG,Paragangliomas and Glomus Tumors,Pheochromocytoma and Paraganglioma
2,TCGA-BLCA,Bladder,TCGA-BLCA,"Epithelial Neoplasms, NOS, Squamous Cell Neopl...",Bladder Urothelial Carcinoma

### GTEx

In [8]:
ROOT_GTEx = ROOT_DATA / Path('GTEx')

os.listdir(ROOT_GTEx)[:10]

['tcga_primary_site_to_gtex_ids.tsv']

In [9]:
fname_gtex = 'tcga_primary_site_to_gtex_ids.tsv'

dfg = pdreadcsv(fname_gtex, ROOT_GTEx)
print(len(dfg))

dfg.head(6)

33

,tcga_project_id,tcga_primary_site,gtex_dataset_id,preferred_gtex_id,gtex_tissue_site_detail_ids,mapping_confidence,notes,source_gtex_api
0,TCGA-ACC,Adrenal Gland,gtex_v8,Adrenal_Gland,Adrenal_Gland,high,Adrenocortical carcinoma; direct adrenal gland...,https://gtexportal.org/api/v2/redoc
1,TCGA-BLCA,Bladder,gtex_v8,Bladder,Bladder,high,"Direct bladder GTEx tissue, but GTEx bladder s...",https://gtexportal.org/api/v2/redoc
2,TCGA-BRCA,Breast,gtex_v8,Breast_Mammary_Tissue,Breast_Mammary_Tissue,high,Breast carcinoma; GTEx mammary/breast tissue.,https://gtexportal.org/api/v2/redoc
3,TCGA-CESC,Cervix Uteri,gtex_v8,Cervix_Ectocervix,Cervix_Ectocervix|Cervix_Endocervix|Uterus,medium,Cervical cancer may involve ectocervix/endocer...,https://gtexportal.org/api/v2/redoc
4,TCGA-CHOL,Bile Duct,gtex_v8,Liver,Liver,low,No direct bile duct/cholangiocyte GTEx tissue;...,https://gtexportal.org/api/v2/redoc
5,TCGA-COAD,Colon,gtex_v8,Colon_Transverse,Colon_Transverse|Colon_Sigmoid,high,Colon cancer; transverse/sigmoid are both vali...,https://gtexportal.org/api/v2/redoc

In [10]:
psi_id = 'TCGA-BRCA'
psi_id = 'TCGA-LUAD'

dfa = dfg[dfg.tcga_project_id == psi_id]

gtex_id = None

if len(dfa) == 1:
    row = dfa.iloc[0]

    gtex_id = row.preferred_gtex_id
    gtex_tissue_ids = row.gtex_tissue_site_detail_ids
    print(f"Found '{gtex_id}' tissue '{gtex_tissue_ids}'")
elif len(dfa) == 0:
    print("Not found")
else:
    print("Multiple matches found")
    for i, row in dfa.iterrows():
        gtex_id = row.preferred_gtex_id
        gtex_tissue_ids = row.gtex_tissue_site_detail_ids

        print(f"{row.tcga_project_id} -> '{gtex_id}' tissue '{gtex_tissue_ids}'")

Found 'Lung' tissue 'Lung'

### Get df_tumor

In [11]:
psi_id

'TCGA-LUAD'

In [12]:
verbose=False

dic_tumor, dic_normal = gdc.get_file_expression_tumor_and_normal(psi_id=psi_id, force=False, verbose=verbose)
df_tumor, df_normal = gdc.merge_normal_tumor_tables(dic_tumor, dic_normal,  imax_tumor=12, imax_normal=12, verbose=verbose)

len(df_tumor), len(df_normal)

>>> TCGA-LUAD
>>> TCGA-LUAD
0.........10.........20.........30.........40.........50.........60.........70.........80.........90......... -> 100
Dowloading tumor files: 0.........10.........20.........30.........40.........50.........60.........70.........80.........90.........100........ -> 109
>>> Processing normal data: 100
1 2 3 4 5 6 7 8 9 10 11 12 13
>>> Processing tumor data: 11
1 2 3 4 5 6 7 8 9 10 11

(150684, 240796)

In [13]:
df_tumor.head(3)

,gene_id,symbol,gene_type,tumor_1,tumor_2,tumor_3,tumor_4,tumor_5,tumor_6,tumor_7,tumor_8,tumor_9,tumor_10,tumor_11
0,ENSG00000000003,TSPAN6,protein_coding,1604,2392,1373,803,799,5095,2,792,1489,3870,522
1,ENSG00000000005,TNMD,protein_coding,0,0,8,2,1,0,14,0,0,1,0
2,ENSG00000000419,DPM1,protein_coding,459,816,713,799,400,3372,39,1043,345,1380,678

In [41]:
from scipy.stats import f_oneway

def add_entropy(df, read_limit:int=50, min_read:int=200, n_quantiles:int=10):
    # select tumor columns
    cols = [c for c in df.columns if c.startswith("tumor_")]

    def row_entropy(values):
        values = np.asarray(values, dtype=float)

        # remove NaNs
        values = values[np.isfinite(values)]

        if len(values) == 0:
            return np.nan

        # all equal → entropy = 0
        if np.allclose(values, values[0]):
            return 0.0

        # shift to positive (important if negative values exist)
        values = values - values.min()

        # avoid all zeros
        if np.allclose(values.sum(), 0):
            return 0.0

        probs = values / values.sum()

        # avoid log(0)
        probs = probs[probs > 0]

        entropy = -np.sum(probs * np.log2(probs))
        return entropy

    min_cols = int(len(cols) * 0.4)
    good = (df[cols] < read_limit).sum(axis=1) <= min_cols
    df = df[good].copy()

    df["total_sum"] = df[cols].sum(axis=1)

    df = df[df.total_sum > len(cols)*min_read]

    df["entropy"] = df[cols].apply(lambda row: row_entropy(row.values), axis=1)

    df["entropy_q"] = pd.qcut(df["entropy"], q=n_quantiles, labels=False, duplicates="drop" )

    return df


print(len(df_tumor))
df_tumor2 = add_entropy(df_tumor)
print(len(df_tumor2))
df_tumor2.head(3)

150684
15817

,gene_id,symbol,gene_type,tumor_1,tumor_2,tumor_3,tumor_4,tumor_5,tumor_6,tumor_7,tumor_8,tumor_9,tumor_10,tumor_11,entropy,entropy_q,total_sum
0,ENSG00000000003,TSPAN6,protein_coding,1604,2392,1373,803,799,5095,2,792,1489,3870,522,2.954896,5,18741
2,ENSG00000000419,DPM1,protein_coding,459,816,713,799,400,3372,39,1043,345,1380,678,2.911364,4,10044
3,ENSG00000000457,SCYL3,protein_coding,542,432,557,699,264,995,168,352,283,1706,471,2.852843,3,6469

In [46]:
def select_top_entropy(df, q=0.1):

    df = df[df.entropy_q <= q].copy()
    df = df.sort_values('entropy', ascending=True)
    df.reset_index(drop=True, inplace=True)

    return df

tumor_cols = [c for c in df_tumor.columns if c.startswith("tumor_")]

df_tumor3 = select_top_entropy(df_tumor2, q=0.1)
print(len(df_tumor3))
df_tumor3.head(3)

1582

,gene_id,symbol,gene_type,tumor_1,tumor_2,tumor_3,tumor_4,tumor_5,tumor_6,tumor_7,tumor_8,tumor_9,tumor_10,tumor_11,entropy,entropy_q,total_sum
0,ENSG00000135919,SERPINE2,protein_coding,189,821,1026,2040,1170,216535,5,599,193,1394,754,0.329341,0,224726
1,ENSG00000235162,C12orf75,protein_coding,627,56,231,253,47,22188,52,620,113,203,70,0.563498,0,24460
2,ENSG00000235174,RPL39P3,processed_pseudogene,73,87,72,89,12,13687,0,213,11,663,58,0.612907,0,14965

In [47]:
df_tumor3.head(30)

,gene_id,symbol,gene_type,tumor_1,tumor_2,tumor_3,tumor_4,tumor_5,tumor_6,tumor_7,tumor_8,tumor_9,tumor_10,tumor_11,entropy,entropy_q,total_sum
0,ENSG00000135919,SERPINE2,protein_coding,189,821,1026,2040,1170,216535,5,599,193,1394,754,0.329341,0,224726
1,ENSG00000235162,C12orf75,protein_coding,627,56,231,253,47,22188,52,620,113,203,70,0.563498,0,24460
2,ENSG00000235174,RPL39P3,processed_pseudogene,73,87,72,89,12,13687,0,213,11,663,58,0.612907,0,14965
3,ENSG00000080823,MOK,protein_coding,61,120,114,166,139,13949,15,93,79,424,112,0.614011,0,15272
4,ENSG00000101955,SRPX,protein_coding,52,600,238,82,183,16806,0,96,36,284,78,0.672237,0,18455
5,ENSG00000178031,ADAMTSL1,protein_coding,62,58,148,28,107,6498,10,10,53,170,82,0.673331,0,7226
6,ENSG00000164266,SPINK1,protein_coding,64067,83,10713,10,85,63,0,11,81,252,41,0.677665,0,75406
7,ENSG00000108602,ALDH3A1,protein_coding,4439,635,54,70,10533,17,1,22,4,114336,293,0.696827,0,130404
8,ENSG00000152049,KCNE4,protein_coding,33,73,417,128,104,184,1,331,34,15081,243,0.701489,0,16629
9,ENSG00000174028,FAM3C2P,processed_pseudogene,29,224,115,23,69,8168,0,215,95,249,122,0.887762,0,9309
10,ENSG00000183287,CCBE1,protein_coding,40,96,204,22,118,5339,0,160,28,89,87,0.969824,0,6183
11,ENSG00000100302,RASD2,protein_coding,33,55,280,6833,72,278,1,39,171,48,146,0.972276,0,7956
12,ENSG00000234851,RPL23AP42,processed_pseudogene,78,41,115,87,21,5254,0,139,29,315,55,0.983687,0,6134
13,ENSG00000164465,DCBLD1,protein_coding,383,833,818,261,658,37806,72,809,459,1049,1732,1.018384,0,44880
14,ENSG00000101842,VSIG1,protein_coding,76,485,151,26,24,36,12,6823,68,586,55,1.026197,0,8342
15,ENSG00000218426,AL590867.2,processed_pseudogene,83,100,103,78,15,5620,0,55,39,617,49,1.041269,0,6759
16,ENSG00000229867,STEAP3-AS1,lncRNA,65,149,236,70,222,5696,82,168,77,516,167,1.046433,0,7448
17,ENSG00000174837,ADGRE1,protein_coding,60,61,60,2,63,2084,0,9,22,58,59,1.089716,0,2478
18,ENSG00000101938,CHRDL1,protein_coding,53,469,533,313,245,14553,0,27,86,1080,239,1.116503,0,17598
19,ENSG00000152128,TMEM163,protein_coding,244,390,389,186,88,323,19,553,415,14020,251,1.117022,0,16878
20,ENSG00000246859,STARD4-AS1,lncRNA,482,473,1155,25030,454,1092,2704,822,506,1523,805,1.117713,0,35046
21,ENSG00000118308,IRAG2,protein_coding,14,53,179,5050,126,219,23,36,117,288,124,1.133032,0,6229
22,ENSG00000214548,MEG3,lncRNA,241,36,137,75,40,320,3,75,87,5238,106,1.147645,0,6358
23,ENSG00000168679,SLC16A4,protein_coding,1699,139,294,52,1017,1593,483,48,391,23929,190,1.148941,0,29835
24,ENSG00000021826,CPS1,protein_coding,10262,280,57,27,2854,278,1,38,6,71,67,1.169496,0,13941
25,ENSG00000159228,CBR1,protein_coding,1100,1651,1315,971,1617,6124,1,1062,735,72218,2014,1.217479,0,88808
26,ENSG00000007402,CACNA2D2,protein_coding,888,382,1797,76,477,1301,70,322,94,19349,285,1.239488,0,25041
27,ENSG00000164867,NOS3,protein_coding,104,152,460,118,371,581,6,482,707,13430,225,1.253099,0,16636
28,ENSG00000153446,C16orf89,protein_coding,802,825,2975,30,286,1695,1,264,1407,32931,264,1.262399,0,41480
29,ENSG00000169550,MUC15,protein_coding,132,818,115,29,13,1399,48,102,430,102,10439,1.265104,0,13627

In [49]:
df_tumor3.tail(30)

,gene_id,symbol,gene_type,tumor_1,tumor_2,tumor_3,tumor_4,tumor_5,tumor_6,tumor_7,tumor_8,tumor_9,tumor_10,tumor_11,entropy,entropy_q,total_sum
1552,ENSG00000205542,TMSB4X,protein_coding,10410,56120,50469,23782,14338,247913,25,24118,22609,87685,15153,2.558076,0,552622
1553,ENSG00000169093,ASMTL,protein_coding,474,0,936,0,0,0,55,476,409,1057,608,2.558131,0,4015
1554,ENSG00000169093,ASMTL,protein_coding,474,0,936,819,417,0,55,476,0,1057,0,2.558485,0,4234
1555,ENSG00000169093,ASMTL,protein_coding,474,0,936,0,417,2019,0,0,409,1057,608,2.558664,0,5920
1556,ENSG00000133134,BEX2,protein_coding,218,120,511,948,36,2379,0,428,6,680,538,2.558702,0,5864
1557,ENSG00000169093,ASMTL,protein_coding,474,766,936,0,0,0,55,476,409,1057,0,2.558892,0,4173
1558,ENSG00000169093,ASMTL,protein_coding,0,0,936,0,417,2019,0,476,409,1057,608,2.559029,0,5922
1559,ENSG00000144120,TMEM177,protein_coding,356,214,316,271,153,2433,0,398,145,535,175,2.559243,0,4996
1560,ENSG00000096088,PGC,protein_coding,632,757,1394,10,621,2151,4,20,182,2587,149,2.559266,0,8507
1561,ENSG00000272288,AL451165.2,lncRNA,150,137,196,208,141,335,131,136,126,341,347,2.559293,0,2248
1562,ENSG00000182378,PLCXD1,protein_coding,0,173,353,790,216,845,9,411,0,0,1140,2.559420,0,3937
1563,ENSG00000169093,ASMTL,protein_coding,474,766,0,819,417,0,55,0,409,1057,0,2.559435,0,3997
1564,ENSG00000143502,SUSD4,protein_coding,48,843,258,164,39,32,1,150,142,886,142,2.559459,0,2705
1565,ENSG00000169093,ASMTL,protein_coding,474,0,936,0,417,0,55,476,0,1057,608,2.559572,0,4023
1566,ENSG00000162757,C1orf74,protein_coding,193,133,234,379,171,774,106,207,139,811,187,2.559629,0,3334
1567,ENSG00000169093,ASMTL,protein_coding,0,766,0,819,417,0,55,476,409,1057,0,2.559692,0,3999
1568,ENSG00000174791,RIN1,protein_coding,146,186,221,51,254,1592,1,402,149,269,86,2.559761,0,3357
1569,ENSG00000182378,PLCXD1,protein_coding,315,173,353,0,0,0,0,411,321,424,1140,2.559801,0,3137
1570,ENSG00000169093,ASMTL,protein_coding,474,766,936,0,417,0,55,476,0,1057,0,2.560384,0,4181
1571,ENSG00000112936,C7,protein_coding,893,1329,3357,490,1824,5631,1,28,449,8843,1269,2.560412,0,24114
1572,ENSG00000285830,AL109628.2,lncRNA,240,341,592,290,318,1050,1219,393,293,1489,377,2.560413,0,6602
1573,ENSG00000169093,ASMTL,protein_coding,0,0,936,819,417,0,55,0,409,1057,608,2.560624,0,4301
1574,ENSG00000005020,SKAP2,protein_coding,1495,695,1753,810,1372,11674,2,1429,702,2302,1562,2.560761,0,23796
1575,ENSG00000221890,NPTXR,protein_coding,663,93,185,742,160,2272,1,229,123,491,189,2.561256,0,5148
1576,ENSG00000169093,ASMTL,protein_coding,474,0,0,819,417,0,55,0,409,1057,608,2.561270,0,3839
1577,ENSG00000115009,CCL20,protein_coding,53,164,572,79,709,227,5,3214,1272,2316,3080,2.561322,0,11691
1578,ENSG00000169093,ASMTL,protein_coding,0,0,0,819,417,0,55,476,409,1057,608,2.561507,0,3841
1579,ENSG00000182378,PLCXD1,protein_coding,0,173,353,790,216,845,9,0,0,424,1140,2.561659,0,3950
1580,ENSG00000169093,ASMTL,protein_coding,474,766,0,819,0,2019,0,476,409,0,608,2.561991,0,5571
1581,ENSG00000169093,ASMTL,protein_coding,0,766,936,0,417,0,55,0,409,1057,608,2.562234,0,4248

In [50]:
geneid_list = np.unique(df_tumor3['gene_id'])

len(geneid_list)

1018

### GTEx portal

In [68]:
print(len(geneid_list))
np.array(geneid_list[:50])

1018

array(['ENSG00000001626', 'ENSG00000003989', 'ENSG00000004468',
       'ENSG00000005020', 'ENSG00000005059', 'ENSG00000006007',
       'ENSG00000006016', 'ENSG00000006210', 'ENSG00000006534',
       'ENSG00000006747', 'ENSG00000007402', 'ENSG00000008226',
       'ENSG00000008735', 'ENSG00000008853', 'ENSG00000012171',
       'ENSG00000017483', 'ENSG00000018236', 'ENSG00000019102',
       'ENSG00000019186', 'ENSG00000021300', 'ENSG00000021826',
       'ENSG00000022267', 'ENSG00000022556', 'ENSG00000023171',
       'ENSG00000023839', 'ENSG00000025423', 'ENSG00000025708',
       'ENSG00000026103', 'ENSG00000026508', 'ENSG00000029153',
       'ENSG00000034053', 'ENSG00000038002', 'ENSG00000040531',
       'ENSG00000043039', 'ENSG00000047457', 'ENSG00000047662',
       'ENSG00000047936', 'ENSG00000048052', 'ENSG00000049247',
       'ENSG00000051128', 'ENSG00000053918', 'ENSG00000057294',
       'ENSG00000060718', 'ENSG00000060982', 'ENSG00000062038',
       'ENSG00000064199', 'ENSG00000064205', 'ENSG00000064225',
       'ENSG00000064763', 'ENSG00000064787'], dtype=object)

In [69]:
GTEX_API = "https://gtexportal.org/api/v2"

In [70]:
def resolve_gtex_gencode_id(gene_id, datasetId="gtex_v8", timeout=60):
    gene_base = str(gene_id).split(".")[0]

    url = f"{GTEX_API}/reference/gene"

    params = {
        "geneId": gene_base,
        "datasetId": datasetId,
    }

    r = requests.get(url, params=params, timeout=timeout)
    r.raise_for_status()

    data = r.json().get("data", [])

    if not data:
        return None

    return data[0].get("gencodeId")

In [74]:


def get_gtex_expression_for_geneid_list(
    gtex_id:str,
    geneid_list:list,
    datasetId:str="gtex_v8",
    page_size:int=1000,
    sleep: float = 0.1,
    timeout:int=60,
    verbose:bool=False,
):
    """
    Download GTEx normal tissue expression for selected genes.
    Returns long-format dataframe:
    geneSymbol | gencodeId | tissueSiteDetailId | sampleId | tpm | log2Tpm
    """

    all_rows = []

    print(">>>", len(geneid_list))
    for i, geneid in enumerate(geneid_list):
        page = 0

        while True:

            gencode_id = resolve_gtex_gencode_id(geneid)
            print(">>>", gencode_id, end=" ")

            if gencode_id is None:
                print("?")
                if verbose: print(f"Nothing found for {geneid}")
                break
            
            url = f"{GTEX_API}/expression/geneExpression"

            params = {
                "datasetId": datasetId,
                "gencodeId": gencode_id,
                "tissueSiteDetailId": gtex_id,
                "page": page,
                "itemsPerPage": page_size,
            }

            r = requests.get(url, params=params, timeout=timeout)
            r.raise_for_status()

            js = r.json()
            data = js.get("data", [])

            if not data:
                print("x")
                if verbose: print(f"Error: could not retrieve data for {gtex_id} for geneid '{geneid}'")
                break

            print("Ok")

            all_rows.extend(data)

            paging = js.get("paging_info", {})
            n_pages = paging.get("numberOfPages", 1)

            page += 1
            if page >= n_pages:
                break

            time.sleep(sleep)

    print("")
    df = pd.DataFrame(all_rows)
    return df

In [75]:
gtex_id

'Lung'

In [76]:
df_gtex = get_gtex_expression_for_geneid_list(
                gtex_id=gtex_id,
                geneid_list=geneid_list,
                datasetId="gtex_v8",
                page_size=1000,
                sleep = 0.1,
                timeout=60)

print(df_gtex.shape)

>>> 1018
>>> ENSG00000001626.14 Ok
>>> ENSG00000003989.17 Ok
>>> ENSG00000004468.12 Ok
>>> ENSG00000005020.12 Ok
>>> ENSG00000005059.15 Ok
>>> ENSG00000006007.11 Ok
>>> ENSG00000006016.10 Ok
>>> ENSG00000006210.6 Ok
>>> ENSG00000006534.15 Ok
>>> ENSG00000006747.14 Ok
>>> ENSG00000007402.11 Ok
>>> ENSG00000008226.19 Ok
>>> ENSG00000008735.13 Ok
>>> ENSG00000008853.16 Ok
>>> ENSG00000012171.19 Ok
>>> ENSG00000017483.14 Ok
>>> ENSG00000018236.14 Ok
>>> ENSG00000019102.11 Ok
>>> ENSG00000019186.9 Ok
>>> ENSG00000021300.13 Ok
>>> ENSG00000021826.14 Ok
>>> ENSG00000022267.16 Ok
>>> ENSG00000022556.15 Ok
>>> ENSG00000023171.16 Ok
>>> ENSG00000023839.10 Ok
>>> ENSG00000025423.11 Ok
>>> ENSG00000025708.13 Ok
>>> ENSG00000026103.21 Ok
>>> ENSG00000026508.17 Ok
>>> ENSG00000029153.14 Ok
>>> ENSG00000034053.14 Ok
>>> ENSG00000038002.8 Ok
>>> ENSG00000040531.14 Ok
>>> ENSG00000043039.6 Ok
>>> ENSG00000047457.13 Ok
>>> ENSG00000047662.4 Ok
>>> ENSG00000047936.10 Ok
>>> ENSG00000048052.21 Ok
>>> ENSG00000049247.13 Ok
>>> ENSG00000051128.18 Ok
>>> ENSG00000053918.15 Ok
>>> ENSG00000057294.14 Ok
>>> ENSG00000060718.20 Ok
>>> ENSG00000060982.14 Ok
>>> ENSG00000062038.13 Ok
>>> ENSG00000064199.6 Ok
>>> ENSG00000064205.10 Ok
>>> ENSG00000064225.12 Ok
>>> ENSG00000064763.10 Ok
>>> ENSG00000064787.13 Ok
>>> ENSG00000064886.13 Ok
>>> ENSG00000065328.16 Ok
>>> ENSG00000066405.12 Ok
>>> ENSG00000066855.15 Ok
>>> ENSG00000067057.16 Ok
>>> ENSG00000068078.17 Ok
>>> ENSG00000069122.18 Ok
>>> ENSG00000069188.16 Ok
>>> ENSG00000069535.13 Ok
>>> ENSG00000070019.4 Ok
>>> ENSG00000070182.19 Ok
>>> ENSG00000070961.15 Ok
>>> ENSG00000072210.18 Ok
>>> ENSG00000072756.16 Ok
>>> ENSG00000072858.10 Ok
>>> ENSG00000072864.14 Ok
>>> ENSG00000073282.12 Ok
>>> ENSG00000073756.11 Ok
>>> ENSG00000073792.15 Ok
>>> ENSG00000074706.13 Ok
>>> ENSG00000075213.10 Ok
>>> ENSG00000075239.13 Ok
>>> ENSG00000075461.5 Ok
>>> ENSG00000075643.5 Ok
>>> ENSG00000075975.15 Ok
>>> ENSG00000076864.19 Ok
>>> ENSG00000078018.19 Ok
>>> ENSG00000080293.9 Ok
>>> ENSG00000080819.6 Ok
>>> ENSG00000080823.22 Ok
>>> ENSG00000081059.19 Ok
>>> ENSG00000085276.17 Ok
>>> ENSG00000085662.13 Ok
>>> ENSG00000085788.13 Ok
>>> ENSG00000085998.13 Ok
>>> ENSG00000087128.9 Ok
>>> ENSG00000087470.17 Ok
>>> ENSG00000087842.10 Ok
>>> ENSG00000088205.12 Ok
>>> ENSG00000088305.18 Ok
>>> ENSG00000088992.17 Ok
>>> ENSG00000089041.16 Ok
>>> ENSG00000090530.9 Ok
>>> ENSG00000091129.19 Ok
>>> ENSG00000091136.13 Ok
>>> ENSG00000091651.8 Ok
>>> ENSG00000091831.22 Ok
>>> ENSG00000091844.7 Ok
>>> ENSG00000092621.11 Ok
>>> ENSG00000093009.9 Ok
>>> ENSG00000095303.14 Ok
>>> ENSG00000095539.15 Ok
>>> ENSG00000095713.13 Ok
>>> ENSG00000095739.10 Ok
>>> ENSG00000096088.16 Ok
>>> ENSG00000096696.13 Ok
>>> ENSG00000099204.18 Ok
>>> ENSG00000099377.13 Ok
>>> ENSG00000099804.8 Ok
>>> ENSG00000099812.8 Ok
>>> ENSG00000099937.10 Ok
>>> ENSG00000099994.10 Ok
>>> ENSG00000100003.17 Ok
>>> ENSG00000100065.14 Ok
>>> ENSG00000100097.11 Ok
>>> ENSG00000100167.19 Ok
>>> ENSG00000100302.6 Ok
>>> ENSG00000100473.15 Ok
>>> ENSG00000100567.12 Ok
>>> ENSG00000100749.7 Ok
>>> ENSG00000101003.9 Ok
>>> ENSG00000101057.15 Ok
>>> ENSG00000101210.10 Ok
>>> ENSG00000101336.13 Ok
>>> ENSG00000101457.12 Ok
>>> ENSG00000101670.11 Ok
>>> ENSG00000101842.13 Ok
>>> ENSG00000101928.12 Ok
>>> ENSG00000101938.14 Ok
>>> ENSG00000101955.14 Ok
>>> ENSG00000102466.15 Ok
>>> ENSG00000102854.15 Ok
>>> ENSG00000102910.13 Ok
>>> ENSG00000102962.4 Ok
>>> ENSG00000103460.16 Ok
>>> ENSG00000103888.16 Ok
>>> ENSG00000103942.12 Ok
>>> ENSG00000104154.6 Ok
>>> ENSG00000104218.14 Ok
>>> ENSG00000104221.12 Ok
>>> ENSG00000104368.17 Ok
>>> ENSG00000104524.13 Ok
>>> ENSG00000104691.14 Ok
>>> ENSG00000104760.16 Ok
>>> ENSG00000104892.16 Ok
>>> ENSG00000104907.12 Ok
>>> ENSG00000104980.7 Ok
>>> ENSG00000105364.13 Ok
>>> ENSG00000105388.15 Ok
>>> ENSG00000105464.3 Ok
>>> ENSG00000105664.10 Ok
>>> ENSG00000105825.11 Ok
>>> ENSG00000105855.9 Ok
>>> ENSG00000105877.17 Ok
>>> ENSG00000105997.22 Ok
>>> ENSG00000106066.14 Ok
>>> ENSG00000106565.17 Ok
>>> ENSG00000107201.9 Ok
>>> ENSG00000107562.16 Ok
>>> ENSG00000107833.10 Ok
>>> ENSG00000108474.16 Ok
>>> ENSG00000108551.4 Ok
>>> ENSG00000108602.17 Ok
>>> ENSG00000109321.10 Ok
>>> ENSG00000109674.3 Ok
>>> ENSG00000109805.9 Ok
>>> ENSG00000109861.15 Ok
>>> ENSG00000109906.13 Ok
>>> ENSG00000110195.12 Ok
>>> ENSG00000110811.19 Ok
>>> ENSG00000110900.14 Ok
>>> ENSG00000111110.11 Ok
>>> ENSG00000111186.12 Ok
>>> ENSG00000111247.14 Ok
>>> ENSG00000111275.12 Ok
>>> ENSG00000111452.12 Ok
>>> ENSG00000111615.13 Ok
>>> ENSG00000111799.20 Ok
>>> ENSG00000111817.16 Ok
>>> ENSG00000111875.7 Ok
>>> ENSG00000112237.12 Ok
>>> ENSG00000112742.9 Ok
>>> ENSG00000112769.18 Ok
>>> ENSG00000112936.18 Ok
>>> ENSG00000113319.12 Ok
>>> ENSG00000113494.16 Ok
>>> ENSG00000113749.7 Ok
>>> ENSG00000113851.14 Ok
>>> ENSG00000113924.11 Ok
>>> ENSG00000114270.17 Ok
>>> ENSG00000114790.12 Ok
>>> ENSG00000115009.11 Ok
>>> ENSG00000115107.19 Ok
>>> ENSG00000115221.10 Ok
>>> ENSG00000115255.10 Ok
>>> ENSG00000115380.19 Ok
>>> ENSG00000115414.18 Ok
>>> ENSG00000115419.12 Ok
>>> ENSG00000115457.9 Ok
>>> ENSG00000115641.18 Ok
>>> ENSG00000115841.19 Ok
>>> ENSG00000115919.14 Ok
>>> ENSG00000116106.11 Ok
>>> ENSG00000116132.11 Ok
>>> ENSG00000116299.16 Ok
>>> ENSG00000116661.9 Ok
>>> ENSG00000116711.9 Ok
>>> ENSG00000116761.11 Ok
>>> ENSG00000116774.11 Ok
>>> ENSG00000116991.10 Ok
>>> ENSG00000117091.9 Ok
>>> ENSG00000117228.9 Ok
>>> ENSG00000117472.9 Ok
>>> ENSG00000117525.13 Ok
>>> ENSG00000117983.17 Ok
>>> ENSG00000118308.15 Ok
>>> ENSG00000118407.14 Ok
>>> ENSG00000118513.18 Ok
>>> ENSG00000118849.9 Ok
>>> ENSG00000119655.10 Ok
>>> ENSG00000119917.13 Ok
>>> ENSG00000119922.9 Ok
>>> ENSG00000119927.13 Ok
>>> ENSG00000119938.8 Ok
>>> ENSG00000120217.13 Ok
>>> ENSG00000120675.5 Ok
>>> ENSG00000120885.21 Ok
>>> ENSG00000120992.17 Ok
>>> ENSG00000121039.9 Ok
>>> ENSG00000121281.12 Ok
>>> ENSG00000121350.15 Ok
>>> ENSG00000121361.3 Ok
>>> ENSG00000122852.14 Ok
>>> ENSG00000122862.4 Ok
>>> ENSG00000123094.15 Ok
>>> ENSG00000123552.17 Ok
>>> ENSG00000123689.5 Ok
>>> ENSG00000123838.10 Ok
>>> ENSG00000124120.10 Ok
>>> ENSG00000124191.17 Ok
>>> ENSG00000124243.17 Ok
>>> ENSG00000124429.17 Ok
>>> ENSG00000124615.17 Ok
>>> ENSG00000125378.15 Ok
>>> ENSG00000125629.14 Ok
>>> ENSG00000125656.8 Ok
>>> ENSG00000125731.12 Ok
>>> ENSG00000125775.14 Ok
>>> ENSG00000125827.8 Ok
>>> ENSG00000125872.7 Ok
>>> ENSG00000125966.9 Ok
>>> ENSG00000125999.10 Ok
>>> ENSG00000126215.13 Ok
>>> ENSG00000126878.12 Ok
>>> ENSG00000127324.8 Ok
>>> ENSG00000128422.15 Ok
>>> ENSG00000128578.9 Ok
>>> ENSG00000128591.15 Ok
>>> ENSG00000128944.13 Ok
>>> ENSG00000129354.11 Ok
>>> ENSG00000129355.6 Ok
>>> ENSG00000129680.15 Ok
>>> ENSG00000129682.15 Ok
>>> ENSG00000129810.14 Ok
>>> ENSG00000130270.16 Ok
>>> ENSG00000130303.12 Ok
>>> ENSG00000130332.14 Ok
>>> ENSG00000130812.10 Ok
>>> ENSG00000130816.14 Ok
>>> ENSG00000130830.14 Ok
>>> ENSG00000130962.17 Ok
>>> ENSG00000131203.12 Ok
>>> ENSG00000131400.7 Ok
>>> ENSG00000131401.11 Ok
>>> ENSG00000131408.13 Ok
>>> ENSG00000131470.14 Ok
>>> ENSG00000131746.12 Ok
>>> ENSG00000131771.13 Ok
>>> ENSG00000131781.12 Ok
>>> ENSG00000132004.12 Ok
>>> ENSG00000132017.10 Ok
>>> ENSG00000132182.11 Ok
>>> ENSG00000132274.15 Ok
>>> ENSG00000132688.10 Ok
>>> ENSG00000132840.9 Ok
>>> ENSG00000133048.12 Ok
>>> ENSG00000133106.14 Ok
>>> ENSG00000133134.11 Ok
>>> ENSG00000133135.13 Ok
>>> ENSG00000133641.17 Ok
>>> ENSG00000133661.15 Ok
>>> ENSG00000133703.11 Ok
>>> ENSG00000133740.10 Ok
>>> ENSG00000133794.17 Ok
>>> ENSG00000133812.15 Ok
>>> ENSG00000133818.13 Ok
>>> ENSG00000134020.7 Ok
>>> ENSG00000134077.15 Ok
>>> ENSG00000134121.9 Ok
>>> ENSG00000134152.10 Ok
>>> ENSG00000134222.16 Ok
>>> ENSG00000134258.16 Ok
>>> ENSG00000134321.11 Ok
>>> ENSG00000134326.11 Ok
>>> ENSG00000134490.13 Ok
>>> ENSG00000134504.12 Ok
>>> ENSG00000134668.12 Ok
>>> ENSG00000134775.15 Ok
>>> ENSG00000134986.13 Ok
>>> ENSG00000135114.12 Ok
>>> ENSG00000135119.14 Ok
>>> ENSG00000135299.16 Ok
>>> ENSG00000135318.11 Ok
>>> ENSG00000135362.13 Ok
>>> ENSG00000135423.12 Ok
>>> ENSG00000135451.12 Ok
>>> ENSG00000135549.14 Ok
>>> ENSG00000135678.11 Ok
>>> ENSG00000135778.11 Ok
>>> ENSG00000135919.12 Ok
>>> ENSG00000136155.16 Ok
>>> ENSG00000136982.5 Ok
>>> ENSG00000137124.7 Ok
>>> ENSG00000137135.17 Ok
>>> ENSG00000137203.10 Ok
>>> ENSG00000137310.11 Ok
>>> ENSG00000137331.11 Ok
>>> ENSG00000137440.4 Ok
>>> ENSG00000137547.8 Ok
>>> ENSG00000137628.16 Ok
>>> ENSG00000137673.8 Ok
>>> ENSG00000137699.16 Ok
>>> ENSG00000137709.9 Ok
>>> ENSG00000137745.11 Ok
>>> ENSG00000137825.10 Ok
>>> ENSG00000137868.18 Ok
>>> ENSG00000137959.15 Ok
>>> ENSG00000137962.12 Ok
>>> ENSG00000137965.10 Ok
>>> ENSG00000137968.16 Ok
>>> ENSG00000137970.7 Ok
>>> ENSG00000138135.6 Ok
>>> ENSG00000138162.18 Ok
>>> ENSG00000138271.5 Ok
>>> ENSG00000138615.5 Ok
>>> ENSG00000138640.14 Ok
>>> ENSG00000138646.8 Ok
>>> ENSG00000138678.10 Ok
>>> ENSG00000138755.5 Ok
>>> ENSG00000138764.14 Ok
>>> ENSG00000138772.12 Ok
>>> ENSG00000138785.14 Ok
>>> ENSG00000139146.13 Ok
>>> ENSG00000139239.7 Ok
>>> ENSG00000139278.9 Ok
>>> ENSG00000139318.7 Ok
>>> ENSG00000139351.14 Ok
>>> ENSG00000139508.14 Ok
>>> ENSG00000139626.15 Ok
>>> ENSG00000139629.15 Ok
>>> ENSG00000140105.17 Ok
>>> ENSG00000140254.12 Ok
>>> ENSG00000140297.12 Ok
>>> ENSG00000140534.13 Ok
>>> ENSG00000140564.11 Ok
>>> ENSG00000140945.16 Ok
>>> ENSG00000141576.14 Ok
>>> ENSG00000141994.15 Ok
>>> ENSG00000142459.8 Ok
>>> ENSG00000142512.14 Ok
>>> ENSG00000143153.12 Ok
>>> ENSG00000143156.13 Ok
>>> ENSG00000143228.12 Ok
>>> ENSG00000143257.11 Ok
>>> ENSG00000143320.8 Ok
>>> ENSG00000143412.9 Ok
>>> ENSG00000143416.20 Ok
>>> ENSG00000143502.14 Ok
>>> ENSG00000143507.17 Ok
>>> ENSG00000143512.12 Ok
>>> ENSG00000143546.9 Ok
>>> ENSG00000143653.9 Ok
>>> ENSG00000143819.12 Ok
>>> ENSG00000143891.16 Ok
>>> ENSG00000144118.13 Ok
>>> ENSG00000144120.12 Ok
>>> ENSG00000144476.5 Ok
>>> ENSG00000144868.13 Ok
>>> ENSG00000145113.21 Ok
>>> ENSG00000145287.10 Ok
>>> ENSG00000145358.6 Ok
>>> ENSG00000145386.9 Ok
>>> ENSG00000145824.12 Ok
>>> ENSG00000146122.16 Ok
>>> ENSG00000146166.16 Ok
>>> ENSG00000146197.8 Ok
>>> ENSG00000146477.5 Ok
>>> ENSG00000146648.17 Ok
>>> ENSG00000147364.16 Ok
>>> ENSG00000147536.11 Ok
>>> ENSG00000147548.16 Ok
>>> ENSG00000147642.16 Ok
>>> ENSG00000147687.18 Ok
>>> ENSG00000147872.9 Ok
>>> ENSG00000148346.11 Ok
>>> ENSG00000148671.13 Ok
>>> ENSG00000148702.14 Ok
>>> ENSG00000149021.6 Ok
>>> ENSG00000149260.15 Ok
>>> ENSG00000149557.12 Ok
>>> ENSG00000150636.17 Ok
>>> ENSG00000150782.11 Ok
>>> ENSG00000151012.13 Ok
>>> ENSG00000151090.17 Ok
>>> ENSG00000151332.18 Ok
>>> ENSG00000151474.21 Ok
>>> ENSG00000151575.14 Ok
>>> ENSG00000151632.17 Ok
>>> ENSG00000151651.15 Ok
>>> ENSG00000152049.6 Ok
>>> ENSG00000152128.13 Ok
>>> ENSG00000152137.6 Ok
>>> ENSG00000152229.18 Ok
>>> ENSG00000152284.4 Ok
>>> ENSG00000152455.15 Ok
>>> ENSG00000152784.15 Ok
>>> ENSG00000152785.6 Ok
>>> ENSG00000153292.15 Ok
>>> ENSG00000153363.12 Ok
>>> ENSG00000153446.15 Ok
>>> ENSG00000154025.15 Ok
>>> ENSG00000154040.20 Ok
>>> ENSG00000154065.16 Ok
>>> ENSG00000154146.12 Ok
>>> ENSG00000154277.12 Ok
>>> ENSG00000154319.14 Ok
>>> ENSG00000154451.14 Ok
>>> ENSG00000154556.17 Ok
>>> ENSG00000154839.9 Ok
>>> ENSG00000155096.13 Ok
>>> ENSG00000155307.17 Ok
>>> ENSG00000155380.11 Ok
>>> ENSG00000155438.11 Ok
>>> ENSG00000155657.26 Ok
>>> ENSG00000155659.14 Ok
>>> ENSG00000155760.2 Ok
>>> ENSG00000155957.17 Ok
>>> ENSG00000155962.12 Ok
>>> ENSG00000156050.8 Ok
>>> ENSG00000156234.7 Ok
>>> ENSG00000156298.12 Ok
>>> ENSG00000156299.13 Ok
>>> ENSG00000156463.17 Ok
>>> ENSG00000156510.12 Ok
>>> ENSG00000156535.13 Ok
>>> ENSG00000156738.17 Ok
>>> ENSG00000157064.10 Ok
>>> ENSG00000157399.14 Ok
>>> ENSG00000157404.15 Ok
>>> ENSG00000157456.7 Ok
>>> ENSG00000157601.13 Ok
>>> ENSG00000158125.9 Ok
>>> ENSG00000158467.16 Ok
>>> ENSG00000158825.5 Ok
>>> ENSG00000159164.9 Ok
>>> ENSG00000159167.11 Ok
>>> ENSG00000159189.11 Ok
>>> ENSG00000159212.12 Ok
>>> ENSG00000159228.12 Ok
>>> ENSG00000159231.5 Ok
>>> ENSG00000159348.12 Ok
>>> ENSG00000160111.12 Ok
>>> ENSG00000160180.15 Ok
>>> ENSG00000160469.16 Ok
>>> ENSG00000160862.12 Ok
>>> ENSG00000160932.10 Ok
>>> ENSG00000160957.12 Ok
>>> ENSG00000160973.7 Ok
>>> ENSG00000161055.3 Ok
>>> ENSG00000161888.11 Ok
>>> ENSG00000162545.5 Ok
>>> ENSG00000162645.12 Ok
>>> ENSG00000162654.8 Ok
>>> ENSG00000162738.5 Ok
>>> ENSG00000162757.4 Ok
>>> ENSG00000162896.5 Ok
>>> ENSG00000162949.16 Ok
>>> ENSG00000163072.15 Ok
>>> ENSG00000163075.12 Ok
>>> ENSG00000163110.14 Ok
>>> ENSG00000163141.18 Ok
>>> ENSG00000163220.10 Ok
>>> ENSG00000163235.15 Ok
>>> ENSG00000163297.16 Ok
>>> ENSG00000163568.14 Ok
>>> ENSG00000163577.7 Ok
>>> ENSG00000163584.17 Ok
>>> ENSG00000163636.10 Ok
>>> ENSG00000163659.12 Ok
>>> ENSG00000163735.6 Ok
>>> ENSG00000163762.6 Ok
>>> ENSG00000163879.10 Ok
>>> ENSG00000163975.11 Ok
>>> ENSG00000163993.6 Ok
>>> ENSG00000164070.11 Ok
>>> ENSG00000164087.7 Ok
>>> ENSG00000164099.3 Ok
>>> ENSG00000164109.13 Ok
>>> ENSG00000164120.13 Ok
>>> ENSG00000164176.12 Ok
>>> ENSG00000164265.8 Ok
>>> ENSG00000164266.10 Ok
>>> ENSG00000164292.12 Ok
>>> ENSG00000164414.17 Ok
>>> ENSG00000164430.15 Ok
>>> ENSG00000164465.18 Ok
>>> ENSG00000164694.16 Ok
>>> ENSG00000164758.7 Ok
>>> ENSG00000164867.10 Ok
>>> ENSG00000164930.11 Ok
>>> ENSG00000164949.7 Ok
>>> ENSG00000165046.12 Ok
>>> ENSG00000165272.14 Ok
>>> ENSG00000165304.7 Ok
>>> ENSG00000165516.10 Ok
>>> ENSG00000165525.17 Ok
>>> ENSG00000165819.11 Ok
>>> ENSG00000165949.12 Ok
>>> ENSG00000166016.5 Ok
>>> ENSG00000166123.13 Ok
>>> ENSG00000166143.9 Ok
>>> ENSG00000166206.14 Ok
>>> ENSG00000166250.11 Ok
>>> ENSG00000166347.18 Ok
>>> ENSG00000166532.15 Ok
>>> ENSG00000166582.9 Ok
>>> ENSG00000166669.13 Ok
>>> ENSG00000166676.14 Ok
>>> ENSG00000166741.7 Ok
>>> ENSG00000166816.13 Ok
>>> ENSG00000166825.13 Ok
>>> ENSG00000166851.14 Ok
>>> ENSG00000166920.12 Ok
>>> ENSG00000167191.11 Ok
>>> ENSG00000167286.9 Ok
>>> ENSG00000167476.10 Ok
>>> ENSG00000167601.11 Ok
>>> ENSG00000167702.11 Ok
>>> ENSG00000167711.13 Ok
>>> ENSG00000167775.10 Ok
>>> ENSG00000167779.7 Ok
>>> ENSG00000167815.11 Ok
>>> ENSG00000168032.8 Ok
>>> ENSG00000168306.12 Ok
>>> ENSG00000168484.12 Ok
>>> ENSG00000168517.10 Ok
>>> ENSG00000168675.18 Ok
>>> ENSG00000168679.17 Ok
>>> ENSG00000168874.12 Ok
>>> ENSG00000168878.16 Ok
>>> ENSG00000168899.4 Ok
>>> ENSG00000169083.16 Ok
>>> ENSG00000169093.15 Ok
>>> ENSG00000169129.14 Ok
>>> ENSG00000169184.5 Ok
>>> ENSG00000169213.6 Ok
>>> ENSG00000169245.5 Ok
>>> ENSG00000169435.13 Ok
>>> ENSG00000169550.12 Ok
>>> ENSG00000169583.12 Ok
>>> ENSG00000169814.12 Ok
>>> ENSG00000169894.17 Ok
>>> ENSG00000169908.11 Ok
>>> ENSG00000170425.3 Ok
>>> ENSG00000170456.15 Ok
>>> ENSG00000170522.9 Ok
>>> ENSG00000170561.12 Ok
>>> ENSG00000171004.18 Ok
>>> ENSG00000171017.10 Ok
>>> ENSG00000171174.13 Ok
>>> ENSG00000171241.8 Ok
>>> ENSG00000171346.15 Ok
>>> ENSG00000171476.21 Ok
>>> ENSG00000171497.4 Ok
>>> ENSG00000171557.16 Ok
>>> ENSG00000171560.14 Ok
>>> ENSG00000171564.11 Ok
>>> ENSG00000171766.15 Ok
>>> ENSG00000171791.12 Ok
>>> ENSG00000171903.16 Ok
>>> ENSG00000172009.14 Ok
>>> ENSG00000172167.7 Ok
>>> ENSG00000172175.12 Ok
>>> ENSG00000172201.11 Ok
>>> ENSG00000172250.14 Ok
>>> ENSG00000172270.18 Ok
>>> ENSG00000172296.12 Ok
>>> ENSG00000172724.11 Ok
>>> ENSG00000172927.7 Ok
>>> ENSG00000173068.17 Ok
>>> ENSG00000173110.7 Ok
>>> ENSG00000173267.13 Ok
>>> ENSG00000173369.15 Ok
>>> ENSG00000173376.13 Ok
>>> ENSG00000173467.8 Ok
>>> ENSG00000173702.7 Ok
>>> ENSG00000173848.18 Ok
>>> ENSG00000173890.16 Ok
>>> ENSG00000173947.13 Ok
>>> ENSG00000174028.6 Ok
>>> ENSG00000174502.18 Ok
>>> ENSG00000174514.12 Ok
>>> ENSG00000174564.12 Ok
>>> ENSG00000174749.5 Ok
>>> ENSG00000174791.10 Ok
>>> ENSG00000174808.11 Ok
>>> ENSG00000174837.14 Ok
>>> ENSG00000174917.8 Ok
>>> ENSG00000174939.10 Ok
>>> ENSG00000175084.11 Ok
>>> ENSG00000175264.7 Ok
>>> ENSG00000175265.17 Ok
>>> ENSG00000175287.18 Ok
>>> ENSG00000175305.17 Ok
>>> ENSG00000175318.11 Ok
>>> ENSG00000175592.8 Ok
>>> ENSG00000176124.11 Ok
>>> ENSG00000176153.11 Ok
>>> ENSG00000176208.8 Ok
>>> ENSG00000176619.12 Ok
>>> ENSG00000176623.11 Ok
>>> ENSG00000176834.13 Ok
>>> ENSG00000176907.4 Ok
>>> ENSG00000177337.7 Ok
>>> ENSG00000177508.11 Ok
>>> ENSG00000177575.12 Ok
>>> ENSG00000177694.15 Ok
>>> ENSG00000178031.16 Ok
>>> ENSG00000178460.17 Ok
>>> ENSG00000178605.13 Ok
>>> ENSG00000178826.10 Ok
>>> ENSG00000178999.12 Ok
>>> ENSG00000179023.8 Ok
>>> ENSG00000179115.10 Ok
>>> ENSG00000179152.19 Ok
>>> ENSG00000179178.10 Ok
>>> ENSG00000179564.3 Ok
>>> ENSG00000179593.15 Ok
>>> ENSG00000179715.12 Ok
>>> ENSG00000179750.15 Ok
>>> ENSG00000180340.6 Ok
>>> ENSG00000180772.6 Ok
>>> ENSG00000180801.13 Ok
>>> ENSG00000181019.12 Ok
>>> ENSG00000181315.10 Ok
>>> ENSG00000181458.10 Ok
>>> ENSG00000181634.7 Ok
>>> ENSG00000181649.5 Ok
>>> ENSG00000181652.19 Ok
>>> ENSG00000182272.11 Ok
>>> ENSG00000182378.13 Ok
>>> ENSG00000182667.14 Ok
>>> ENSG00000182752.9 Ok
>>> ENSG00000182795.12 Ok
>>> ENSG00000182809.10 Ok
>>> ENSG00000182963.9 Ok
>>> ENSG00000182985.17 Ok
>>> ENSG00000183020.13 Ok
>>> ENSG00000183098.10 Ok
>>> ENSG00000183196.8 Ok
>>> ENSG00000183287.13 Ok
>>> ENSG00000183580.9 Ok
>>> ENSG00000183617.4 Ok
>>> ENSG00000183779.6 Ok
>>> ENSG00000183844.16 Ok
>>> ENSG00000183856.10 Ok
>>> ENSG00000184254.16 Ok
>>> ENSG00000184454.6 Ok
>>> ENSG00000184828.9 Ok
>>> ENSG00000184979.9 Ok
>>> ENSG00000185088.13 Ok
>>> ENSG00000185189.17 Ok
>>> ENSG00000185565.11 Ok
>>> ENSG00000185633.10 Ok
>>> ENSG00000185689.15 Ok
>>> ENSG00000185697.16 Ok
>>> ENSG00000185745.9 Ok
>>> ENSG00000185885.15 Ok
>>> ENSG00000186205.12 Ok
>>> ENSG00000186377.7 Ok
>>> ENSG00000186567.12 Ok
>>> ENSG00000186638.16 Ok
>>> ENSG00000186818.12 Ok
>>> ENSG00000186832.8 Ok
>>> ENSG00000186891.13 Ok
>>> ENSG00000186907.7 Ok
>>> ENSG00000187091.13 Ok
>>> ENSG00000187134.13 Ok
>>> ENSG00000187608.8 Ok
>>> ENSG00000187840.4 Ok
>>> ENSG00000188153.12 Ok
>>> ENSG00000188343.12 Ok
>>> ENSG00000188536.12 Ok
>>> ENSG00000188549.12 Ok
>>> ENSG00000188641.12 Ok
>>> ENSG00000188672.17 Ok
>>> ENSG00000188687.17 Ok
>>> ENSG00000188910.7 Ok
>>> ENSG00000188921.13 Ok
>>> ENSG00000188959.9 Ok
>>> ENSG00000189058.8 Ok
>>> ENSG00000189120.4 Ok
>>> ENSG00000189221.9 Ok
>>> ENSG00000189223.14 Ok
>>> ENSG00000189334.8 Ok
>>> ENSG00000189377.8 Ok
>>> ENSG00000196126.11 Ok
>>> ENSG00000196139.13 Ok
>>> ENSG00000196151.10 Ok
>>> ENSG00000196154.11 Ok
>>> ENSG00000196155.12 Ok
>>> ENSG00000196167.9 Ok
>>> ENSG00000196177.12 Ok
>>> ENSG00000196188.10 Ok
>>> ENSG00000196205.8 Ok
>>> ENSG00000196260.4 Ok
>>> ENSG00000196470.11 Ok
>>> ENSG00000196611.4 Ok
>>> ENSG00000196616.13 Ok
>>> ENSG00000196735.11 Ok
>>> ENSG00000196754.10 Ok
>>> ENSG00000196937.10 Ok
>>> ENSG00000197249.13 Ok
>>> ENSG00000197635.9 Ok
>>> ENSG00000197696.9 Ok
>>> ENSG00000197959.13 Ok
>>> ENSG00000198223.16 Ok
>>> ENSG00000198356.11 Ok
>>> ENSG00000198502.5 Ok
>>> ENSG00000198734.10 Ok
>>> ENSG00000198736.11 Ok
>>> ENSG00000198743.6 Ok
>>> ENSG00000198848.12 Ok
>>> ENSG00000198879.11 Ok
>>> ENSG00000203697.11 Ok
>>> ENSG00000203760.8 Ok
>>> ENSG00000204228.3 Ok
>>> ENSG00000204257.14 Ok
>>> ENSG00000204287.13 Ok
>>> ENSG00000204305.13 Ok
>>> ENSG00000204381.11 Ok
>>> ENSG00000204396.10 Ok
>>> ENSG00000204514.9 Ok
>>> ENSG00000204623.9 Ok
>>> ENSG00000204642.13 Ok
>>> ENSG00000204681.10 Ok
>>> ENSG00000204839.8 Ok
>>> ENSG00000204977.9 Ok
>>> ENSG00000205542.10 Ok
>>> ENSG00000205707.10 Ok
>>> ENSG00000205790.1 Ok
>>> ENSG00000206075.13 Ok
>>> ENSG00000211445.11 Ok
>>> ENSG00000211460.11 Ok
>>> ENSG00000211598.2 Ok
>>> ENSG00000211637.2 Ok
>>> ENSG00000211638.2 Ok
>>> ENSG00000211640.4 Ok
>>> ENSG00000211648.2 Ok
>>> ENSG00000211649.3 Ok
>>> ENSG00000211651.3 Ok
>>> ENSG00000211653.2 Ok
>>> ENSG00000211659.2 Ok
>>> ENSG00000211660.3 Ok
>>> ENSG00000211662.2 Ok
>>> ENSG00000211663.2 Ok

In [82]:
gdc.root_gtex = create_dir(gdc.ROOT_DATA0, 'GTEx')

In [83]:
fname = "gtex_TPM_%s.tsv"%(psi_id)
pdwritecsv(df_gtex, fname, gdc.root_gtex)

print(len(df_gtex))
df_gtex.head()

991

,data,tissueSiteDetailId,ontologyId,datasetId,gencodeId,geneSymbol,unit,subsetGroup
0,"[4.23, 0.8048, 1.058, 7.783, 3.34, 1.121, 0.37...",Lung,UBERON:0008952,gtex_v8,ENSG00000001626.14,CFTR,TPM,None
1,"[14.6, 9.227, 21.5, 20.61, 5.981, 34.44, 16.79...",Lung,UBERON:0008952,gtex_v8,ENSG00000003989.17,SLC7A2,TPM,None
2,"[9.614, 5.767, 6.255, 4.502, 4.926, 14.01, 10....",Lung,UBERON:0008952,gtex_v8,ENSG00000004468.12,CD38,TPM,None
3,"[26.78, 44.86, 36.63, 42.64, 30.5, 40.02, 34.4...",Lung,UBERON:0008952,gtex_v8,ENSG00000005020.12,SKAP2,TPM,None
4,"[15.37, 10.43, 8.518, 10.34, 9.851, 17.75, 16....",Lung,UBERON:0008952,gtex_v8,ENSG00000005059.15,MCUB,TPM,None

### GTEx download

https://www.gtexportal.org/home/downloads/adult-gtex/overview

In [84]:
def download_file(url, filename_out):
    with requests.get(url, stream=True) as r:
        r.raise_for_status()

        try:
            with open(filename_out, "wb") as f:
                for chunk in r.iter_content(chunk_size=8192):
                    f.write(chunk)
        except Exception as e:
            print(f"Error: as writingfile {filename_out}: {e}")

In [101]:
url_counts = (
    "https://storage.googleapis.com/adult-gtex/bulk-gex/v11/rna-seq/"
    "GTEx_Analysis_2025-08-22_v11_RNASeQCv2.4.3_gene_reads.gct.gz"
)

url_tpm = (
    "https://storage.googleapis.com/adult-gtex/bulk-gex/v11/rna-seq/"
    "GTEx_Analysis_2025-08-22_v11_RNASeQCv2.4.3_gene_tpm.gct.gz"
)

url_meta = (
    "https://storage.googleapis.com/adult-gtex/metadata/"
    "GTEx_Analysis_v11_Annotations_SampleAttributesDS.txt"
)
fname_counts = "GTEx_Analysis_2025-08-22_v11_RNASeQCv2.4.3_gene_reads.gct.gz"
fname_meta   = "GTEx_Analysis_v11_Annotations_SampleAttributesDS.tsv"

filename_counts = gdc.root_gtex / fname_counts
filename_meta   = gdc.root_gtex / fname_meta

# --> download manually at https://www.gtexportal.org/home/downloads/adult-gtex/bulk_tissue_expression
#                      and https://www.gtexportal.org/home/downloads/adult-gtex/metadata

# download_file(url_counts, filename_counts)
# download_file(url_meta, filename_meta)

### Reading GTEx count super-file

In [94]:
# load matrix'1
dfcounts = pdreadcsv(fname_counts, gdc.root_gtex, skiprows=2)
print(len(dfcounts))
dfcounts.head(3)

74628

,Name,Description,GTEX-1117F-0005-SM-HL9SH,GTEX-1117F-0011-R10b-SM-GI4VE,GTEX-1117F-0011-R11b-SM-GIN8R,GTEX-1117F-0011-R2b-SM-GI4VL,GTEX-1117F-0011-R3a-SM-GJ3PJ,GTEX-1117F-0011-R4b-SM-GI4VM,GTEX-1117F-0011-R5a-SM-GI4VW,GTEX-1117F-0011-R6a-SM-GI4VX,...,GTEX-ZZPU-1326-SM-5GZWS,GTEX-ZZPU-1426-SM-5GZZ6,GTEX-ZZPU-1826-SM-5E43L,GTEX-ZZPU-2126-SM-5EGIU,GTEX-ZZPU-2226-SM-5EGIV,GTEX-ZZPU-2326-SM-GOQYU,GTEX-ZZPU-2426-SM-5E44I,GTEX-ZZPU-2526-SM-GOQZ3,GTEX-ZZPU-2626-SM-5E45Y,GTEX-ZZPU-2726-SM-5NQ8O
0,ENSG00000290825.2,DDX11L16,0,0,1,0,0,3,0,1,...,1,0,0,0,0,0,0,1,0,0
1,ENSG00000223972.6,DDX11L1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
2,ENSG00000310526.1,WASH7P,90,137,452,69,95,174,269,261,...,397,231,215,266,152,474,139,896,88,213

In [103]:
# load metadata
dfmeta = pdreadcsv(fname_meta, gdc.root_gtex)
print(len(dfmeta))
dfmeta.head(3)

48231

,SAMPID,SMATSSCR,SMCENTER,SMPTHNTS,SMRIN,SMTS,SMTSD,SMUBRID,SMTSISCH,SMTSPAX,...,SMSHRTRT,SMSMRDHQ,SMSMRTHQ,SMPRERDHQ,SMPRERTHQ,SMSMGNDT,SMPREGNDT,SMRDLNMN,SMRDLNMD,SMRDLNSD
0,BMS-X4LF-0126-SM-4JBHL,NaN,B1,NaN,7.5,Thyroid,Thyroid,UBERON:0002046,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,BMS-X4LF-0226-SM-4JBJ3,NaN,B1,NaN,6.9,Blood Vessel,Artery - Pulmonary,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,BMS-X4LF-0326-SM-4JBIR,NaN,B1,NaN,7.4,Muscle,Muscle - Skeletal,UBERON:0011907,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [122]:
# select lung samples
lung_samples = dfmeta.loc[dfmeta["SMTSD"] == "Lung", "SAMPID"].to_list()
print(len(lung_samples))
lung_samples[:5]

1892

['GTEX-1117F-1026-SM-GW2CO',
 'GTEX-1117F-1026-SM-LLLJU',
 'GTEX-111CU-0326-SM-5GZXO',
 'GTEX-111CU-0326-SM-F1XB2',
 'GTEX-111FC-1126-SM-5GZWU']

In [117]:
dfcounts.columns

Index(['Name', 'Description', 'GTEX-1117F-0005-SM-HL9SH',
       'GTEX-1117F-0011-R10b-SM-GI4VE', 'GTEX-1117F-0011-R11b-SM-GIN8R',
       'GTEX-1117F-0011-R2b-SM-GI4VL', 'GTEX-1117F-0011-R3a-SM-GJ3PJ',
       'GTEX-1117F-0011-R4b-SM-GI4VM', 'GTEX-1117F-0011-R5a-SM-GI4VW',
       'GTEX-1117F-0011-R6a-SM-GI4VX',
       ...
       'GTEX-ZZPU-1326-SM-5GZWS', 'GTEX-ZZPU-1426-SM-5GZZ6',
       'GTEX-ZZPU-1826-SM-5E43L', 'GTEX-ZZPU-2126-SM-5EGIU',
       'GTEX-ZZPU-2226-SM-5EGIV', 'GTEX-ZZPU-2326-SM-GOQYU',
       'GTEX-ZZPU-2426-SM-5E44I', 'GTEX-ZZPU-2526-SM-GOQZ3',
       'GTEX-ZZPU-2626-SM-5E45Y', 'GTEX-ZZPU-2726-SM-5NQ8O'],
      dtype='object', length=19790)

In [118]:
cols = ["Name", "Description"] + list(lung_samples)

In [121]:
good_cols = [x for x in cols if x in dfcounts.columns]

In [ ]:
df2 = dfcounts.loc[:, good_cols].copy()

KeyError: "['GTEX-1117F-1026-SM-GW2CO', 'GTEX-1117F-1026-SM-LLLJU', 'GTEX-111CU-0326-SM-F1XB2', 'GTEX-111FC-1126-SM-LUBBH', 'GTEX-111VG-0726-SM-GADV8', 'GTEX-111YS-0626-SM-F1CL6', 'GTEX-1122O-0126-SM-F1BZV', 'GTEX-1128S-0726-SM-EUKOO', 'GTEX-113JC-1326-SM-GW1F2', 'GTEX-113JC-1326-SM-LUBBT', 'GTEX-117YW-0526-SM-EUJFZ', 'GTEX-117YX-1326-SM-F3JKO', 'GTEX-1192W-0626-SM-GW224', 'GTEX-1192X-1326-SM-GW191', 'GTEX-11DXZ-0726-SM-GW23R', 'GTEX-11DYG-0626-SM-GW1XU', 'GTEX-11DZ1-0426-SM-EUPBM', 'GTEX-11EI6-0826-SM-CYKV8', 'GTEX-11EMC-0126-SM-F1KDQ', 'GTEX-11EQ9-0226-SM-F1FCM', 'GTEX-11GSP-0726-SM-9VXZ4', 'GTEX-11GSP-0726-SM-9WPNU', 'GTEX-11GSP-0726-SM-GW2CL', 'GTEX-11I78-0126-SM-DECQN', 'GTEX-11I78-0126-SM-GW226', 'GTEX-11ILO-0726-SM-5HL5I', 'GTEX-11ILO-0726-SM-GM8M3', 'GTEX-11NSD-0326-SM-EV6WG', 'GTEX-11NUK-0826-SM-EUKLA', 'GTEX-11NUK-0826-SM-LVTBX', 'GTEX-11NV4-1126-SM-F5WG8', 'GTEX-11NV4-1126-SM-GW17Z', 'GTEX-11NV4-1126-SM-LUBC6', 'GTEX-11O72-1326-SM-GEGUH', 'GTEX-11OF3-1126-SM-F1KN5', 'GTEX-11P81-0226-SM-F3SYL', 'GTEX-11PRG-0926-SM-EVR7U', 'GTEX-11TT1-1626-SM-F16CM', 'GTEX-11TTK-0926-SM-GW19B', 'GTEX-11TUW-0526-SM-F3IPX', 'GTEX-11UD2-0726-SM-F51EQ', 'GTEX-11WQC-0626-SM-ATE5Y', 'GTEX-11WQC-0626-SM-CYKQZ', 'GTEX-11WQC-0626-SM-GAT85', 'GTEX-11WQK-1226-SM-CYKV5', 'GTEX-11WQK-1226-SM-GW2CV', 'GTEX-11XUK-0326-SM-GL4O7', 'GTEX-11XUK-0326-SM-GW19G', 'GTEX-11XUK-5001-SM-AN3X2', 'GTEX-11ZTS-1226-SM-F1FCP', 'GTEX-11ZTS-1226-SM-GW1A7', 'GTEX-11ZTS-1226-SM-LUBEL', 'GTEX-11ZTT-5002-SM-AN3YG', 'GTEX-11ZUS-0126-SM-CYKR8', 'GTEX-11ZUS-0126-SM-GW2BW', 'GTEX-11ZVC-0226-SM-EXKUF', 'GTEX-1211K-0826-SM-7LDFQ', 'GTEX-1211K-0826-SM-9VXYJ', 'GTEX-1211K-0826-SM-GLPS4', 'GTEX-1211K-5004-SM-AN3X3', 'GTEX-1212Z-1026-SM-EUPAX', 'GTEX-1212Z-1026-SM-GW1UX', 'GTEX-12584-1426-SM-F113L', 'GTEX-12584-1426-SM-GW1UR', 'GTEX-1269C-0926-SM-LVTCD', 'GTEX-1269W-1026-SM-GL4N2', 'GTEX-12BJ1-1026-SM-F34O4', 'GTEX-12C56-0126-SM-GL4O6', 'GTEX-12WS9-1026-SM-GI4WI', 'GTEX-12WSA-1026-SM-CYKQ3', 'GTEX-12WSA-1026-SM-GW18E', 'GTEX-12WSD-0826-SM-9VXZ8', 'GTEX-12WSD-0826-SM-EV6X2', 'GTEX-12WSD-0826-SM-GW21I', 'GTEX-12WSE-0826-SM-EZKRP', 'GTEX-12WSE-0826-SM-GW22V', 'GTEX-12WSG-0326-SM-5FQU3', 'GTEX-12WSG-5004-SM-EX48N', 'GTEX-12WSG-5005-SM-AN3XB', 'GTEX-12WSH-0126-SM-GAMY3', 'GTEX-12WSI-0826-SM-F1HY6', 'GTEX-12WSJ-0226-SM-EV6U2', 'GTEX-12WSK-0826-SM-EVR6O', 'GTEX-12WSL-1026-SM-5CVNJ', 'GTEX-12WSL-1026-SM-F419V', 'GTEX-12WSN-0626-SM-5BC61', 'GTEX-12WSN-0626-SM-GJMPT', 'GTEX-12WSN-5004-SM-AN3XF', 'GTEX-12WSN-5004-SM-EX41Q', 'GTEX-12ZZW-0926-SM-CYKRH', 'GTEX-12ZZW-0926-SM-DECRK', 'GTEX-12ZZX-0926-SM-GW18L', 'GTEX-12ZZY-0926-SM-ATE5I', 'GTEX-12ZZY-0926-SM-F4GMW', 'GTEX-13111-0426-SM-5DUXR', 'GTEX-13111-0426-SM-GW1YH', 'GTEX-13111-5001-SM-AN3XJ', 'GTEX-13112-0826-SM-GW1ST', 'GTEX-13112-0826-SM-LVTBZ', 'GTEX-13113-0426-SM-5GCOD', 'GTEX-13113-0426-SM-GHHMT', 'GTEX-13113-5004-SM-EVYT6', 'GTEX-1313W-0926-SM-GEGTI', 'GTEX-131XE-0726-SM-F16CK', 'GTEX-131XF-1026-SM-EVLQK', 'GTEX-131XF-5010-SM-AN3XQ', 'GTEX-131XH-0426-SM-F1CLX', 'GTEX-131XH-0426-SM-LUBEM', 'GTEX-131XW-1126-SM-F16BI', 'GTEX-131YS-0926-SM-F5WPQ', 'GTEX-132NY-1226-SM-F1RQJ', 'GTEX-132QS-0726-SM-EB7IH', 'GTEX-1339X-0626-SM-EAQAW', 'GTEX-1339X-5003-SM-AN3Y7', 'GTEX-1399S-1726-SM-F413Z', 'GTEX-1399T-2326-SM-LUBF3', 'GTEX-1399U-0826-SM-F4BG9', 'GTEX-139TT-0726-SM-F4151', 'GTEX-139TT-0726-SM-GW1XV', 'GTEX-139TT-0726-SM-LUBEK', 'GTEX-139UW-0226-SM-F1KD4', 'GTEX-139YR-0926-SM-EAQ9E', 'GTEX-139YR-0926-SM-GW1FL', 'GTEX-13CF2-0726-SM-GW1FT', 'GTEX-13CF3-0426-SM-F3A1P', 'GTEX-13CZU-5001-SM-AN3YV', 'GTEX-13D11-0326-SM-9VXYN', 'GTEX-13FH7-1726-SM-EAYYL', 'GTEX-13FHO-1026-SM-ATE65', 'GTEX-13FHO-1026-SM-CYKRK', 'GTEX-13FHO-1026-SM-F34O8', 'GTEX-13FHP-0726-SM-ATE5L', 'GTEX-13FHP-0726-SM-CYKPV', 'GTEX-13FHP-0726-SM-F5WPC', 'GTEX-13FLW-0526-SM-LUBEJ', 'GTEX-13FTX-0326-SM-EV6TF', 'GTEX-13FTY-0126-SM-EVYMV', 'GTEX-13FTZ-0526-SM-GEGUB', 'GTEX-13FXS-0826-SM-GW2AX', 'GTEX-13FXS-0826-SM-LVTBY', 'GTEX-13G51-0426-SM-CYKUU', 'GTEX-13G51-0426-SM-LVTBT', 'GTEX-13IVO-1026-SM-GW1EL', 'GTEX-13JUV-0526-SM-ATE32', 'GTEX-13JUV-0526-SM-CYKUW', 'GTEX-13JUV-0526-SM-LUBEE', 'GTEX-13JVG-1426-SM-F4JCK', 'GTEX-13JVG-1426-SM-MN9W1', 'GTEX-13N11-0326-SM-EVR64', 'GTEX-13N11-5028-SM-AN3Z7', 'GTEX-13N11-5030-SM-H5JDW-CST', 'GTEX-13N11-5030-SM-H5JDW-EZ', 'GTEX-13N11-5030-SM-H5JDW-NST', 'GTEX-13N11-5030-SM-H5JDW-TST', 'GTEX-13N11-5030-SM-HL11S', 'GTEX-13N1W-0726-SM-ATE66', 'GTEX-13N1W-0726-SM-F16CN', 'GTEX-13N2G-0826-SM-ATE5H', 'GTEX-13N2G-0826-SM-CYKVY', 'GTEX-13N2G-0826-SM-EUKQU', 'GTEX-13NYB-0626-SM-9VXYV', 'GTEX-13NYB-0626-SM-F51GC', 'GTEX-13NYS-1626-SM-ATE6E', 'GTEX-13NYS-1626-SM-CYKVW', 'GTEX-13NYS-1626-SM-GW1VT', 'GTEX-13NZ8-0326-SM-F413Y', 'GTEX-13NZ9-0926-SM-F27C1', 'GTEX-13NZA-1426-SM-ATE4G', 'GTEX-13NZA-1426-SM-GJBQS', 'GTEX-13NZA-1426-SM-GW1VS', 'GTEX-13NZB-5004-SM-AN3ZB', 'GTEX-13O21-3026-SM-F1RQ3', 'GTEX-13O3O-0726-SM-CYKVH', 'GTEX-13O3P-1026-SM-EV6W3', 'GTEX-13O3P-1026-SM-GW1UY', 'GTEX-13O3Q-0526-SM-ATE3X', 'GTEX-13O3Q-0526-SM-F1RR9', 'GTEX-13O3Q-0526-SM-LVTBW', 'GTEX-13O61-0726-SM-EVR6J', 'GTEX-13O61-5004-SM-AN3ZO', 'GTEX-13OVH-1026-SM-ATE6I', 'GTEX-13OVH-1026-SM-CYKS2', 'GTEX-13OVH-1026-SM-F27CB', 'GTEX-13OVJ-0726-SM-EV6T1', 'GTEX-13OVK-0126-SM-GW1XG', 'GTEX-13OVL-0626-SM-F16AH', 'GTEX-13OW5-0726-SM-F34OC', 'GTEX-13OW5-0726-SM-GW1V7', 'GTEX-13OW5-0726-SM-LVTCR', 'GTEX-13OW6-0826-SM-F4JBB', 'GTEX-13OW7-0926-SM-CYKRR', 'GTEX-13OW7-0926-SM-GEGR2', 'GTEX-13OW8-1726-SM-9VXYO', 'GTEX-13OW8-1726-SM-GW1U6', 'GTEX-13PL6-2426-SM-GW1UQ', 'GTEX-13QBU-0726-SM-EVLQO', 'GTEX-13QBU-5004-SM-AN41B', 'GTEX-13QBU-5004-SM-HTQ8C', 'GTEX-13QIC-0326-SM-GW1TX', 'GTEX-13QJ3-1026-SM-F16AU', 'GTEX-13QJC-0526-SM-EXKU3', 'GTEX-13QJC-0526-SM-LUBE1', 'GTEX-13RTJ-1126-SM-EXCPO', 'GTEX-13RTJ-1126-SM-GW18K', 'GTEX-13S7M-2126-SM-EVYSD', 'GTEX-13S86-0626-SM-F27CC', 'GTEX-13SLW-1226-SM-CYKW6', 'GTEX-13SLW-1226-SM-F4GP1', 'GTEX-13U4I-1426-SM-F27BG', 'GTEX-13VXT-1426-SM-EVLJH', 'GTEX-13VXU-2726-SM-CYKUK', 'GTEX-13VXU-2726-SM-LUBDZ', 'GTEX-13W3W-0326-SM-731DS', 'GTEX-13W3W-0326-SM-EWR5R', 'GTEX-13W46-1426-SM-GW1AA', 'GTEX-13X6K-1626-SM-7EWCX', 'GTEX-13X6K-1626-SM-EZHE8', 'GTEX-13YAN-1026-SM-F3J9O', 'GTEX-1445S-1426-SM-LUBF4', 'GTEX-144GM-0126-SM-EAW4G', 'GTEX-144GM-5001-SM-AN418', 'GTEX-144GN-0426-SM-EVLJP', 'GTEX-145LS-1226-SM-EWYJ3', 'GTEX-145LT-0326-SM-EVR65', 'GTEX-145LT-5001-SM-AN41S', 'GTEX-145LU-0526-SM-F414J', 'GTEX-145ME-0226-SM-EXI67', 'GTEX-145ME-5001-SM-7IGOL', 'GTEX-145ME-5001-SM-AN41C', 'GTEX-145ME-5001-SM-GLDVC', 'GTEX-145ME-5003-SM-GLFX3', 'GTEX-145MF-0726-SM-EXHWU', 'GTEX-145MG-1426-SM-MN9XD', 'GTEX-145MH-0626-SM-CYKUL', 'GTEX-145MH-0626-SM-EBBH7', 'GTEX-145MH-0626-SM-GW1ZB', 'GTEX-145MN-0926-SM-EVLJZ', 'GTEX-145MN-5004-SM-AN41N', 'GTEX-145MN-5004-SM-HTQ8A', 'GTEX-145MO-1326-SM-F3JBN', 'GTEX-146FH-1226-SM-EUKQ2', 'GTEX-146FH-1226-SM-GW1RN', 'GTEX-14753-0826-SM-GW1E7', 'GTEX-1477Z-0626-SM-CYKRO', 'GTEX-1477Z-0626-SM-F51GD', 'GTEX-1477Z-0626-SM-GW1RM', 'GTEX-147F3-0726-SM-EUPAR', 'GTEX-147F3-5007-SM-AN41R', 'GTEX-147F4-0926-SM-CYKOU', 'GTEX-147F4-0926-SM-F3JAQ', 'GTEX-147GR-1226-SM-CYKOA', 'GTEX-147GR-1226-SM-EWR6J', 'GTEX-147JS-1226-SM-EXCRN', 'GTEX-148VI-0226-SM-F1RNG', 'GTEX-148VI-5001-SM-AN41Q', 'GTEX-148VJ-0826-SM-CYKPD', 'GTEX-148VJ-0826-SM-F1X95', 'GTEX-1497J-0326-SM-EWDYJ', 'GTEX-1497J-5001-SM-AN41V', 'GTEX-14A5H-1226-SM-GM8KF', 'GTEX-14A5H-1226-SM-MN9W2', 'GTEX-14A5I-0926-SM-GW2DC', 'GTEX-14A6H-0526-SM-F3IQ5', 'GTEX-14A6H-0526-SM-GW1DA', 'GTEX-14A6H-5007-SM-AN422', 'GTEX-14ABY-1126-SM-CYKOT', 'GTEX-14ABY-1126-SM-F1X94', 'GTEX-14AS3-0926-SM-EXON3', 'GTEX-14AS3-0926-SM-GW1X7', 'GTEX-14AS3-5007-SM-AN41Z', 'GTEX-14BIL-1226-SM-79OME', 'GTEX-14BIL-1226-SM-EZHES', 'GTEX-14BIM-0726-SM-GW18T', 'GTEX-14BIN-0226-SM-GW188', 'GTEX-14BIN-0226-SM-MMU24', 'GTEX-14BMU-0526-SM-5CA2F', 'GTEX-14BMU-0526-SM-5CA2F_rep', 'GTEX-14BMU-0526-SM-5CA2F_rep2', 'GTEX-14BMU-0526-SM-73KW4', 'GTEX-14BMU-0526-SM-EWR3A', 'GTEX-14BMU-5001-SM-AN427', 'GTEX-14BMV-0826-SM-73KXU', 'GTEX-14BMV-0826-SM-CYKTX-ELUATE', 'GTEX-14BMV-0826-SM-CYKTX-INPUT', 'GTEX-14BMV-0826-SM-CYKTX-SUP', 'GTEX-14BMV-0826-SM-F2UMW', 'GTEX-14BMV-0826-SM-GW1QQ', 'GTEX-14C38-5010-SM-AN428', 'GTEX-14C39-0326-SM-CYKOQ', 'GTEX-14C39-0326-SM-EXOPB', 'GTEX-14C5O-1126-SM-CYKO3', 'GTEX-14DAQ-0926-SM-793AZ', 'GTEX-14DAQ-0926-SM-CYKRD', 'GTEX-14DAQ-0926-SM-F3IRJ', 'GTEX-14DAR-0226-SM-EXKYY', 'GTEX-14DAR-0226-SM-GW1WU', 'GTEX-14E1K-0226-SM-F5B9Q', 'GTEX-14E6C-1426-SM-F4VS7', 'GTEX-14E6C-1426-SM-GW1CP', 'GTEX-14E6D-1026-SM-CYKRZ', 'GTEX-14E6D-1026-SM-F5WG3', 'GTEX-14E6E-0426-SM-5P9I7', 'GTEX-14E6E-0426-SM-EX41J', 'GTEX-14E6E-5001-SM-AN42D', 'GTEX-14E7W-1326-SM-EXOPA', 'GTEX-14E7W-1326-SM-GW217', 'GTEX-14ICK-0726-SM-GM8LG', 'GTEX-14ICK-5007-SM-AN42K', 'GTEX-14JFF-1126-SM-GW1CX', 'GTEX-14JG1-0926-SM-F3IR6', 'GTEX-14JG1-0926-SM-GW1CZ', 'GTEX-14JG6-0326-SM-EXOL9', 'GTEX-14JG6-0326-SM-GW1ED', 'GTEX-14JG6-5001-SM-AN42H', 'GTEX-14JIY-1326-SM-CYKT3', 'GTEX-14JIY-1326-SM-EWR6M', 'GTEX-14LLW-0726-SM-F4I6X', 'GTEX-14LZ3-0726-SM-F3IR7', 'GTEX-14LZ3-0726-SM-GW18U', 'GTEX-14PHY-0526-SM-EX3ZC', 'GTEX-14PJ4-0626-SM-EXOL8', 'GTEX-14PJ4-0626-SM-GW1QR', 'GTEX-14PJ5-0226-SM-EXCS5', 'GTEX-14PJ5-5001-SM-AN42L', 'GTEX-14PJ6-0426-SM-GW1C8', 'GTEX-14PJ6-5001-SM-AN42U', 'GTEX-14PJM-0926-SM-CYKSY', 'GTEX-14PJM-0926-SM-EZHER', 'GTEX-14PJM-0926-SM-GW2CR', 'GTEX-14PJO-0926-SM-EXOPC', 'GTEX-14PJO-0926-SM-GW1RZ', 'GTEX-14PK6-0326-SM-6AJ9S', 'GTEX-14PK6-0326-SM-EVYSY', 'GTEX-14PK6-0326-SM-GW1C7', 'GTEX-14PK6-5001-SM-AN431', 'GTEX-14PKU-0726-SM-GLPRS', 'GTEX-14PN3-0926-SM-GM8LD', 'GTEX-14PN3-0926-SM-GW1DX', 'GTEX-14PQA-1126-SM-CYKTQ', 'GTEX-14PQA-1126-SM-F4165', 'GTEX-14PQA-1126-SM-LUBE2', 'GTEX-14XAO-0526-SM-6AJB7', 'GTEX-14XAO-0526-SM-EXOOF', 'GTEX-15CHC-0226-SM-EWR4W', 'GTEX-15CHC-5001-SM-AN436', 'GTEX-15CHQ-1026-SM-GM8LA', 'GTEX-15CHR-0726-SM-7EPHG', 'GTEX-15CHR-0726-SM-F4VRY', 'GTEX-15CHR-0726-SM-GW1RR', 'GTEX-15CHR-5005-SM-H5JDT-CST', 'GTEX-15CHR-5005-SM-H5JDT-EZ', 'GTEX-15CHR-5005-SM-H5JDT-NST', 'GTEX-15CHR-5005-SM-H5JDT-TST', 'GTEX-15D1Q-0526-SM-CYKT2', 'GTEX-15D1Q-0526-SM-EX425', 'GTEX-15D1Q-0526-SM-GW2DA', 'GTEX-15D79-1026-SM-GW1CY', 'GTEX-15DCD-1426-SM-CYKTW', 'GTEX-15DCZ-0826-SM-6AJBB', 'GTEX-15DCZ-0826-SM-EVYT1', 'GTEX-15DDE-0826-SM-GW21H', 'GTEX-15EO6-0326-SM-GW1T5', 'GTEX-15EOM-5010-SM-AN43D', 'GTEX-15EOM-5010-SM-GM8KW', 'GTEX-15EOM-5011-SM-GJ3RX', 'GTEX-15EOM-5011-SM-GM8MM', 'GTEX-15ER7-0926-SM-CYKTS-ELUATE', 'GTEX-15ER7-0926-SM-CYKTS-INPUT', 'GTEX-15ER7-0926-SM-CYKTS-SUP', 'GTEX-15ER7-0926-SM-F51OS', 'GTEX-15ETS-5013-SM-AN43K', 'GTEX-15EU6-1226-SM-EXI6U', 'GTEX-15EU6-1226-SM-GW17S', 'GTEX-15F5U-5003-SM-AN43O', 'GTEX-15FZZ-0326-SM-EXOOA', 'GTEX-15FZZ-5001-SM-AN44G', 'GTEX-15G19-0726-SM-CYKSQ', 'GTEX-15G19-0726-SM-GM8MP', 'GTEX-15G1A-0426-SM-EZHEX', 'GTEX-15G1A-0426-SM-GW1BS', 'GTEX-15RIE-0326-SM-GW1GV', 'GTEX-15RIE-5002-SM-HL11U', 'GTEX-15RIF-0426-SM-GLFYH', 'GTEX-15RJ7-0626-SM-EWYJV', 'GTEX-15RJ7-5004-SM-AN441', 'GTEX-15RJE-1026-SM-EWDZ9', 'GTEX-15RJE-1026-SM-GW2CM', 'GTEX-15SB6-0426-SM-EWYDU', 'GTEX-15SB6-5001-SM-AN44H', 'GTEX-15SDE-0226-SM-GM8LJ', 'GTEX-15SDE-0226-SM-GW1S7', 'GTEX-15SDE-5001-SM-AN43Z', 'GTEX-15SHV-0326-SM-EWR2O', 'GTEX-15SHV-0326-SM-GW1QS', 'GTEX-15SHV-5001-SM-AN446', 'GTEX-15SHW-0926-SM-EXOK4', 'GTEX-15SHW-0926-SM-GW1RW', 'GTEX-15SKB-0826-SM-F3SXV', 'GTEX-15SKB-0826-SM-GW1S9', 'GTEX-15SZO-0926-SM-GW2DF', 'GTEX-15UF6-1226-SM-GW1WV', 'GTEX-15UKP-1926-SM-EXI5E', 'GTEX-15UKP-1926-SM-GW22M', 'GTEX-15UKP-5010-SM-AN44O', 'GTEX-169BO-5001-SM-AN44A', 'GTEX-16A39-5001-SM-AN44B', 'GTEX-16AAH-0426-SM-EVYTK', 'GTEX-16AAH-0426-SM-GW1DR', 'GTEX-16AAH-0426-SM-MN9X3', 'GTEX-16GPK-1826-SM-7MGW5', 'GTEX-16GPK-1826-SM-GGXES', 'GTEX-16GPK-1826-SM-GJMR2', 'GTEX-16MTA-1226-SM-F2ULS', 'GTEX-16NFA-0826-SM-GM8LU', 'GTEX-16NFA-5003-SM-AN44K', 'GTEX-16NGA-0226-SM-EWF8B', 'GTEX-16NPV-0726-SM-GW2DE', 'GTEX-16XZZ-0926-SM-CYKP1', 'GTEX-16XZZ-0926-SM-EXKW5', 'GTEX-16YQH-1626-SM-GM8KL', 'GTEX-16YQH-1626-SM-GW17E', 'GTEX-16Z82-1026-SM-CYKSW', 'GTEX-16Z82-1026-SM-F1CLO', 'GTEX-178AV-0326-SM-EXKY4', 'GTEX-17EVP-0726-SM-CYKU5', 'GTEX-17EVP-0726-SM-EXCTT', 'GTEX-17EVQ-1526-SM-CYKTA', 'GTEX-17EVQ-1526-SM-EX426', 'GTEX-17EVQ-1526-SM-GW1R3', 'GTEX-17F96-0626-SM-F1X8R', 'GTEX-17F98-0226-SM-EXOLQ', 'GTEX-17F9Y-1026-SM-EWF81', 'GTEX-17GQL-0726-SM-F4JBF', 'GTEX-17GQL-5007-SM-AN454', 'GTEX-17HG3-0326-SM-F1KE8', 'GTEX-17HG3-0326-SM-GW231', 'GTEX-17HGU-0926-SM-F27C4', 'GTEX-17HHE-0626-SM-F1RP9', 'GTEX-17HII-0926-SM-EX47X', 'GTEX-17JCI-1526-SM-F1COF', 'GTEX-17KNJ-0926-SM-EZHDR', 'GTEX-17KNJ-5007-SM-AN44U', 'GTEX-17MF6-0826-SM-F3JAO', 'GTEX-183FY-0726-SM-EWE15', 'GTEX-18464-1326-SM-GINAA', 'GTEX-18465-0626-SM-EZKRF', 'GTEX-18465-0626-SM-GW1C9', 'GTEX-18A66-0926-SM-EXI7D', 'GTEX-18A66-0926-SM-GW29X', 'GTEX-18A67-1126-SM-EWR3N', 'GTEX-18A6Q-0826-SM-EXHZ1', 'GTEX-18A7A-1026-SM-F41A5', 'GTEX-18D9A-0226-SM-F1XBM', 'GTEX-18D9B-1026-SM-72D6A', 'GTEX-18D9B-1026-SM-7KFS8', 'GTEX-18D9B-1026-SM-EXL15', 'GTEX-18D9B-1026-SM-GW1QG', 'GTEX-18D9U-0526-SM-EZHEE', 'GTEX-18D9U-0526-SM-GW1XD', 'GTEX-18D9U-5004-SM-AN44W', 'GTEX-18QFQ-0926-SM-EWYFM', 'GTEX-19HZE-0526-SM-GMXBE', 'GTEX-19HZE-0526-SM-GW1RP', 'GTEX-19HZE-0526-SM-MN9X1', 'GTEX-1A32A-0726-SM-F4BEK', 'GTEX-1A3MV-0526-SM-EWYJD', 'GTEX-1A3MV-0526-SM-GW2DB', 'GTEX-1A3MX-0726-SM-GW1DP', 'GTEX-1A8FM-0826-SM-F1KEF', 'GTEX-1A8FM-0826-SM-LUBDN', 'GTEX-1A8G6-0726-SM-F41CG', 'GTEX-1A8G6-0726-SM-MN9VY', 'GTEX-1AX8Y-0526-SM-72D5K', 'GTEX-1AX8Y-0526-SM-GIFZT', 'GTEX-1AX8Z-1526-SM-73KW1', 'GTEX-1AX8Z-1526-SM-F1HYS', 'GTEX-1AX8Z-5010-SM-GL4MB', 'GTEX-1AX9I-0826-SM-EXCQM', 'GTEX-1AX9I-0826-SM-GW1R7', 'GTEX-1AX9J-1626-SM-F3A1H', 'GTEX-1AX9K-0826-SM-731F9', 'GTEX-1AX9K-0826-SM-EXKVG', 'GTEX-1AYCT-0726-SM-EXKZM', 'GTEX-1AYCT-5004-SM-AN45J', 'GTEX-1AYD5-1226-SM-EXCTI', 'GTEX-1AYD5-1226-SM-GW1EA', 'GTEX-1AYD5-5010-SM-AN45I', 'GTEX-1B8KZ-0526-SM-EX41M', 'GTEX-1B8L1-0626-SM-GGQT5', 'GTEX-1B8SF-0826-SM-F41CV', 'GTEX-1B8SG-1026-SM-GM8LR', 'GTEX-1B932-0726-SM-EWR5S', 'GTEX-1B932-5007-SM-AN45T', 'GTEX-1B97I-0226-SM-EXCQN', 'GTEX-1B98T-1226-SM-GLFVD', 'GTEX-1B98T-1226-SM-GW1S5', 'GTEX-1B98T-1226-SM-HLJSK', 'GTEX-1B996-0726-SM-F16C1', 'GTEX-1BAJH-1326-SM-GGXSB', 'GTEX-1BAJH-1326-SM-GW1FE', 'GTEX-1C4CL-0826-SM-EXCTJ', 'GTEX-1C4CL-0826-SM-GW1D4', 'GTEX-1C64N-1126-SM-GW1CB', 'GTEX-1C64O-1226-SM-EX47Z', 'GTEX-1C64O-1226-SM-GW1TA', 'GTEX-1C6VR-0626-SM-G5R2S', 'GTEX-1C6VS-1226-SM-F51N3', 'GTEX-1C6WA-0726-SM-F1KOE', 'GTEX-1CAMQ-1026-SM-GW1QU', 'GTEX-1CAMQ-1026-SM-LUBDO', 'GTEX-1CAV2-0626-SM-GM8KS', 'GTEX-1CAV2-0626-SM-GW29Z', 'GTEX-1CAV2-0626-SM-LVTCC', 'GTEX-1CB4F-0926-SM-F39Z2', 'GTEX-1CB4I-2126-SM-EWR55', 'GTEX-1CB4J-1726-SM-F2TYF', 'GTEX-1E1VI-0926-SM-GM8MD', 'GTEX-1E1VI-0926-SM-GW1DZ', 'GTEX-1E2YA-0926-SM-GJ4YN', 'GTEX-1EMGI-1426-SM-MN9WB', 'GTEX-1EN7A-0826-SM-EWF8N', 'GTEX-1EN7A-0826-SM-GW1R8', 'GTEX-1F48J-0826-SM-GIFZD', 'GTEX-1F52S-0726-SM-GW1QO', 'GTEX-1F5PK-0526-SM-GKGP6', 'GTEX-1F5PK-0526-SM-GW189', 'GTEX-1F5PK-5004-SM-AN46P', 'GTEX-1F6I4-1026-SM-GHHO4', 'GTEX-1F6I4-1026-SM-GW1WX', 'GTEX-1F6IF-1826-SM-GW1EE', 'GTEX-1F6RS-0826-SM-GM8ME', 'GTEX-1F75B-1026-SM-GJMAM', 'GTEX-1F75B-1026-SM-GW2D8', 'GTEX-1F75W-0626-SM-GW2D9', 'GTEX-1F75W-0626-SM-LUBDQ', 'GTEX-1F7RK-0826-SM-GI2MN', 'GTEX-1F88E-0226-SM-GW1TM', 'GTEX-1F88F-0926-SM-GGQRJ', 'GTEX-1FIGZ-0326-SM-GJCM7', 'GTEX-1GF9V-1026-SM-GGXT7', 'GTEX-1GF9X-0326-SM-GHSP8', 'GTEX-1GL5R-0526-SM-GHSDF', 'GTEX-1GL5R-0526-SM-GW1DT', 'GTEX-1GMR2-0126-SM-GGQQM', 'GTEX-1GMR2-0126-SM-GW1WR', 'GTEX-1GMR2-5001-SM-AN476', 'GTEX-1GMR3-0226-SM-GW1C2', 'GTEX-1GMR3-5001-SM-AN46H', 'GTEX-1GMR8-1426-SM-LUBDP', 'GTEX-1GMRU-1426-SM-GM8L5', 'GTEX-1GN1U-1026-SM-GKBDD', 'GTEX-1GN1W-1026-SM-GLFXX', 'GTEX-1GN1W-1026-SM-GW17F', 'GTEX-1GN2E-1526-SM-GI2NP', 'GTEX-1GPI6-0726-SM-GW2D7', 'GTEX-1GTWX-0626-SM-GHSDO', 'GTEX-1GTWX-0626-SM-GW1S8', 'GTEX-1GZ2Q-0726-SM-GHHNS', 'GTEX-1GZ2Q-0726-SM-MN9V8', 'GTEX-1GZ4H-0426-SM-GLFWB', 'GTEX-1GZ4I-0726-SM-GJCLT', 'GTEX-1GZHY-0826-SM-GM8KV', 'GTEX-1GZHY-0826-SM-GW1RD', 'GTEX-1H11D-0726-SM-GGXS7', 'GTEX-1H11D-0726-SM-GW1XA', 'GTEX-1H1DF-1226-SM-GW1D5', 'GTEX-1H1E6-0726-SM-GKBD3', 'GTEX-1H1ZS-0826-SM-GIES2', 'GTEX-1H23P-1026-SM-GM8KM', 'GTEX-1H23P-1026-SM-GW1WW', 'GTEX-1H2FU-1226-SM-GHSEF', 'GTEX-1H3O1-0326-SM-GM8L1', 'GTEX-1H3VE-1026-SM-GW2CS', 'GTEX-1H3VY-1426-SM-GH6UA', 'GTEX-1H3VY-1426-SM-GW2CN', 'GTEX-1H3VY-5010-SM-AN46N', 'GTEX-1H4P4-0126-SM-GLFXZ', 'GTEX-1HB9E-0726-SM-GKBAT', 'GTEX-1HB9E-0726-SM-GW1XB', 'GTEX-1HB9E-0726-SM-LUBF5', 'GTEX-1HBPM-0826-SM-GIRCX', 'GTEX-1HBPM-0826-SM-GJE8O', 'GTEX-1HBPN-1126-SM-GM83Z', 'GTEX-1HBPN-1126-SM-H65ZD', 'GTEX-1HCU7-0926-SM-GLFYZ', 'GTEX-1HCUA-0226-SM-GLDWN', 'GTEX-1HCUA-5001-SM-AN46Z', 'GTEX-1HCVE-0626-SM-GIERX', 'GTEX-1HCVE-0626-SM-GW1CF', 'GTEX-1HFI6-0926-SM-GM8L6', 'GTEX-1HR9M-0826-SM-GW18A', 'GTEX-1HSMO-0926-SM-GLFZ2', 'GTEX-1HSMP-1326-SM-A96TR', 'GTEX-1HSMP-1326-SM-GLFWN', 'GTEX-1HSMQ-0726-SM-B2LXY', 'GTEX-1HSMQ-0726-SM-GKBB1', 'GTEX-1HSMQ-5004-SM-AN47O', 'GTEX-1HSMQ-5005-SM-GKSJF-CST', 'GTEX-1HSMQ-5005-SM-GKSJF-EZ', 'GTEX-1HSMQ-5005-SM-GKSJF-NST', 'GTEX-1HSMQ-5005-SM-GKSJF-TST', 'GTEX-1HSMQ-5006-SM-HL123', 'GTEX-1HT8W-1426-SM-GJCPD', 'GTEX-1I19N-0526-SM-GM8LT', 'GTEX-1I1CD-0926-SM-GJZAZ', 'GTEX-1I1GP-0526-SM-GKBAI', 'GTEX-1I1GQ-1126-SM-GIREM', 'GTEX-1I1GU-0526-SM-GM8MB', 'GTEX-1I1GV-0926-SM-GGPUN', 'GTEX-1I4MK-0326-SM-GM8M9', 'GTEX-1I6K6-0926-SM-GW2CT', 'GTEX-1I6K7-1226-SM-AAEQX', 'GTEX-1I6K7-1226-SM-GJBPV', 'GTEX-1ICG6-5004-SM-AN47H', 'GTEX-1ICLY-5007-SM-AN47U', 'GTEX-1ICLZ-0926-SM-GM8M2', 'GTEX-1IDJD-0826-SM-A8N9H', 'GTEX-1IDJD-0826-SM-GIREU', 'GTEX-1IDJH-0726-SM-GGPTO', 'GTEX-1IDJI-0626-SM-GKGN3', 'GTEX-1IDJI-0626-SM-GW1WO', 'GTEX-1IDJI-5007-SM-AN47G', 'GTEX-1IDJU-0226-SM-GGXE5', 'GTEX-1IDJU-0226-SM-GW1T6', 'GTEX-1IDJU-5001-SM-AN482', 'GTEX-1IDJU-5002-SM-HL124', 'GTEX-1IGQW-0726-SM-GW1CE', 'GTEX-1IKJJ-0926-SM-GW1DJ', 'GTEX-1IKK5-1926-SM-GJZAS', 'GTEX-1IKK5-1926-SM-GW1QN', 'GTEX-1IKK5-1926-SM-MN9W6', 'GTEX-1IKOE-1226-SM-A8N98', 'GTEX-1IKOE-5010-SM-AN489', 'GTEX-1IL2U-0926-SM-GKGN9', 'GTEX-1IL2U-0926-SM-GW1DV', 'GTEX-1IOXB-1126-SM-GJZCB', 'GTEX-1IOXB-1126-SM-LVTCA', 'GTEX-1J1OQ-0926-SM-GW21Y', 'GTEX-1J1R8-0226-SM-GJMCG', 'GTEX-1J1R8-0226-SM-GW1C1', 'GTEX-1J8EW-1026-SM-GIERO', 'GTEX-1J8JJ-1126-SM-GKGMA', 'GTEX-1J8JJ-1126-SM-GW1Q2', 'GTEX-1J8Q3-0826-SM-A8N8W', 'GTEX-1J8Q3-0826-SM-GHSQB', 'GTEX-1J8Q3-0826-SM-GW1TO', 'GTEX-1J8QM-0526-SM-GJZBP', 'GTEX-1J8QM-5001-SM-AN49B', 'GTEX-1JJ6O-1026-SM-HL117', 'GTEX-1JJE9-0926-SM-G6KWV', 'GTEX-1JJEA-1126-SM-G6JFD', 'GTEX-1JK1U-1126-SM-G7UFU', 'GTEX-1JK1U-1126-SM-GW1VL', 'GTEX-1JK1U-5007-SM-AN487', 'GTEX-1JKYN-2126-SM-G63DR', 'GTEX-1JMI6-0726-SM-G6UEA', 'GTEX-1JMI6-0726-SM-H6Q7E', 'GTEX-1JMLX-0926-SM-G5T2D', 'GTEX-1JMLX-0926-SM-LLLJE', 'GTEX-1JMOU-0526-SM-G63F1', 'GTEX-1JMOU-0526-SM-GW2CI', 'GTEX-1JMOU-0526-SM-MN9W7', 'GTEX-1JMPZ-1126-SM-G66HL', 'GTEX-1JMQI-1126-SM-G7PMN', 'GTEX-1JMQJ-2126-SM-G5WO2', 'GTEX-1JMQJ-2126-SM-GW2D5', 'GTEX-1JMQK-0826-SM-HL119', 'GTEX-1JMQL-1126-SM-G7UFQ', 'GTEX-1JMQL-1126-SM-LVTC9', 'GTEX-1JN6P-0726-SM-G7PP3', 'GTEX-1JN76-0826-SM-G6EGO', 'GTEX-1JN76-0826-SM-GW1SB', 'GTEX-1K2DA-0426-SM-HL11B', 'GTEX-1K2DU-0526-SM-G7UDR', 'GTEX-1K2DU-5004-SM-AN48C', 'GTEX-1K9T9-0926-SM-G6JFE', 'GTEX-1KAFJ-0326-SM-G836H', 'GTEX-1KAFJ-0326-SM-MN9WU', 'GTEX-1KANB-1026-SM-G6OKW', 'GTEX-1KD4Q-0926-SM-G6DMI', 'GTEX-1KD5A-1126-SM-G71MF', 'GTEX-1KWVE-0426-SM-G89ZY', 'GTEX-1KXAM-0426-SM-CYKMP', 'GTEX-1KXAM-0426-SM-G6ON6', 'GTEX-1KXAM-0426-SM-GW2CW', 'GTEX-1L5NE-0726-SM-G7UFP', 'GTEX-1L5NE-0726-SM-GW17C', 'GTEX-1L5NE-5004-SM-AN48I', 'GTEX-1LB8K-0826-SM-G8A6M', 'GTEX-1LC46-0626-SM-CXZKW', 'GTEX-1LC46-0626-SM-G7UDM', 'GTEX-1LC46-5004-SM-AN494', 'GTEX-1LC47-1126-SM-G78HQ', 'GTEX-1LC47-1126-SM-GW2CJ', 'GTEX-1LC47-1126-SM-LLLJC', 'GTEX-1LG7Y-0826-SM-G6V25', 'GTEX-1LG7Y-0826-SM-GW2D2', 'GTEX-1LGRB-0226-SM-G6JFP', 'GTEX-1LGRB-0226-SM-MN9WQ', 'GTEX-1LH75-0226-SM-G7FX7', 'GTEX-1LH75-0226-SM-LLLJQ', 'GTEX-1LSNL-1126-SM-G76S2', 'GTEX-1LSNL-1126-SM-GW2D6', 'GTEX-1LSVX-0626-SM-G6KX7', 'GTEX-1LSVX-0626-SM-GW2CX', 'GTEX-1LVA9-1126-SM-GW2D1', 'GTEX-1LVAN-1126-SM-G5T2G', 'GTEX-1LVAN-1126-SM-MN9WV', 'GTEX-1LVAO-1226-SM-G7PN1', 'GTEX-1LVAO-1226-SM-GW2D4', 'GTEX-1M4P7-0826-SM-

In [ ]:
df2.rename(columns={"Name": "ensemblid", "Description": "symbol"}, inplace=True)

print(len(df2))
df2.head(3)