In [ ]:
from platform import python_version
print(python_version())

In [ ]:
!echo $CONDA_DEFAULT_ENV

## Pathways' Discover

In [1]:
import os, sys, pickle

import numpy as np
import pandas as pd
pd.set_option('display.width', 100)
pd.set_option('max_colwidth', 80)
import yaml

import seaborn as sns
sns.set_context("notebook", font_scale=1.4)

import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
%matplotlib inline

sys.path.insert(1, '../src/')

from Basic import *
from MTD_lib import *
from gemini_lib import *
# from enricher_lib import *
# from config_lib import *

import warnings
warnings.filterwarnings("ignore")

pd.set_option("display.precision", 3)
from IPython.display import display, HTML
# display(HTML("<style>.container { width:100% !important; }</style>"))
display(HTML("<style>:root { --jp-notebook-max-width: 100% !important; }</style>"))

# !pip3 install pyyaml
with open('params.yml', 'r') as file:
    dic_yml = yaml.safe_load(file)

In [2]:
root_chibe = dic_yml['root_chibe']
root_colab = dic_yml['root_colab']
root0 = dic_yml['root0']

from dotenv import load_dotenv
load_dotenv()

email = os.getenv('email')

try:
    i_project=dic_yml['i_project']
except:
    i_project=0

print(">>> i_project", i_project)

project_list = dic_yml['project_list']
n = len(project_list)
project = project_list[i_project]

s_project_list = dic_yml['s_project_list']
s_project = s_project_list[i_project]
assert n==len(project_list), f"Error project_list: there are {n} projects"

disease = dic_yml['disease']
gene_protein = dic_yml['gene_protein']
s_omics = dic_yml['s_omics']

has_age = dic_yml['has_age']
has_gender = dic_yml['has_gender']

exp_normalization = dic_yml['exp_normalization']
normalization = 'quantile_norm' if exp_normalization == True else 'not_normalized'

abs_lfc_cutoff_inf = dic_yml['abs_lfc_cutoff_inf']
s_pathw_enrichm_method = dic_yml['s_pathw_enrichm_method']
num_min_degs_for_ptw_enr = dic_yml['num_min_degs_for_ptw_enr']

tolerance_pPMI = dic_yml['tolerance_pPMI']
type_sat_ptw_index = dic_yml['type_sat_ptw_index']
saturation_lfc_param = dic_yml['saturation_lfc_param']

pval_pathway_cutoff = dic_yml['pval_pathway_cutoff']
fdr_pathway_cutoff = dic_yml['fdr_pathway_cutoff']
num_of_genes_cutoff = dic_yml['num_of_genes_cutoff']
enr_db_list = dic_yml['enr_db_list']

case_list = dic_yml['case_list']
dic_case_list = dic_yml['dic_case_list']

std_filename      = dic_yml['std_filename']
std_filename_list = dic_yml['std_filename_list']

min_lfc_modulation = dic_yml['min_lfc_modulation']
num_of_genes_list  = dic_yml['num_of_genes_list']
pPMI_normalized  = dic_yml['pPMI_normalized']

#--- max len for formatting purposes
s_len_case  = dic_yml['s_len_case']

n_sentences = dic_yml['n_sentences']
run_list = dic_yml['run_list']
chosen_model_list = dic_yml['chosen_model_list']
i_dfp_list = dic_yml['i_dfp_list']
chosen_model_sampling = dic_yml['chosen_model_sampling']

fdr_ptw_cutoff_list = np.arange(0.05, 0.80, 0.05)
lfc_list = np.round(np.arange(1.0, -0.01, -.025), 3)
fdr_list = np.arange(0.05, 0.76, .01)

cfg = Config(project, s_project, case_list, root0)
case = case_list[0]

n_genes_annot_ptw, n_degs, n_degs_in_ptw, n_degs_not_in_ptw, degs_in_all_ratio = -1,-1,-1,-1,-1
abs_lfc_cutoff, fdr_lfc_cutoff, n_degs, n_degs_up, n_degs_dw = cfg.get_best_lfc_cutoff(case, 'not_normalized')

print(f"project '{project}', s_project '{s_project}'")
print(f"G/P LFC cutoffs: lfc={abs_lfc_cutoff:.3f}; fdr={fdr_lfc_cutoff:.3f}")
print(f"Pathway cutoffs: pval={pval_pathway_cutoff:.3f}; fdr={fdr_pathway_cutoff:.3f}; num of genes={num_of_genes_cutoff}")

>>> i_project 0
project 'Medulloblastoma microarray study', s_project 'medulloblastoma'
G/P LFC cutoffs: lfc=1.000; fdr=0.050
Pathway cutoffs: pval=0.050; fdr=0.050; num of genes=3

In [3]:
mtd = MTD(disease=disease, gene_protein=gene_protein, s_omics=s_omics, project=project, s_project=s_project, root0=root0,
          case_list=case_list, dic_case_list=dic_case_list, has_age=has_age, has_gender=has_gender, exp_normalization=exp_normalization,
          std_filename=std_filename, std_filename_list=std_filename_list,
          geneset_num=0, num_min_degs_for_ptw_enr=num_min_degs_for_ptw_enr,
          tolerance_pPMI=tolerance_pPMI, s_pathw_enrichm_method=s_pathw_enrichm_method,
          root_colab=root_colab, root_chibe=root_chibe, 
          abs_lfc_cutoff_inf=abs_lfc_cutoff_inf, fdr_ptw_cutoff_list=fdr_ptw_cutoff_list,
          num_of_genes_list=num_of_genes_list, lfc_list=lfc_list, fdr_list=fdr_list, 
          min_lfc_modulation=min_lfc_modulation, type_sat_ptw_index=type_sat_ptw_index,
          saturation_lfc_param=saturation_lfc_param, enr_db_list=enr_db_list, pPMI_normalized=pPMI_normalized)

case = case_list[0]
print(">>>", case)

mtd.cfg.set_default_best_lfc_cutoff(mtd.normalization, abs_lfc_cutoff=1, fdr_lfc_cutoff=0.05)
ret, degs, degs_ensembl, dfdegs = mtd.open_case(case, prompt_verbose=True, verbose=False)
print("\nEcho Parameters:")
mtd.echo_parameters()

Start opening tables ....
Building synonym dictionary ...

$$$ Removed: ./figures/
>>> WNT
>>> case WNT
	DEGs 3448
		Up (#1441)
		Dw (#2007)

Up-regulated per biotype
                               biotype    n
0                                  LNC  321
1                                  TEC    1
2                                  UNK   25
3                            hasSymbol  128
4                               lncRNA   19
5                                ncRNA   47
6                 processed_pseudogene    2
7                       protein_coding  882
8                               scaRNA    2
9                               snoRNA    9
10      transcribed_unitary_pseudogene    1
11  transcribed_unprocessed_pseudogene    2
12              unprocessed_pseudogene    2

Down-regulated per biotype
                               biotype     n
0                                  LNC   223
1                                  UNK    23
2                            hasSymbol   217
3                               lncRNA    30
4                                ncRNA    18
5                 processed_pseudogene     2
6                       protein_coding  1486
7                               snoRNA     1
8       transcribed_unitary_pseudogene     1
9   transcribed_unprocessed_pseudogene     5
10              unprocessed_pseudogene     1

Echo Parameters:
For case 0 'WNT' ('WNT'), there are 3448/2446 DEGs/DEGs with ensembl_id
DEG's cutoffs: abs(LFC)=0.825; FDR=0.330
	3448/2446 DEGs/ensembl.
		Up 1441/920 DEGs/ensembl.
		Dw 2007/1526 DEGs/ensembl.

Found 104 (best=104) pathways for geneset num=0 'Reactome_Pathways_2024'
Pathway cutoffs p-value=0.050 fdr=0.200 min genes=3
DEGs found in enriched pathways:
	There are 2446 DEGs found in pathways
	825 (best=825) DEGs in pathways and 2623/1621 DEGs/ensembl not in pathways

	253 DEGs ensembl Up in pathways
	667 DEGs Up ensembl not in pathways

	572 DEGs ensembl Dw in pathways
	954 DEGs Dw ensembl not in pathways

In [4]:
mtd.abs_lfc_cutoff, mtd.fdr_lfc_cutoff, mtd.min_lfc_modulation

(np.float64(0.825), np.float64(0.33), 0.4)

In [5]:
len(mtd.dflfc)

3448

In [6]:
mtd.df_enr.head(6)

,pathway,pathway_id,pval,fdr,odds_ratio,combined_score,genes,num_of_genes
0,Neuronal System,R-HSA-112316,3.926e-20,7.047e-17,3.023,135.087,"['RAB3A', 'ABAT', 'RIMS1', 'HOMER3', 'PRKACB', 'PPFIA2', 'PRKCG', 'NSF', 'KC...",119
1,Extracellular Matrix Organization,R-HSA-1474244,3.066e-13,2.752e-10,2.806,80.858,"['DDR1', 'APP', 'COL18A1', 'PTPRS', 'ITGB4', 'ELN', 'COL12A1', 'ICAM2', 'TNC...",83
2,Signal Transduction,R-HSA-162582,1.912e-11,1.144e-08,1.487,36.695,"['IFT172', 'SPINT2', 'FZD10', 'MYLK', 'GJA1', 'PSMD6', 'SOX17', 'MYC', 'EPST...",427
3,Protein-protein Interactions at Synapses,R-HSA-6794362,4.919e-09,2.207e-06,4.142,79.238,"['GRIA1', 'NLGN1', 'PTPRS', 'NRXN1', 'NRXN3', 'LIN7A', 'GRM1', 'EPB41L5', 'G...",32
4,Transmission Across Chemical Synapses,R-HSA-112315,7.038e-09,2.527e-06,2.419,45.414,"['RAB3A', 'RASGRF1', 'GRIK3', 'PRKAG2', 'ABAT', 'KIF17', 'SLC6A4', 'RIMS1', ...",67
5,Potassium Channels,R-HSA-1296071,2.800e-08,8.376e-06,3.572,62.122,"['HCN4', 'KCNK9', 'KCNC2', 'KCNA1', 'KCNC4', 'KCNA4', 'KCNA5', 'KCNV1', 'GNG...",34

### Summary in text

In [7]:
mtd.geneset_num

0

In [8]:
mtd.set_db(mtd.geneset_num, verbose=True)

>>> Reactome_Pathways_2024

### Cases

In [9]:
mtd.case_list

['WNT', 'G4']

In [10]:
i = 0
case = case_list[i]
print(">>>", case)
ret, degs, degs_ensembl, dfdegs = mtd.open_case(case, verbose=False)

df_enr = mtd.df_enr
print(len(df_enr))
df_enr.head(3)

>>> WNT
104

,pathway,pathway_id,pval,fdr,odds_ratio,combined_score,genes,num_of_genes
0,Neuronal System,R-HSA-112316,3.926e-20,7.047e-17,3.023,135.087,"['RAB3A', 'ABAT', 'RIMS1', 'HOMER3', 'PRKACB', 'PPFIA2', 'PRKCG', 'NSF', 'KC...",119
1,Extracellular Matrix Organization,R-HSA-1474244,3.066e-13,2.752e-10,2.806,80.858,"['DDR1', 'APP', 'COL18A1', 'PTPRS', 'ITGB4', 'ELN', 'COL12A1', 'ICAM2', 'TNC...",83
2,Signal Transduction,R-HSA-162582,1.912e-11,1.144e-08,1.487,36.695,"['IFT172', 'SPINT2', 'FZD10', 'MYLK', 'GJA1', 'PSMD6', 'SOX17', 'MYC', 'EPST...",427

### DEGs to text

In [11]:
force=True
verbose=False

text = mtd.degs_to_text_all_cases_summary(force=force, verbose=verbose)
print(text)

# Project Medulloblastoma microarray study: microarray for Medulloblastoma
# Calculated in 14/11/2025 18:50:23
# geneset 0 - Reactome_Pathways_2024

0) WNT ('WNT')

BCA's LFC DEG cutoffs: abs(lfc)=0.825; fdr=0.330

	There are a total of 3448 DEGs, and 2446 have ensembl_id

		All DEGs Up (1441): A1BG-AS1, AACS, AADAT, AANAT, ABCA1, ABCC1, ABHD12B, ABHD14B, ACAA2, ACAD11, ACCS, ACOX2, ACP6, ACSS2, ACTC1, ACTL6A, ACTR3B, ACTR5, ADAM12, ADAM19, ADAMTS4, ADAMTSL1, ADAT3, ADCY3, ADPRH, AEN, AGXT2L2, AHCY, AHSA2, AKR7L, ALDH16A1, ALDH3B1, ALDH4A1, ALG1L2, ALG3, ALK, ALPL, AMHR2, ANGEL1, ANKDD1A, ANKHD1-EIF4EBP3, ANKMY1, ANKRD16, ANO2, ANTXR2, APCDD1, APLNR, APP, ARHGEF19, ASB13, ASXL2, ATAD3C, ATOH8, ATP13A1, ATP1B3, ATP2B1, ATP6V0D1, ATP6V1C2, ATP6V1E2, ATXN2L, AXIN2, B3GALNT2, B3GNT2, B3GNT8, B3GNT9, BAG2, BAMBI, BAZ1A, BHMT2, BLID, BMF, BMI1, BMP4, BOP1, BORA, BRCA1, BRIP1, BSG, C10orf114, C10orf2, C11orf49, C11orf82, C12orf33, C12orf5, C13orf33, C14orf101, C14orf142, C14orf48, C15orf54, C16orf59, C17orf82, C17orf96, C1QTNF9B-AS1, C1orf114, C1orf130, C1orf145, C1orf226, C20orf103, C20orf134, C22orf31, C2CD2, C2orf63, C2orf68, C2orf71, C3orf64, C3orf72, C3orf78, C4orf43, C5orf20, C5orf35, C5orf63, C6orf126, C8orf38, C8orf60, C9orf21, C9orf3, C9orf43, CABLES1, CABP4, CABP7, CACHD1, CACNA2D3, CACNA2D4, CAD, CADPS, CALCRL, CAMK1D, CAMKK1, CAPN13, CBWD7, CBX8, CC2D1B, CCBE1, CCDC109B, CCDC3, CCDC36, CCDC57, CCDC87, CCDC88C, CCDC97, CCND2, CCNE2, CCNG1, CCNL2, CCNO, CCT5, CD177, CD79B, CDC14A, CDC34, CDCA4, CDCA7L, CDH11, CDH16, CDH23, CDHR1, CDK6, CDKL1, CDKN2A, CDKN2C, CDT1, CECR5, CELF6, CEP112, CEP128, CEP152, CES1, CHAC2, CHAF1A, CHPF2, CHRAC1, CHST10, CKM, CLCN2, CLDN11, CLEC4A, CLIP4, CLK2, CLN6, CLPTM1L, CNDP1, CNGA3, COBL, COL12A1, COL18A1, COL2A1, COL5A1, COL6A2, COL9A3, COLQ, COMP, CP, CPLX3, CPNE4, CPS1, CRABP2, CROCC, CRTAP, CRTC3, CRYZ, CSNK1G2, CSPG5, CSRP2, CST3, CTPS, CTSK, CUBN, CUL4A, CXCR4, CYB561, CYB5RL, CYP27B1, CYP3A5, CYP3A7, CYP4F12, CYP4F8, DACH1, DACT1, DAK, DAND5, DAP, DAPK2, DCTD, DCUN1D3, DDIT4L, DDR2, DDX11, DDX11L2, DDX21, DDX52, DDX54, DEFB122, DEFB124, DERA, DGAT2, DGCR8, DIDO1, DKFZP434L187, DKFZP547J0410, DKK2, DLX3, DLX4, DMRT2, DNAH2, DNAJC10, DNHD1, DNPEP, DSC2, DSC3, DSCC1, DSE, DSG2, DSP, DUOX1, DUS3L, DVL3, E2F1, E2F7, EBF2, EBPL, ECE1, ECEL1, EDN3, EFEMP2, EFNA3, EFNA4, EGFEM1P, EGFLAM, EIF2C2, EIF3IP1, ELK3, ELMO3, ELN, EMID1, EMILIN2, EMILIN3, EML4, EML6, EMX2, EMX2OS, ENPP2, EPB41L5, EPHA10, EPHA2, EPHA3, EPHA7, ERCC1, ERI1, ESM1, ESPNL, ESYT1, EVC, EXOSC5, EYA1, F12, FAIM, FAM114A1, FAM124A, FAM136A, FAM174B, FAM175A, FAM183B, FAM19A4, FAM204A, FAM208B, FAM22F, FAM60A, FAM71F2, FAM76A, FAM78B, FAM86A, FAM86B1, FAM86B2, FAM86DP, FAM86FP, FANCA, FANCC, FANCL, FAP, FBLN1, FBN1, FBXL7, FEV, FGFR1, FHAD1, FJX1, FKBP10, FLJ31713, FLJ41327, FLJ42393, FLJ44715, FLJ45513, FLJ45831, FLRT2, FNDC3A, FOSL2, FOXA1, FOXD1, FOXL2, FPR3, FSCN1, FSTL4, FUK, FUT4, FYCO1, FZD10, FZD2, FZD6, FZD7, G3BP1, GABRD, GABRG3, GAD1, GADD45A, GADD45G, GAL3ST4, GALNT14, GANAB, GAR1, GAS2, GATA4, GBE1, GFPT1, GHRLOS, GJA3, GJD2, GLDN, GLI2, GLT8D2, GLTSCR2, GNAS-AS1, GNB3, GNL3, GOLGA1, GOLGA6A, GORAB, GPATCH4, GPC6, GPR15, GPR98, GPSM1, GRASP, GRB10, GSN, GSTT2, GTF3C2, HADH, HAND2, HAT1, HAUS5, HDLBP, HK2, HLA-DQB1, HLA-DRB5, HM13, HMBOX1, HMBS, HMCN1, HMG20B, HOMER2, HOOK2, HOXC4, HOXC6, HOXD1, HOXD11, HOXD13, HOXD3, HOXD4, HOXD8, HOXD9, HS3ST3B1, HSD11B2, HSPA5, HTRA3, HUNK, HUS1B, HYAL1, HYDIN, HYOU1, IBA57, IDUA, IER5, IFRD2, IFT172, IFT57, IGFBPL1, IGSF9, IL17REL, IL28RA, IL31RA, IL36B, ILF3, ILVBL, INADL, INTS6, IQCD, IQCF1, IRX6, ISL1, ITGA10, ITGA4, ITGBL1, ITPRIPL1, IVNS1ABP, JAM3, JMJD4, KCNA5, KCNH6, KCNH8, KCNJ5, KCNK17, KCNK5, KCTD14, KIAA0182, KIAA0564, KIAA1324, KIAA1683, KIAA1755, KIF7, KLHDC5, KLHDC8A, KRBOX1, KREMEN1, KRI1, KRTAP13-2, KRTAP13-4, KRTAP4-2, KRTAP9-1, KTI12, L3MBTL2, L3MBTL4, LAG3, LAMB2, LCLAT1, LCTL, LEF1, LEPRE1, LEPROT, LGALS3BP, LGR5, LHX2, LHX8, LIMD1, LINC00028, LINC00052, LINC00256A, LINC00317, LINC00340, LINC00476, LINC00478, LINC00482, LLGL2, LMNB2, LOC100126784, LOC100127910, LOC100127983, LOC100128343, LOC100128361, LOC100128563, LOC100128668, LOC100128946, LOC100129112, LOC100129280, LOC100129380, LOC100129387, LOC100129397, LOC100129617, LOC100129917, LOC100130057, LOC100130256, LOC100130468, LOC100130580, LOC100130761, LOC100130776, LOC100130876, LOC100130930, LOC100131000, LOC100131067, LOC100131541, LOC100131657, LOC100131822, LOC100131826, LOC100131840, LOC100133039, LOC100133315, LOC100133331, LOC100134285, LOC100190940, LOC100272216, LOC100505695, LOC100505880, LOC100506123, LOC100506342, LOC100653224, LOC100653259, LOC100653515, LOC142937, LOC154872, LOC158402, LOC282997, LOC283028, LOC283454, LOC284950, LOC285084, LOC285181, LOC285484, LOC285878, LOC286382, LOC338653, LOC338758, LOC339807, LOC348120, LOC375295, LOC388387, LOC388692, LOC388796, LOC389199, LOC389791, LOC389831, LOC391322, LOC400043, LOC400236, LOC400622, LOC401022, LOC401242, LOC440131, LOC440386, LOC440896, LOC440925, LOC441179, LOC441461, LOC441956, LOC442028, LOC442497, LOC572558, LOC641518, LOC642366, LOC643783, LOC645722, LOC651536, LOC728061, LOC728147, LOC729291, LOC729652, LOC729860, LOC731223, LOC90834, LOC92659, LPAR5, LPIN1, LRBA, LRIG3, LRIT1, LRIT2, LRP4, LRP8, LRRC52, LRRC55, LRRFIP1, LRRN1, LRRN4CL, LTBP3, LTBP4, LTC4S, LUZP1, LYPD6, LYSMD3, LZTR1, MAEA, MAF, MAN2C1, MANEAL, MAP3K14, MAPK12, MARC1, MARCH11, MAST2, MAT2A, MATN4, MBD6, MCART1, MCPH1, MEGF6, METAP1D, METTL1, METTL21A, METTL21B, MFHAS1, MGC23270, MGC45800, MGC72080, MIA3, MICAL1, MINA, MIR100HG, MIRLET7BHG, MKRN3, MLLT6, MLXIP, MMP14, MMP2, MMP23B, MMP7, MOB1A, MOB3B, MRPL19, MSH5, MSTO1, MT1F, MTAP, MTHFD2, MTMR11, MUC1, MUCL1, MUDENG, MYC, MYCL1, MYH15, MYH7B, MYH9, MYO15B, MYO1B, MYO1E, MYO3B, MYO7A, MYO7B, MYOT, MYOZ1, NAGS, NANOS1, NAP1L4, NAT9, NBLA00301, NBPF1, NEUROD4, NEUROG1, NFATC3, NFRKB, NINL, NKD1, NOB1, NOD2, NOM1, NOP14, NOTCH2NL, NOTUM, NPM3, NPS, NR4A1, NRCAM, NS3BP, NTN5, NTRK1, NUDT9P1, NXPH3, NXT1, OBFC1, OBSL1, OCA2, ODZ3, ONECUT2, ONECUT3, OPN4, OR10R3P, OR2C1, OR4N4, OR56B4, OR7E24, OR7E37P, ORAI2, ORM1, OSBPL1A, OSR2, OTX2, OXCT2, P4HA2, PABPC1L, PAICS, PAN2, PAQR4, PARD3B, PARD6G, PARP12, PART1, PASK, PAX3, PCBP3, PCBP3-OT1, PCBP4, PCDH8, PCDHB9, PCDHGB7, PCGF5, PCK2, PCSK1, PDCD6IP, PDE4D, PDGFC, PDIA5, PDK1, PDLIM4, PECR, PFDN4, PHACTR1, PHACTR2, PHC2, PHF21B, PHLDB3, PIF1, PIGN, PITPNM2, PITX2, PIWIL4, PKDCC, PKP2, PKP4, PLA2G4D, PLA2G4F, PLCB1, PLCG1, PLEKHA4, PLEKHF2, PLEKHG4, PLEKHO2, PLK1, PLOD1, PLOD2, PLS1, PMEL, PMP22, PODNL1, POFUT1, POGK, POGLUT1, POLE, POLR1B, POLR3D, POLR3E, POM121L1P, POU4F2, PPAN-P2RY11, PPFIBP2, PPM1N, PPP1R13L, PPRC1, PRAC, PRDM15, PRDM16, PRELID2, PRKD2, PRMT1, PRPH, PRRX1, PRSS23, PRTG, PSD4, PSMA1, PSMD9, PTBP3, PTGS1, PTPRS, PTPRU, PUS1, PUS10, PUS3, PUS7, PVT1, PYCR1, QSOX2, QTRTD1, RAB11FIP2, RAB11FIP4, RABEP2, RAMP3, RANBP2, RASGEF1B, RASIP1, RASL11B, RASSF8, RAVER2, RBBP6, RBBP9, RBFOX1, RBL1, RBM15B, RBM28, RBP7, RCAN3, RCC1, RD3, REC8, RFNG, RFX5, RGPD5, RGR, RHOBTB3, RHOQ, RNASE11, RNASEH2A, RNF220, RNF43, RNF7, RNU105A, RNU105B, ROR1, ROR2, RPGRIP1, RPL3L, RPS2, RSPO1, RSPO4, RSRC1, RTEL1, RTKN, RTKN2, RTTN, RUNX2, RUNX3, RXRA, RYK, SARM1, SCARA3, SCARF2, SCARNA1, SCARNA12, SCARNA17, SCLY, SDC2, SDCCAG3, SEC1, SELENBP1, SELV, SEMA3B, SEMA4F, SEMA6C, SERPINA5, SERTAD2, SEZ6L, SFMBT1, SFXN2, SFXN4, SGCA, SGSH, SH3BP1, SH3D19, SHC1, SHOX2, SIX3, SLC12A7, SLC13A3, SLC17A9, SLC1A7, SLC20A2, SLC23A3, SLC24A2, SLC25A10, SLC27A2, SLC35B1, SLC35D3, SLC35F2, SLC38A8, SLC39A4, SLC39A8, SLC43A1, SLC4A2, SLC6A10P, SLC6A2, SLC7A14, SLC7A6, SLCO5A1, SMARCC1, SMUG1, SNHG12, SNHG13, SNORA12, SNORA23, SNORA26, SNORA73A, SNORA74A, SNORA75, SNORD15A, SNRPB, SNTG2, SNX33, SOCS6, SP5, SP6, SP9, SPAG6, SPATA5L1, SPCS3, SPG20OS, SPG7, SPINK5, SPINT1, SPON2, SPRYD4, SRD5A2, SRL, SRRT, SRSF10, SRSF6, ST3GAL1, STARD13, STARD9, STAT5A, STGC3, STK32C, STON2, STX1A, STX3, SUSD1, SUSD2, SYK, TAL2, TANC1, TARBP1, TAS1R1, TBC1D30, TBC1D4, TBL1XR1, TBL2, TBR1, TBX19, TBX2, TC2N, TCF3, TCF7, TCHH, TCOF1, TEAD1, TEAD3, TELO2, TEX261, TFF3, TGFB1I1, TGFB3, TGFBR1, TH, THBS3, THBS4, THOC5, THSD1, TLE1, TLK2, TLX2, TMBIM4, TMEM120B, TMEM123, TMEM132C, TMEM176A, TMEM176B, TMEM180, TMEM185B, TMEM190, TMEM196, TMEM2, TMEM201, TMEM233, TMEM39A, TMEM43, TMEM45A, TMEM51, TMEM52, TMEM87A, TMEM91, TMPRSS13, TNC, TNFRSF11B, TNFSF11, TNNC1, TOM1L1, TOMM34, TOP1MT, TOP3B, TOX3, TP53, TP53BP2, TP53INP1, TP53RK, TP53TG3, TPD52L2, TPPP3, TRADD, TRAF5, TRAF7, TRAIP, TRAK2, TRIM14, TRIM17, TRIM46, TRMT2A, TROAP, TRPM3, TSC22D2, TSHR, TSHZ3, TSPAN11, TSPAN17, TSPAN5, TSPAN9, TUBAL3, TULP2, TWIST1, TWIST2, TXLNA, TXNRD1, TYW1B, UBAP2, UBR4, UCKL1, UCKL1-AS1, UCN2, UFSP1, UGGT1, URB2, USH2A, UTP15, VGLL3, VIT, VMAC, VPS37B, VRK1, VRK2, VSTM2A, VSTM4, VSX2, VWDE, WDFY2, WDR36, WDR4, WDR52, WDR6, WDR73, WIF1, WNT10A, WNT11, WRN, XBP1, XKR7, XLOC_000626, XLOC_000670, XLOC_001412, XLOC_002408, XLOC_002569, XLOC_002746, XLOC_002759, XLOC_006922, XLOC_006924, XLOC_006925, XLOC_009766, XLOC_011185, ZAK, ZAR1, ZBTB1, ZBTB39, ZBTB40, ZBTB42, ZC3HAV1, ZCCHC4, ZDHHC1, ZDHHC22, ZFHX3, ZFHX4, ZHX1-C8ORF76, ZMAT4, ZNF124, ZNF334, ZNF358, ZNF48, ZNF503, ZNF503-AS2, ZNF514, ZNF552, ZNF556, ZNF561, ZNF574, ZNF589, ZNF598, ZNF646, ZNF662, ZNF70, ZNF703, ZNF746, ZNF747, ZNF837, ZNRF3, ZRANB3, ZSCAN16, ZXDC, ZZZ3, lncRNA1, lncRNA100, lncRNA1003, lncRNA1013, lncRNA1019, lncRNA102, lncRNA1020, lncRNA1030, lncRNA1041, lncRNA105, lncRNA1054, lncRNA1064, lncRNA1075, lncRNA1082, lncRNA1087, lncRNA1088, lncRNA1098, lncRNA111, lncRNA1111, lncRNA1117, lncRNA113, lncRNA1132, lncRNA115, lncRNA1156, lncRNA1170, lncRNA1185, lncRNA120, lncRNA121, lncRNA122, lncRNA123, lncRNA125, lncRNA128, lncRNA129, lncRNA137, lncRNA138, lncRNA140, lncRNA142, lncRNA147, lncRNA148, lncRNA149, lncRNA153, lncRNA158, lncRNA16, lncRNA162, lncRNA163, lncRNA165, lncRNA167, lncRNA168, lncRNA170, lncRNA171, lncRNA172, lncRNA176, lncRNA177, lncRNA179, lncRNA18, lncRNA181, lncRNA182, lncRNA184, lncRNA185, lncRNA189, lncRNA19, lncRNA193, lncRNA195, lncRNA196, lncRNA198, lncRNA2, lncRNA201, lncRNA202, lncRNA205, lncRNA208, lncRNA21, lncRNA211, lncRNA214, lncRNA215, lncRNA216, lncRNA219, lncRNA225, lncRNA227, lncRNA228, lncRNA23, lncRNA230, lncRNA233, lncRNA236, lncRNA237, lncRNA241, lncRNA243, lncRNA251, lncRNA252, lncRNA253, lncRNA26, lncRNA260, lncRNA261, lncRNA262, lncRNA263, lncRNA265, lncRNA268, lncRNA27, lncRNA270, lncRNA275, lncRNA278, lncRNA28, lncRNA280, lncRNA281, lncRNA283, lncRNA289, lncRNA29, lncRNA291, lncRNA295, lncRNA298, lncRNA3, lncRNA30, lncRNA302, lncRNA304, lncRNA306, lncRNA307, lncRNA308, lncRNA309, lncRNA31, lncRNA311, lncRNA316, lncRNA318, lncRNA319, lncRNA32, lncRNA320, lncRNA324, lncRNA33, lncRNA330, lncRNA332, lncRNA337, lncRNA342, lncRNA343, lncRNA35, lncRNA351, lncRNA352, lncRNA353, lncRNA354, lncRNA356, lncRNA357, lncRNA359, lncRNA36, lncRNA362, lncRNA364, lncRNA365, lncRNA366, lncRNA369, lncRNA37, lncRNA371, lncRNA372, lncRNA384, lncRNA386, lncRNA387, lncRNA39, lncRNA398, lncRNA399, lncRNA4, lncRNA40, lncRNA402, lncRNA404, lncRNA407, lncRNA41, lncRNA412, lncRNA422, lncRNA424, lncRNA425, lncRNA428, lncRNA431, lncRNA433, lncRNA442, lncRNA445, lncRNA446, lncRNA452, lncRNA456, lncRNA458, lncRNA46, lncRNA461, lncRNA462, lncRNA467, lncRNA471, lncRNA475, lncRNA477, lncRNA478, lncRNA481, lncRNA484, lncRNA485, lncRNA486, lncRNA487, lncRNA488, lncRNA489, lncRNA494, lncRNA495, lncRNA498, lncRNA5, lncRNA501, lncRNA509, lncRNA51, lncRNA511, lncRNA524, lncRNA527, lncRNA531, lncRNA536, lncRNA54, lncRNA55, lncRNA550, lncRNA551, lncRNA553, lncRNA554, lncRNA56, lncRNA561, lncRNA562, lncRNA567, lncRNA57, lncRNA574, lncRNA577, lncRNA579, lncRNA580, lncRNA581, lncRNA585, lncRNA586, lncRNA588, lncRNA591, lncRNA593, lncRNA602, lncRNA607, lncRNA608, lncRNA609, lncRNA61, lncRNA612, lncRNA618, lncRNA62, lncRNA621, lncRNA622, lncRNA626, lncRNA632, lncRNA637, lncRNA643, lncRNA646, lncRNA651, lncRNA656, lncRNA66, lncRNA660, lncRNA664, lncRNA665, lncRNA670, lncRNA679, lncRNA689, lncRNA695, lncRNA7, lncRNA702, lncRNA703, lncRNA709, lncRNA71, lncRNA714, lncRNA718, lncRNA72, lncRNA725, lncRNA727, lncRNA73, lncRNA730, lncRNA737, lncRNA739, lncRNA74, lncRNA741, lncRNA744, lncRNA745, lncRNA746, lncRNA748, lncRNA754, lncRNA767, lncRNA77, lncRNA773, lncRNA783, lncRNA785, lncRNA789, lncRNA80, lncRNA802, lncRNA81, lncRNA810, lncRNA813, lncRNA816, lncRNA82, lncRNA830, lncRNA836, lncRNA839, lncRNA841, lncRNA844, lncRNA847, lncRNA849, lncRNA859, lncRNA87, lncRNA871, lncRNA875, lncRNA88, lncRNA888, lncRNA89, lncRNA9, lncRNA90, lncRNA900, lncRNA902, lncRNA91, lncRNA914, lncRNA92, lncRNA923, lncRNA947, lncRNA957, lncRNA96, lncRNA966, lncRNA97, lncRNA987, lncRNA992, psiTPTE22


In [12]:
fname, fname_cutoff = mtd.set_enrichment_name()
filefull1 = os.path.join(mtd.root_enrich, fname)
filefull2 = os.path.join(mtd.root_enrich, fname_cutoff)

print(os.path.exists(filefull1), filefull1)
print(os.path.exists(filefull2), filefull2)

True ../../colaboracoes/medulloblastoma/projects/medulloblastoma/enrichment_analyses/enricher_Reactome_Pathways_2024_medulloblastoma_microarray_for_G4_x_ctrl_not_normalized_cutoff_lfc_1.000_fdr_0.160.tsv
True ../../colaboracoes/medulloblastoma/projects/medulloblastoma/enrichment_analyses/enricher_Reactome_Pathways_2024_medulloblastoma_microarray_for_G4_x_ctrl_not_normalized_cutoff_lfc_1.000_fdr_0.160_pathway_pval_0.050_fdr_0.750_num_genes_3.tsv

### Most positive and most negative "pseudo-Pathways Modulation Index" (pPMI)

  - method: calc_all_pPMI() / calc_pathway_gene_index_per_case()
    
    - _type 'discrete'
      - mod_up = #mod_up_in_pathway if #mod_up_in_pathway > 0 else 1/2
      - mod_dw = #mod_dw_in_pathway if #mod_dw_in_pathway > 0 else 1/2
    
    - _type 'linear'
      - mod_up = 0.001 if no_data else sum of lfc
      - mod_dw = 0.001 if no_data else sum of lfc
  
    - _type 'linear_sat' (default saturation = 3)
      - mod_up = sum(lfc_positive (if lfc > +saturation = +saturation ))
      - mod_dw = sum(lfc_negative (if lfc < -saturation = -saturation ))
  
  - pPMI

    - ratio = np.abs(mod_up / mod_dw)  
    - pathway_mod_gene_index = log2(ratio)

In [13]:
lista = [-4., -3, -2, -1.5, -1, -0.5]
saturation = 3
[saturation if x < -saturation else x for x in lista]

[3, -3, -2, -1.5, -1, -0.5]

In [14]:
mtd.type_sat_ptw_index

'linear_sat'

#### calc_pPMI_summary

In [15]:
verbose=False
force=False

dff, text_all, df_sum_ptw = mtd.calc_pPMI_summary(force=force, verbose=verbose)
print(len(dff))

lines = [0, 5, 10]
dff.iloc[lines].T

444

,0,5,10
case,G4,G4,G4
pathway_id,R-HSA-1971475,R-HSA-114452,R-HSA-445717
pathway,A Tetrasaccharide Linker Sequence Is Required for GAG Synthesis,Activation of BH3-only Proteins,Aquaporin-mediated Transport
pPMI_total,-1.921,-0.115,-1.282
ratio_up_dw,0.264,0.923,0.411
pPMI_norm,-0.751,-0.285,-0.841
ratio_norm_up_dw,0.594,0.821,0.558
lfc_pPMI_up,2.876,9.986,11.779
lfc_pPMI_dw,-10.886,-10.818,-28.634
n_genes_annot_in_pathway,26,30,52
n_mod_in_pathway,13,17,33
perc_mod_in_pathway,0.5,0.567,0.635
n_mod_up_in_pathway,4,9,14
n_mod_dw_in_pathway,9,8,19
fdr,0.0,0.0,0.0
pval,0.0,0.0,0.0
mod_up_in_pathway,"['SDC4', 'GPC2', 'B4GALT7', 'B3GAT3']","['TP53BP2', 'YWHAQ', 'TP53', 'BMF', 'E2F1', 'BCL2L11', 'MAPK8', 'SFN', 'PMAI...","['AQP12A', 'AQP8', 'AQP5', 'PRKAR2B', 'MIP', 'PRKACG', 'GNB3', 'ADCY7', 'GNG..."
mod_dw_in_pathway,"['GPC5', 'VCAN', 'NCAN', 'B3GAT2', 'CSPG4', 'BCAN', 'XYLT1', 'GPC6', 'SDC3']","['YWHAH', 'PPP3CC', 'BCL2', 'BBC3', 'YWHAE', 'BID', 'BAD', 'PPP1R13B']","['AVP', 'GNG11', 'GNG10', 'ADCY5', 'GNG3', 'AQP7', 'ADCY8', 'PRKACB', 'ADCY4..."
lfc_up,"[0.733, 0.872, 0.842, 0.429]","[1.129, 0.49, 1.524, 1.189, 1.319, 0.502, 0.84, 2.028, 0.966]","[0.917, 0.565, 0.766, 0.892, 0.415, 0.405, 0.468, 0.491, 0.682, 0.887, 2.344..."
lfc_dw,"[-2.206, -0.873, -0.923, -1.096, -1.735, -1.712, -0.992, -0.582, -0.768]","[-1.191, -1.281, -2.256, -3.087, -0.519, -1.283, -0.78, -0.421]","[-0.596, -1.558, -0.655, -1.156, -1.642, -0.584, -1.187, -0.827, -0.783, -0...."
genes_annot_in_pathway,"['B3GAT3', 'B3GAT2', 'B3GAT1', 'BGN', 'B3GALT6', 'DCN', 'VCAN', 'BCAN', 'HSP...","['DYNLL1', 'BAD', 'DYNLL2', 'YWHAZ', 'TP73', 'TFDP1', 'TFDP2', 'BCL2', 'TP53...","['AVPR2', 'GNG13', 'GNG12', 'ADCY1', 'AQP9', 'ADCY5', 'AQP7', 'ADCY4', 'AQP8..."

In [16]:
dff.columns

Index(['case', 'pathway_id', 'pathway', 'pPMI_total', 'ratio_up_dw', 'pPMI_norm',
       'ratio_norm_up_dw', 'lfc_pPMI_up', 'lfc_pPMI_dw', 'n_genes_annot_in_pathway',
       'n_mod_in_pathway', 'perc_mod_in_pathway', 'n_mod_up_in_pathway', 'n_mod_dw_in_pathway',
       'fdr', 'pval', 'mod_up_in_pathway', 'mod_dw_in_pathway', 'lfc_up', 'lfc_dw',
       'genes_annot_in_pathway'],
      dtype='object')

In [17]:
i=0
case = case_list[i]
print(">>>", case)

cols = ['case', 'pathway_id', 'pathway', 'pPMI_total', 'ratio_up_dw', 'pPMI_norm',
       'ratio_norm_up_dw', 'lfc_pPMI_up', 'lfc_pPMI_dw', 'n_genes_annot_in_pathway',
       'n_mod_in_pathway', 'n_mod_up_in_pathway', 'n_mod_dw_in_pathway',
       'fdr', 'mod_up_in_pathway', 'mod_dw_in_pathway', 'lfc_up', 'lfc_dw']

df2 = dff[ (dff.case==case) & (~pd.isnull(dff.fdr)) ]
print(len(df2))
df2[cols]

>>> WNT
221

,case,pathway_id,pathway,pPMI_total,ratio_up_dw,pPMI_norm,ratio_norm_up_dw,lfc_pPMI_up,lfc_pPMI_dw,n_genes_annot_in_pathway,n_mod_in_pathway,n_mod_up_in_pathway,n_mod_dw_in_pathway,fdr,mod_up_in_pathway,mod_dw_in_pathway,lfc_up,lfc_dw
1,WNT,R-HSA-1971475,A Tetrasaccharide Linker Sequence Is Required for GAG Synthesis,-0.891,0.539,-0.891,0.539,7.499,-13.905,26,16,8,8,7.047e-17,"['XYLT2', 'GPC1', 'CSPG4', 'GPC2', 'CSPG5', 'GPC6', 'SDC2', 'HSPG2']","['SDC4', 'VCAN', 'B3GAT2', 'B3GAT1', 'AGRN', 'DCN', 'SDC3', 'BCAN']","[0.844, 0.519, 0.84, 1.032, 1.067, 1.42, 1.089, 0.688]","[-1.471, -1.846, -2.676, -1.558, -1.107, -1.237, -2.4, -1.61]"
2,WNT,R-HSA-2033519,Activated Point Mutants of FGFR2,-2.099,0.233,-0.514,0.700,1.855,-7.947,17,8,2,6,7.047e-17,"['FGF8', 'FGF22']","['FGF5', 'FGF1', 'FGFR2', 'FGF4', 'FGF9', 'FGF3']","[1.169, 0.685]","[-2.829, -1.835, -0.6, -0.403, -1.503, -0.777]"
4,WNT,R-HSA-114452,Activation of BH3-only Proteins,0.321,1.249,0.321,1.249,14.207,-11.377,30,20,10,10,7.047e-17,"['TP53BP2', 'AKT2', 'BMF', 'E2F1', 'AKT3', 'BCL2L11', 'TP53', 'SFN', 'BAD', ...","['YWHAH', 'PPP3CC', 'BCL2', 'BBC3', 'DYNLL1', 'YWHAG', 'YWHAE', 'TP73', 'MAP...","[0.835, 0.792, 2.674, 1.98, 0.779, 0.611, 0.939, 3.672, 0.762, 1.161]","[-2.344, -2.496, -1.191, -1.159, -0.422, -0.924, -0.736, -0.825, -0.594, -0...."
7,WNT,R-HSA-442755,Activation of NMDA Receptors and Postsynaptic Events,-3.205,0.108,-0.972,0.510,7.221,-66.593,93,57,10,47,7.047e-17,"['GIT1', 'CAMK1', 'PRKAB1', 'PRKAR2A', 'DLG1', 'GRIN2C', 'PPM1F', 'TUBAL3', ...","['TUBB4A', 'NRGN', 'TUBA1B', 'GRIN2B', 'TUBA4A', 'LIN7B', 'ADCY8', 'CAMK4', ...","[0.73, 0.471, 0.472, 0.444, 0.727, 0.465, 1.373, 0.966, 1.117, 0.457]","[-1.723, -0.772, -0.514, -1.756, -1.382, -0.786, -1.107, -1.976, -0.543, -3...."
9,WNT,R-HSA-187015,Activation of TRKA Receptors,-0.580,0.669,-0.580,0.669,2.126,-3.178,6,4,2,2,7.047e-17,"['NGF', 'NTRK1']","['NTRK2', 'ADCYAP1']","[0.411, 1.714]","[-1.827, -1.35]"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
434,WNT,R-HSA-8979227,Triglyceride Metabolism,-1.224,0.428,-0.738,0.599,7.256,-16.946,38,24,10,14,7.047e-17,"['AGMO', 'PPP1CC', 'PPP1CA', 'DGAT2', 'FABP4', 'GPAM', 'LPIN1', 'DGAT1', 'GP...","['FABP7', 'MOGAT1', 'PLIN1', 'MOGAT3', 'PRKACB', 'FABP6', 'PRKACG', 'FABP1',...","[0.495, 0.526, 0.515, 1.158, 0.428, 0.48, 1.661, 0.428, 0.572, 0.993]","[-1.467, -0.497, -0.403, -0.456, -1.827, -2.915, -0.825, -0.647, -1.405, -0...."
437,WNT,R-HSA-5218921,VEGFR2 Mediated Cell Proliferation,-2.745,0.149,-1.008,0.497,2.334,-15.649,19,13,3,10,7.047e-17,"['PRKCD', 'PLCG1', 'SPHK1']","['ITPR3', 'AHCYL1', 'PRKCZ', 'ITPR1', 'CALM1', 'KDR', 'PRKCA', 'ITPR2', 'PRK...","[0.912, 0.968, 0.455]","[-0.532, -1.042, -0.845, -2.165, -0.722, -1.318, -1.081, -2.023, -5.833, -0.92]"
438,WNT,R-HSA-432040,Vasopressin Regulates Renal Water Homeostasis via Aquaporins,-0.438,0.738,-0.531,0.692,13.293,-18.007,43,31,16,15,7.047e-17,"['AVP', 'GNGT1', 'RAB11FIP2', 'ADCY5', 'GNG3', 'PRKAR2A', 'AQP1', 'ADCY6', '...","['GNG11', 'GNG5', 'GNG7', 'ADCY8', 'PRKACB', 'ADCY4', 'PRKACG', 'AQP4', 'PRK...","[0.41, 0.555, 2.134, 0.987, 0.561, 0.444, 0.619, 0.601, 1.222, 1.471, 0.551,...","[-0.939, -0.419, -1.497, -1.107, -1.827, -0.634, -0.825, -2.766, -0.638, -1...."
440,WNT,R-HSA-1296072,Voltage Gated Potassium Channels,-1.158,0.448,-0.088,0.941,15.566,-34.747,43,31,10,21,7.047e-17,"['KCNH4', 'KCNQ5', 'KCNH6', 'KCNH8', 'KCNH2', 'KCNA5', 'KCNQ1', 'KCNG3', 'KC...","['KCNC3', 'KCNS3', 'KCNC4', 'KCNQ3', 'KCND2', 'KCNS1', 'KCNH7', 'KCND3', 'KC...","[0.935, 0.682, 2.873, 2.111, 0.918, 2.505, 0.618, 1.268, 2.863, 0.795]","[-0.983, -2.223, -2.033, -0.616, -5.355, -1.848, -1.161, -1.376, -0.628, -2...."
443,WNT,R-HSA-5140745,"WNT5A-dependent Internalization of FZD2, FZD5 and ROR2",0.006,1.004,1.006,2.009,6.710,-6.681,13,9,3,6,7.047e-17,"['FZD2', 'ROR2', 'ROR1']","['AP2B1', 'AP2A2', 'CLTB', 'WNT5A', 'AP2S1', 'AP2M1']","[1.686, 3.181, 1.843]","[-0.941, -0.772, -1.34, -2.632, -0.551, -0.445]"

In [18]:
df2[cols].head(4).T

,1,2,4,7
case,WNT,WNT,WNT,WNT
pathway_id,R-HSA-1971475,R-HSA-2033519,R-HSA-114452,R-HSA-442755
pathway,A Tetrasaccharide Linker Sequence Is Required for GAG Synthesis,Activated Point Mutants of FGFR2,Activation of BH3-only Proteins,Activation of NMDA Receptors and Postsynaptic Events
pPMI_total,-0.891,-2.099,0.321,-3.205
ratio_up_dw,0.539,0.233,1.249,0.108
pPMI_norm,-0.891,-0.514,0.321,-0.972
ratio_norm_up_dw,0.539,0.7,1.249,0.51
lfc_pPMI_up,7.499,1.855,14.207,7.221
lfc_pPMI_dw,-13.905,-7.947,-11.377,-66.593
n_genes_annot_in_pathway,26,17,30,93
n_mod_in_pathway,16,8,20,57
n_mod_up_in_pathway,8,2,10,10
n_mod_dw_in_pathway,8,6,10,47
fdr,0.0,0.0,0.0,0.0
mod_up_in_pathway,"['XYLT2', 'GPC1', 'CSPG4', 'GPC2', 'CSPG5', 'GPC6', 'SDC2', 'HSPG2']","['FGF8', 'FGF22']","['TP53BP2', 'AKT2', 'BMF', 'E2F1', 'AKT3', 'BCL2L11', 'TP53', 'SFN', 'BAD', ...","['GIT1', 'CAMK1', 'PRKAB1', 'PRKAR2A', 'DLG1', 'GRIN2C', 'PPM1F', 'TUBAL3', ..."
mod_dw_in_pathway,"['SDC4', 'VCAN', 'B3GAT2', 'B3GAT1', 'AGRN', 'DCN', 'SDC3', 'BCAN']","['FGF5', 'FGF1', 'FGFR2', 'FGF4', 'FGF9', 'FGF3']","['YWHAH', 'PPP3CC', 'BCL2', 'BBC3', 'DYNLL1', 'YWHAG', 'YWHAE', 'TP73', 'MAP...","['TUBB4A', 'NRGN', 'TUBA1B', 'GRIN2B', 'TUBA4A', 'LIN7B', 'ADCY8', 'CAMK4', ..."
lfc_up,"[0.844, 0.519, 0.84, 1.032, 1.067, 1.42, 1.089, 0.688]","[1.169, 0.685]","[0.835, 0.792, 2.674, 1.98, 0.779, 0.611, 0.939, 3.672, 0.762, 1.161]","[0.73, 0.471, 0.472, 0.444, 0.727, 0.465, 1.373, 0.966, 1.117, 0.457]"
lfc_dw,"[-1.471, -1.846, -2.676, -1.558, -1.107, -1.237, -2.4, -1.61]","[-2.829, -1.835, -0.6, -0.403, -1.503, -0.777]","[-2.344, -2.496, -1.191, -1.159, -0.422, -0.924, -0.736, -0.825, -0.594, -0....","[-1.723, -0.772, -0.514, -1.756, -1.382, -0.786, -1.107, -1.976, -0.543, -3...."

In [19]:
df2.tail(4).T

,437,438,440,443
case,WNT,WNT,WNT,WNT
pathway_id,R-HSA-5218921,R-HSA-432040,R-HSA-1296072,R-HSA-5140745
pathway,VEGFR2 Mediated Cell Proliferation,Vasopressin Regulates Renal Water Homeostasis via Aquaporins,Voltage Gated Potassium Channels,"WNT5A-dependent Internalization of FZD2, FZD5 and ROR2"
pPMI_total,-2.745,-0.438,-1.158,0.006
ratio_up_dw,0.149,0.738,0.448,1.004
pPMI_norm,-1.008,-0.531,-0.088,1.006
ratio_norm_up_dw,0.497,0.692,0.941,2.009
lfc_pPMI_up,2.334,13.293,15.566,6.71
lfc_pPMI_dw,-15.649,-18.007,-34.747,-6.681
n_genes_annot_in_pathway,19,43,43,13
n_mod_in_pathway,13,31,31,9
perc_mod_in_pathway,0.684,0.721,0.721,0.692
n_mod_up_in_pathway,3,16,10,3
n_mod_dw_in_pathway,10,15,21,6
fdr,0.0,0.0,0.0,0.0
pval,0.0,0.0,0.0,0.0
mod_up_in_pathway,"['PRKCD', 'PLCG1', 'SPHK1']","['AVP', 'GNGT1', 'RAB11FIP2', 'ADCY5', 'GNG3', 'PRKAR2A', 'AQP1', 'ADCY6', '...","['KCNH4', 'KCNQ5', 'KCNH6', 'KCNH8', 'KCNH2', 'KCNA5', 'KCNQ1', 'KCNG3', 'KC...","['FZD2', 'ROR2', 'ROR1']"
mod_dw_in_pathway,"['ITPR3', 'AHCYL1', 'PRKCZ', 'ITPR1', 'CALM1', 'KDR', 'PRKCA', 'ITPR2', 'PRK...","['GNG11', 'GNG5', 'GNG7', 'ADCY8', 'PRKACB', 'ADCY4', 'PRKACG', 'AQP4', 'PRK...","['KCNC3', 'KCNS3', 'KCNC4', 'KCNQ3', 'KCND2', 'KCNS1', 'KCNH7', 'KCND3', 'KC...","['AP2B1', 'AP2A2', 'CLTB', 'WNT5A', 'AP2S1', 'AP2M1']"
lfc_up,"[0.912, 0.968, 0.455]","[0.41, 0.555, 2.134, 0.987, 0.561, 0.444, 0.619, 0.601, 1.222, 1.471, 0.551,...","[0.935, 0.682, 2.873, 2.111, 0.918, 2.505, 0.618, 1.268, 2.863, 0.795]","[1.686, 3.181, 1.843]"
lfc_dw,"[-0.532, -1.042, -0.845, -2.165, -0.722, -1.318, -1.081, -2.023, -5.833, -0.92]","[-0.939, -0.419, -1.497, -1.107, -1.827, -0.634, -0.825, -2.766, -0.638, -1....","[-0.983, -2.223, -2.033, -0.616, -5.355, -1.848, -1.161, -1.376, -0.628, -2....","[-0.941, -0.772, -1.34, -2.632, -0.551, -0.445]"
genes_annot_in_pathway,"['AHCYL1', 'SRC', 'PRKCD', 'PDPK1', 'SPHK1', 'ITPR2', 'ITPR3', 'PRKCB', 'PRK...","['AVPR2', 'MYO5B', 'GNG13', 'GNG12', 'RAB11A', 'GNB1', 'PRKAR1B', 'GNB3', 'P...","['KCNF1', 'KCNH3', 'KCNH4', 'KCND1', 'KCNH5', 'KCND2', 'KCNH6', 'KCNB1', 'KC...","['FZD2', 'FZD5', 'WNT5A', 'AP2B1', 'CLTC', 'CLTB', 'AP2A2', 'CLTA', 'AP2A1',..."

In [20]:
df2.iloc[-1].genes_annot_in_pathway

"['FZD2', 'FZD5', 'WNT5A', 'AP2B1', 'CLTC', 'CLTB', 'AP2A2', 'CLTA', 'AP2A1', 'AP2S1', 'ROR2', 'ROR1', 'AP2M1']"

### Heatmap by gender
  - plot_pathway_heatmap_by_gender()
    - calc_pivot_pPMI()
      - calc_one_pathway_all_cases_gene_modulations()

### pivot summary
  - calc_pPMI_summary_and_pivot_tables
    - calc_pPMI_summary()
      - calc_all_pPMI():
        - _type == 'discrete': s_saturation = 'none'
        - _type == 'linear':   s_saturation = 'none'
        - _type == 'linear_sat': s_saturation = f'{saturation:.3f}'

In [21]:
dfpiv, dff, text_all, df_sum_ptw = mtd.calc_pPMI_summary_and_pivot_tables(force=False, verbose=False)
print(len(df_sum_ptw))
df_sum_ptw.head(2)

dfpiv

444

case                                                                G4    WNT
pathway
A Tetrasaccharide Linker Sequence Is Required for GAG Synthesis -1.921 -0.891
Activated Point Mutants of FGFR2                                -3.535 -2.099
Activation of BH3-only Proteins                                 -0.115  0.321
Activation of NMDA Receptors and Postsynaptic Events            -1.462 -3.205
Activation of TRKA Receptors                                    -4.517 -0.580
...                                                                ...    ...
Triglyceride Metabolism                                         -0.496 -1.224
VEGFR2 Mediated Cell Proliferation                              -2.239 -2.745
Vasopressin Regulates Renal Water Homeostasis via Aquaporins    -1.742 -0.438
Voltage Gated Potassium Channels                                -0.797 -1.158
WNT5A-dependent Internalization of FZD2, FZD5 and ROR2          -2.943  0.006

[222 rows x 2 columns]

In [22]:
want_print = False
sel_pathway_list = []

for pathway in dfpiv.index:
    sel_pathway_list.append(pathway)
    if want_print: print(pathway)

In [23]:
"; ".join(sel_pathway_list)

'A Tetrasaccharide Linker Sequence Is Required for GAG Synthesis; Activated Point Mutants of FGFR2; Activation of BH3-only Proteins; Activation of NMDA Receptors and Postsynaptic Events; Activation of TRKA Receptors; Aquaporin-mediated Transport; Arachidonate Metabolism; Assembly of Collagen Fibrils and Other Multimeric Structures; Basigin Interactions; Beta-catenin Independent WNT Signaling; Binding of TCF LEF CTNNB1 to Target Gene Promoters; CDC42 GTPase Cycle; CLEC7A (Dectin-1) Induces NFAT Activation; Ca-dependent Events; Ca2+ Pathway; CaM Pathway; Calmodulin Induced Events; Cardiac Conduction; Cell Death Signalling via NRAGE, NRIF and NADE; Chondroitin Sulfate Dermatan Sulfate Metabolism; Chylomicron Remodeling; Class B 2 (Secretin Family Receptors); Collagen Biosynthesis and Modifying Enzymes; Collagen Chain Trimerization; Collagen Degradation; Collagen Formation; Constitutive Signaling by Aberrant PI3K in Cancer; DAG and IP3 Signaling; DARPP-32 Events; DNA Replication Initiation; Defective B3GALTL Causes PpS; Degradation of the Extracellular Matrix; Dermatan Sulfate Biosynthesis; Diseases Associated With O-glycosylation of Proteins; Diseases Associated With Visual Transduction; Diseases of the Neuronal System; Dopamine Neurotransmitter Release Cycle; Downstream Signaling of Activated FGFR1; Downstream Signaling of Activated FGFR2; Downstream Signaling of Activated FGFR3; ECM Proteoglycans; EGR2 and SOX10-mediated Initiation of Schwann Cell Myelination; Effects of PIP2 Hydrolysis; Elastic Fibre Formation; Elevation of Cytosolic Ca2+ Levels; Extracellular Matrix Organization; FGFR1 Ligand Binding and Activation; FGFR1 Mutant Receptor Activation; FGFR1b Ligand Binding and Activation; FGFR1c Ligand Binding and Activation; FGFR2 Ligand Binding and Activation; FGFR2b Ligand Binding and Activation; FGFR2c Ligand Binding and Activation; FGFR3 Ligand Binding and Activation; FGFR3 Mutant Receptor Activation; FGFR3b Ligand Binding and Activation; FGFR3c Ligand Binding and Activation; FGFRL1 Modulation of FGFR1 Signaling; FRS-mediated FGFR1 Signaling; FRS-mediated FGFR2 Signaling; FRS-mediated FGFR3 Signaling; Formation of Intermediate Mesoderm; Formation of the Anterior Neural Plate; Formation of the Nephric Duct; Formation of the Posterior Neural Plate; Formation of the Ureteric Bud; G Alpha (12 13) Signalling Events; G Alpha (I) Signalling Events; G Alpha (Q) Signalling Events; G Alpha (S) Signalling Events; G Alpha (Z) Signalling Events; G-protein Mediated Events; GABA Synthesis, Release, Reuptake and Degradation; GPCR Downstream Signalling; Gastrulation; Glucagon-like Peptide-1 (GLP1) Regulates Insulin Secretion; Glutamate Neurotransmitter Release Cycle; Glycerophospholipid Biosynthesis; Glycerophospholipid Catabolism; Glycosaminoglycan Metabolism; Glycosphingolipid Biosynthesis; HDL Remodeling; HS-GAG Biosynthesis; Hemostasis; Heparan Sulfate Heparin (HS-GAG) Metabolism; IGF1R Signaling Cascade; IL-6-type Cytokine Receptor Ligand Interactions; IRS-mediated Signalling; IRS-related Events Triggered by IGF1R; Inflammasomes; Insulin Receptor Signalling Cascade; Integration of Energy Metabolism; Integrin Cell Surface Interactions; Intracellular Signaling by Second Messengers; Ion Homeostasis; Ketone Body Metabolism; Kidney Development; LGI-ADAM Interactions; Laminin Interactions; MAPK Family Signaling Cascades; MAPK1 MAPK3 Signaling; MET Activates PTK2 Signaling; MET Activates RAP1 and RAC1; Maturation of Spike Protein; Metabolism of Lipids; Molecules Associated With Elastic Fibres; Muscle Contraction; NCAM Signaling for Neurite Out-Growth; NCAM1 Interactions; NGF-independant TRKA Activation; NOTCH2 Intracellular Domain Regulates Transcription; NOTCH3 Intracellular Domain Regulates Transcription; NOTCH4 Intracellular Domain Regulates Transcription; NRAGE Signals Death Through JNK; Negative Regulation of the PI3K AKT Network; Neurexins and Neuroligins; Neuronal System; Neurotransmitter Receptors and Postsynaptic Signal Transmission; Neurotransmitter Release Cycle; Nitric Oxide Stimulates Guanylate Cyclase; Non-integrin membrane-ECM Interactions; Nucleotide-like (Purinergic) Receptors; O-glycosylation of TSR Domain-Containing Proteins; O-linked Glycosylation; Opioid Signalling; P2Y Receptors; PI Metabolism; PI-3K Cascade FGFR1; PI-3K Cascade FGFR2; PI-3K Cascade FGFR3; PI3K AKT Signaling in Cancer; PI3K Cascade; PI3K Events in ERBB2 Signaling; PI5P, PP2A and IER3 Regulate PI3K AKT Signaling; PLC Beta Mediated Events; POU5F1 (OCT4), SOX2, NANOG Activate Genes Related to Proliferation; Passive Transport by Aquaporins; Phase 4 - Resting Membrane Potential; Phospholipase C-mediated Cascade FGFR1; Phospholipase C-mediated Cascade; FGFR2; Phospholipase C-mediated Cascade; FGFR3; Phospholipid Metabolism; Plasma Lipoprotein Assembly, Remodeling, and Clearance; Platelet Activation, Signaling and Aggregation; Platelet Calcium Homeostasis; Platelet Homeostasis; Potassium Channels; Presynaptic Depolarization and Calcium Channel Opening; Protein-protein Interactions at Synapses; RA Biosynthesis Pathway; RAB Geranylgeranylation; RAC1 GTPase Cycle; RAF MAP Kinase Cascade; RHO GTPase Cycle; RHOA GTPase Cycle; RHOB GTPase Cycle; RHOD GTPase Cycle; RHOG GTPase Cycle; RUNX3 Regulates WNT Signaling; Receptor-type Tyrosine-Protein Phosphatases; Regulation of Commissural Axon Pathfinding by SLIT and ROBO; Regulation of FZD by Ubiquitination; Regulation of Gene Expression in Beta Cells; Regulation of Insulin Secretion; Regulation of MITF-M-dependent Genes Involved in Pigmentation; Regulation of NPAS4 Gene Transcription; Repression of WNT Target Genes; Retinoid Cycle Disease Events; SHC-mediated Cascade FGFR1; SHC-mediated Cascade FGFR2; SHC-mediated Cascade FGFR3; SHC1 Events in ERBB2 Signaling; SLC-mediated Transmembrane Transport; Scavenging by Class A Receptors; Sensory Processing of Sound; Sensory Processing of Sound by Inner Hair Cells of the Cochlea; Sensory Processing of Sound by Outer Hair Cells of the Cochlea; Signal Transduction; Signaling by ALK; Signaling by Activated Point Mutants of FGFR1; Signaling by Activated Point Mutants of FGFR3; Signaling by ERBB2 KD Mutants; Signaling by ERBB2 TMD JMD Mutants; Signaling by ERBB2 in Cancer; Signaling by ERBB4; Signaling by FGFR; Signaling by FGFR in Disease; Signaling by FGFR1; Signaling by FGFR1 in Disease; Signaling by FGFR3; Signaling by FGFR3 in Disease; Signaling by GPCR; Signaling by NTRK1 (TRKA); Signaling by NTRK2 (TRKB); Signaling by NTRKs; Signaling by PDGF; Signaling by Receptor Tyrosine Kinases; Signaling by Retinoic Acid; Signaling by Rho GTPases; Signaling by Rho GTPases, Miro GTPases and RHOBTB3; Signaling by Type 1 Insulin-like Growth Factor 1 Receptor (IGF1R); Signaling by WNT; Signalling to RAS; Specification of Primordial Germ Cells; Specification of the Neural Plate Border; Synthesis of 5-Eicosatetraenoic Acids; Synthesis of PI; TCF Dependent Signaling in Response to WNT; Tandem Pore Domain Potassium Channels; The Canonical Retinoid Cycle in Rods (Twilight Vision); Transcriptional Regulation by MECP2; Transcriptional Regulation of Pluripotent Stem Cells; Transmission Across Chemical Synapses; Transport of Bile Salts and Organic Acids, Metal Ions and Amine Compounds; Transport of Inorganic Cations Anions and Amino Acids Oligopeptides; Transport of Small Molecules; Triglyceride Catabolism; Triglyceride Metabolism; VEGFR2 Mediated Cell Proliferation; Vasopressin Regulates Renal Water Homeostasis via Aquaporins; Voltage Gated Potassium Channels; WNT5A-dependent Internalization of FZD2, FZD5 and ROR2'

### Heatmap plots prepraration

### Pathways' discover code

In [ ]:
term = 'igf'
term = 'Phagocytosis'
term = 'translational'
term = 'Scaven'
term = 'fibrin'
term = 'Activat'; not_term = 'FGFR'
term = 'FGFR'; not_term = ''
term = 'Biosynthesis'; not_term = ''
term = 'nuclear'; not_term = ''
term = 'Degradation'; not_term = ''
term = 'neur'; not_term = ''
term = 'synap'; not_term = ''
term = 'channel'; not_term = ''
term = 'tabol'; not_term = 'lipid'
term = 'transp'; not_term = 'lipid'
term = 'Interac'; not_term = ''
term = 'collag'; not_term = ''
term = 'GTPase'; not_term = ''
term = 'transduction'; not_term = ''

print(">>>", term)

if isinstance(not_term, str) and not_term != '':
    lista = [x for x in mtd.selected_pivot_pathway_list if term.lower() in x.lower() and not_term.lower() not in x.lower()]
else:
    lista = [x for x in mtd.selected_pivot_pathway_list if term.lower() in x.lower()]

lista = [str(x) for x in np.unique(lista)]
lista

In [24]:
terms = ['igf', 'insulin', 'IGFBP']
terms = ['neutrophil', 'vascular', 'nets', 'degranulation']
terms = ['MHC', 'presentation', 'processing', 'TAP', 'endoplasmic']
terms = ['Vascular', 'Degranulation']

terms = ['Degradation', 'Biosynthesis']
terms = ['synap', 'transm', 'channel']
terms = ['neur', 'gaba', 'colin', 'transm']
terms = ['neur']
terms = ['Secretion', 'insulin', 'panc']
terms = ['adherence', 'junctions']
terms = ['syndrome', 'disease']
terms = ['receptor']
terms = ['translational', 'modification', 'carbox', 'Phosphor', 'phosphat', 'dephosphor', 'glycoz', 'cleavag']
terms = ['catenin', 'wnt', 'CDC42', 'LRP6', 'cadherin', 'DVS', 'DLH', 'LRP', 'GSK', 'AXIN', 'FZD']
terms = ['card', 'heart', 'muscle']
terms = ['Transduction', 'VISION', 'AUDITION', 'sensor']
terms = ['hemostasis', 'neutrophil', 'platelet', 'Aggregation', 'degranulation', 'amyloid', 'fibrin', 'Heparan']
terms = ['ECM', 'matrix', 'Elastic',  'Extracellular Matrix', 'heparan']
terms = ['adherence', 'junction', 'notch']
terms = ['lipid', 'HDL', 'LDL', 'trigl', 'choles']
terms = ['Myelin', 'Schwann', 'neuron']
terms = ['Laminin', 'Integrin', 'adhesion', 'migration']
terms = ['gap', 'junction']
terms = ['complement', 'c3', 'c4', 'c5']
terms = ['apoptosis', 'bh', 'bcl']
terms = ['acqua', 'transport', 'carrier', 'solute']
terms = ['gpcr', 'seven', 'G-protein', 'P2Y', 'FGFR']
terms = ['cytok', 'inflam', 'dectin', 'NFAT', 'NLRP3', 'TNF', 'OSM']
terms = ['apopto', 'inflammasome', 'dectin', 'NFAT', 'NLRP3', 'TNF', 'OSM', 'BH', 'CHEMIO', 'CYTO']
terms = ['scav', 'neurodegen', 'LDL', 'lipoprotein']
terms = ['nuclear', 'hdl', 'hormone', 'cholesterol', 'LXR', 'ABC', 'CETP', 'Apolipoprotein', 'PPAR', 'FXR', 'HRE', 'DNA']
terms = ['DAG', 'IP3', 'PIP2', 'PI-3K', 'PI3K']
terms = ['tyr', 'kinase', 'phospha']
terms = ['Neurotransmitter', 'GABA', 'Glut', 'Dopa', 'Acetyl', 'Purinergic']
terms = ['membrane', 'plasma']

lista=[]
for term in terms:
    lista += [x for x in mtd.selected_pivot_pathway_list if term.lower() in x.lower()]

lista = [str(x) for x in np.unique(lista)]
lista

['Non-integrin membrane-ECM Interactions',
 'Phase 4 - Resting Membrane Potential',
 'Plasma Lipoprotein Assembly, Remodeling, and Clearance',
 'SLC-mediated Transmembrane Transport']

In [ ]:
terms = ['scaveng', 'nuclear']

lista=[]
for term in terms:
    lista += [x for x in mtd.selected_pivot_pathway_list if term.lower() in x.lower()]

lista

In [ ]:
[x for x in set_hemostasis if x not in sel_pathway_list]

In [ ]:
mtd.group_female_list, mtd.group_male_list

In [ ]:
mtd.saturation_lfc_index

### Heatmap plots

In [ ]:
mtd.pPMI_normalized

In [ ]:
set_name = set_hemostasis
set_title = 'Hemostasis'
width=1400
height=1300

if mtd.pPMI_normalized:
    fig, dfpiv_female, dfpiv_male, text_all = mtd.plot_pathway_heatmap_by_gender(set_name, set_title, height=height, width=width, zlim=5, maxLen=75, with_pPMI_obs=False, do_case_translate=True)
else:
    fig, dfpiv_female, dfpiv_male, text_all = mtd.plot_pathway_heatmap_by_gender(set_name, set_title, height=height, width=width, zlim=6, maxLen=75, with_pPMI_obs=False, do_case_translate=True)

print('female', len(dfpiv_female))
print('male', len(dfpiv_male))
if fig: fig.show()

In [ ]:
print(text_all)

In [ ]:
dff = mtd.dff

case = 'g2a_male'
pathway = 'Signaling by BRAF and RAF1 Fusions'

row_dff = dff[ (dff.case == case) & (dff.pathway == pathway)]
row_dff

In [ ]:
dfpiv_female

In [ ]:
for i in range(len(dfpiv_female)):
    row = dfpiv_female.iloc[i]
    pathway = row.name
    for col in row.index:
        val = row[col]
        print(i, pathway, val)
        break

In [ ]:
dfpiv, dff, text_all, df_sum_ptw = mtd.calc_pPMI_summary_and_pivot_tables(verbose=verbose)

In [ ]:
case = 'g2a_male'
pathway = 'Signaling by BRAF and RAF1 Fusions'

row_dff = dff[ (dff.case == case) & (dff.pathway == pathway)]
row = row_dff.iloc[0]

print(row_dff['mod_up_in_pathway'], row_dff['mod_dw_in_pathway'])
row_dff.iloc[0]['mod_up_in_pathway']