In [1]:
!python --version

Python 3.11.14

## GDC

https://docs.gdc.cancer.gov/API/Users_Guide/Downloading_Files/

sample  
 ├── primary_site       (organ)  
 ├── disease_type       (broad class)  
 ├── subtype_global     (cross-cancer)  
 ├── subtype_tissue     (within-cancer)  
 └── histology          (biological family)

### TCGA / GDC Portal

https://portal.gdc.cancer.gov/

### 🧠 Big picture (this is powerful)

- You’ve essentially built the backbone of:
- cBioPortal-like explorer
- cohort stratification engine
- patient-specific pipeline (your perturbation_agent 🔥)

### 💡 Flow

> project → project_id  
> primary_sites → pid and disease_type  
> subtypes → subtype_id  
> stages →  stage_id  
> case_id → case_ids or UUIDs  
> samples → sample_id [tumor, normal]  
> aliquots → aliquot_id  
> files → file_id

In [2]:
import os, sys
import pandas as pd

from pathlib import Path

ROOT = Path().resolve().parent.parent
SRC = os.path.join(ROOT, "src")

if str(SRC) not in sys.path:
    sys.path.append(str(SRC))

print("ROOT:", ROOT)
print("SRC added:", SRC)

from libs.calc_degs_lib import CALC_DEGS
from libs.tcga_gdc_lib import *
from libs.Basic import *

ROOT: /home/flavio/uv
SRC added: /home/flavio/uv/src

### 👉 a TCGA cohort builder + data retrieval engine

Which means you can easily extend to:


> pan-cancer analyses  
> patient-specific pipelines (your perturb_agent 🔥)  
> automated workflows (Nextflow-ready)  

#### 🚀 Next steps

> Production pipeline  
  - CLI tool
  - cached queries
  - reproducible outputs

> Expression matrix builder  
  - auto-download
  - merge TSVs
  - DESeq2-ready matrix

> Patient-level analysis
  - per-case DEG
  - pathway perturbation scoring

### Defaults

In [3]:
ROOT = Path().resolve().parent
root_data = os.path.join(ROOT, "data/tcga")

gdc = GDC(root_data=root_data)

os.listdir(root_data)[:10]

['subtype_for_TCGA-KIRC.tsv',
 'degs.txt',
 'cases_for_TCGA-LUSC.tsv',
 'subtype_for_TCGA-HNSC.tsv',
 'cases_for_TCGA-PCPG.tsv',
 'Gene_Expression_Quantification_for_TCGA-BRCA_case_0045349c-69d9-4306-a403-c9c1fa836644_sample_type_Primary_Tumor_stage_unknown_fileid_0e0df72c-33c0-4e4f-939c-a4d45a6e1ea3.tsv',
 'cases_for_TCGA-THYM.tsv',
 'cases_for_TCGA-PAAD.tsv',
 'cases_for_TCGA-LAML.tsv',
 'Gene_Expression_Quantification_for_TCGA-BRCA_case_011b9b2d-ebe5-42bf-9662-d922faccc7a1_sample_type_Primary_Tumor_stage_Stage_IA_fileid_89409cf3-e710-47fd-af3c-6f8f0dec7c90.tsv']

### Get all programs

In [4]:
force=False
verbose=True

prog_list = gdc.get_gdc_progams(force=force, verbose=verbose)

File read at '/home/flavio/uv/perturb_agent/data/tcga/programs.txt'

In [5]:
np.array(prog_list)

array(['TCGA', 'MATCH', 'TARGET', 'CGCI', 'CMI', 'APOLLO', 'BEATAML1.0',
       'CPTAC', 'MP2PRT', 'ALCHEMIST', 'CCDI', 'CCG', 'CDDP_EAGLE',
       'CTSP', 'EXCEPTIONAL_RESPONDERS', 'FM', 'HCMI', 'MMRF', 'NCICCR',
       'OHSU', 'ORGANOID', 'RC', 'REBC', 'TRIO', 'VAREPOP', 'WCDT'],
      dtype='<U22')

### Primary sites given a program

In [6]:
gdc.url_gdc_project

'https://api.gdc.cancer.gov/projects'

In [7]:
force=False
verbose=True

program = 'TCGA'

df_psi = gdc.get_primary_sites(program=program, force=force, verbose=verbose)

print(len(df_psi))
df_psi.head(12)

Table opened ((33, 5)) at '/home/flavio/uv/perturb_agent/data/tcga/primary_site_program_TCGA.tsv'
33

,pid,primary_site,project_id,disease_type,name
0,TCGA-ACC,Adrenal gland,TCGA-ACC,Adenomas and Adenocarcinomas,Adrenocortical Carcinoma
1,TCGA-PCPG,"Adrenal gland, Retroperitoneum and peritoneum,...",TCGA-PCPG,Paragangliomas and Glomus Tumors,Pheochromocytoma and Paraganglioma
2,TCGA-BLCA,Bladder,TCGA-BLCA,"Epithelial Neoplasms, NOS, Squamous Cell Neopl...",Bladder Urothelial Carcinoma
3,TCGA-LGG,Brain,TCGA-LGG,Gliomas,Brain Lower Grade Glioma
4,TCGA-GBM,Brain,TCGA-GBM,"Not Reported, Gliomas",Glioblastoma Multiforme
5,TCGA-BRCA,Breast,TCGA-BRCA,"Adnexal and Skin Appendage Neoplasms, Adenomas...",Breast Invasive Carcinoma
6,TCGA-LUAD,Bronchus and lung,TCGA-LUAD,"Ductal and Lobular Neoplasms, Cystic, Mucinous...",Lung Adenocarcinoma
7,TCGA-LUSC,Bronchus and lung,TCGA-LUSC,"Squamous Cell Neoplasms, Adenomas and Adenocar...",Lung Squamous Cell Carcinoma
8,TCGA-MESO,"Bronchus and lung, Heart, mediastinum, and pleura",TCGA-MESO,Mesothelial Neoplasms,Mesothelioma
9,TCGA-CESC,"Cervix uteri, Ovary",TCGA-CESC,"Squamous Cell Neoplasms, Cystic, Mucinous and ...",Cervical Squamous Cell Carcinoma and Endocervi...
10,TCGA-COAD,"Colon, Rectosigmoid junction",TCGA-COAD,"Cystic, Mucinous and Serous Neoplasms, Complex...",Colon Adenocarcinoma
11,TCGA-READ,"Colon, Rectosigmoid junction, Rectum, Connecti...",TCGA-READ,"Cystic, Mucinous and Serous Neoplasms, Adenoma...",Rectum Adenocarcinoma

In [8]:
df_psi.tail(3)

,pid,primary_site,project_id,disease_type,name
30,TCGA-THCA,Thyroid gland,TCGA-THCA,"Squamous Cell Neoplasms, Epithelial Neoplasms,...",Thyroid Carcinoma
31,TCGA-UCS,"Uterus, NOS, Corpus uteri",TCGA-UCS,"Basal Cell Neoplasms, Complex Mixed and Stroma...",Uterine Carcinosarcoma
32,TCGA-UCEC,"Uterus, NOS, Corpus uteri",TCGA-UCEC,"Not Reported, Cystic, Mucinous and Serous Neop...",Uterine Corpus Endometrial Carcinoma

### Subtypes explanation

👉 GDC does NOT give you clean biological subtypes
👉 You must derive them yourself

This is actually a feature, not a bug — because:

> you control granularity  
> you can harmonize across cancers  
> you avoid noisy labels  


💡 If you want to level this up

I can help you build:

🔬 A cross-TCGA subtype harmonizer
maps all projects → unified subtype ontology
handles synonyms (adenocarcinoma, NOS, etc.)
outputs clean ML-ready labels

👉 That would massively improve your perturbation analysis.

In [9]:
ipsi = 6
pid = df_psi.iloc[ipsi].pid
primary_site = df_psi.iloc[ipsi].primary_site

print(ipsi, pid, primary_site)

6 TCGA-LUAD Bronchus and lung

- Brain tumors do NOT use AJCC staging (3 - TCGA-LGG Brain)

In [10]:
force=False
verbose=True

pid = df_psi.iloc[ipsi].pid
primary_site = df_psi.iloc[ipsi].primary_site

print(ipsi, pid, primary_site)

df_cases, df_subt, df_prof = gdc.get_cases_and_subtypes(pid=pid, batch_size=200, do_filter=False, force=force, verbose=verbose)

print("df_cases", len(df_cases), "df_subt", len(df_subt))

6 TCGA-LUAD Bronchus and lung
Table opened ((585, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_TCGA-LUAD.tsv'
df_cases 585 df_subt 23

### df_subt

In [11]:
print(len(df_subt))
df_subt

23

,pid,subtype_global,tumor_class,subtype_tissue,stage,n
0,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,unknown,136
1,TCGA-LUAD,other,other,other,unknown,136
2,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA,76
3,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IB,71
4,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IIIA,40
5,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IIB,37
6,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IIA,27
7,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IV,14
8,TCGA-LUAD,other,other,other,Stage IB,9
9,TCGA-LUAD,other,other,other,Stage IA,8
10,TCGA-LUAD,other,other,other,Stage IIA,7
11,TCGA-LUAD,other,other,other,Stage IIIA,6
12,TCGA-LUAD,other,other,other,Stage IIB,4
13,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage I,3
14,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IIIB,2
15,TCGA-LUAD,squamous,squamous_cell_carcinoma,squamous,Stage IA,2
16,TCGA-LUAD,other,lymphoma,other,unknown,1
17,TCGA-LUAD,clear_cell,adenocarcinoma,clear_cell,unknown,1
18,TCGA-LUAD,clear_cell,other,clear_cell,Stage IA,1
19,TCGA-LUAD,endometrioid,adenocarcinoma,endometrioid,Stage IA,1
20,TCGA-LUAD,other,other,other,Stage IV,1
21,TCGA-LUAD,squamous,squamous_cell_carcinoma,squamous,Stage IIA,1
22,TCGA-LUAD,squamous,squamous_cell_carcinoma,squamous,Stage IIIA,1

### df_cases

In [12]:
df_cases.head(3)

,primary_site,disease_type,case_id,diagnoses,pid,subtype_global,stage_ajcc,primary_diagnosis,tumor_grade,stage_clin,...,disease_type_norm,diagnosis_norm,tumor_class,histology,subtype_tissue,consistency,validity,n,frac,sstage
0,Bronchus and lung,Adenomas and Adenocarcinomas,07b5663f-9a54-4462-b6c1-6fc8116b8714,"[{'primary_diagnosis': 'Adenocarcinoma, NOS', ...",TCGA-LUAD,adenocarcinoma_generic,Stage IA,"Adenocarcinoma, NOS",NaN,NaN,...,adenomas and adenocarcinomas,adenocarcinoma,adenocarcinoma,epithelial,lung_adenocarcinoma,ok,valid,1,0.001709,I
1,Bronchus and lung,Adenomas and Adenocarcinomas,294ff941-aea1-4588-9a0e-e9f5393e2bb6,[{'primary_diagnosis': 'Infiltrating duct carc...,TCGA-LUAD,other,Stage IA,"Infiltrating duct carcinoma, NOS",NaN,NaN,...,adenomas and adenocarcinomas,infiltrating duct carcinoma,other,other,other,ok,ambiguous,1,0.001709,I
2,Bronchus and lung,Adenomas and Adenocarcinomas,ebb33753-9d38-4368-9033-3e55f129d00d,[{'primary_diagnosis': 'Adenocarcinoma with mi...,TCGA-LUAD,adenocarcinoma_generic,unknown,Adenocarcinoma with mixed subtypes,NaN,NaN,...,adenomas and adenocarcinomas,adenocarcinoma with mixed subtypes,adenocarcinoma,epithelial,lung_adenocarcinoma,ok,valid,1,0.001709,missing

In [13]:
cols = ["pid", "case_id", "subtype_global", "tumor_class", "subtype_tissue", "stage"]

df_cases[cols].head(12)

,pid,case_id,subtype_global,tumor_class,subtype_tissue,stage
0,TCGA-LUAD,07b5663f-9a54-4462-b6c1-6fc8116b8714,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA
1,TCGA-LUAD,294ff941-aea1-4588-9a0e-e9f5393e2bb6,other,other,other,Stage IA
2,TCGA-LUAD,ebb33753-9d38-4368-9033-3e55f129d00d,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,unknown
3,TCGA-LUAD,781f40c9-c099-4c96-8269-ebe2a449c93d,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IIB
4,TCGA-LUAD,5134c56f-8286-4ec8-8348-237cee7dad5e,other,other,other,Stage IIA
5,TCGA-LUAD,369f14c4-2191-4962-a309-3e23ddc4e5fc,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IIA
6,TCGA-LUAD,e51f717f-72e8-400e-9f35-fc5dc32fdf71,other,other,other,unknown
7,TCGA-LUAD,bbe88801-34f3-46d2-bbfd-b46c3901ed71,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IB
8,TCGA-LUAD,d2c1e896-6886-4122-bb48-5fbcd3f641f4,other,other,other,unknown
9,TCGA-LUAD,108a71cf-b9db-47cd-aa74-c03ec989b41b,other,other,other,Stage IIA
10,TCGA-LUAD,9c7875ad-ab71-4d48-b2e3-e4c7a46393e9,other,other,other,unknown
11,TCGA-LUAD,d12b6930-9ae4-4fe7-ad69-d183135c91ab,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IB

### Samples

In [14]:
force=False
force=False
verbose=True

isubt=0

row = df_subt.iloc[isubt]

pid = row.pid
subtype_global = row.subtype_global
tumor_class = row.tumor_class
subtype_tissue = row.subtype_tissue
stage = None # row.stage

# s_case = f"{pid} subtype '{subtype_global}' tumor '{tumor_class}' subtype_tissue '{subtype_tissue}' stage '{stage}'"
# print(s_case)
df_samples = gdc.get_samples_for_pid_subtypes(pid=pid, subtype_global=subtype_global,
                                             tumor_class=tumor_class, subtype_tissue=subtype_tissue,
                                             batch_size=200, force=force, verbose=verbose)

print(len(df_samples))

Table opened ((585, 24)) at '/home/flavio/uv/perturb_agent/data/tcga/cases_for_TCGA-LUAD.tsv'
>>> TCGA-LUAD subtype 'adenocarcinoma_generic' tumor 'adenocarcinoma' subtype_tissue 'lung_adenocarcinoma'
Table opened ((403, 14)) at '/home/flavio/uv/perturb_agent/data/tcga/samples_for_TCGA-LUAD_subtype_'adenocarcinoma_generic'_tumor_'adenocarcinoma'_subtype_tissue_'lung_adenocarcinoma'.tsv'
403

### Available sample types

In [15]:
df_samples.sample_type.unique()

array(['Solid Tissue Normal', 'Primary Tumor', 'Blood Derived Normal'],
      dtype=object)

In [16]:
df2 = df_samples[~df_samples.sample_type.str.contains('Blood', case=False, na=False)]
print(len(df_samples), len(df2))
df2.head()

403 278

,case_id,submitter_id,sample_id,sample_type,barcode_id,file_id,file_name,data_type,data_format,pid,subtype_global,tumor_class,subtype_tissue,stage
0,07b5663f-9a54-4462-b6c1-6fc8116b8714,TCGA-44-2655,298662ad-dbff-4344-9b80-d744c258c292,Solid Tissue Normal,TCGA-44-2655-11A,8f5ab8b4-72a8-4365-a54a-f7dac0e384bd,3211c900-d9ba-4b44-9329-8bc476c59266.methylati...,Methylation Beta Value,TXT,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA
1,07b5663f-9a54-4462-b6c1-6fc8116b8714,TCGA-44-2655,9fcabda1-ea79-4188-8b3f-7d0fd060a819,Primary Tumor,TCGA-44-2655-01A,b2b7acb4-ece5-4e00-bd05-2de5f985bb8a,deae5c6f-6617-4729-98b2-b89ee95cf663.somatic.S...,Structural Rearrangement,BEDPE,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA
2,07b5663f-9a54-4462-b6c1-6fc8116b8714,TCGA-44-2655,9fcabda1-ea79-4188-8b3f-7d0fd060a819,Primary Tumor,TCGA-44-2655-01A,87ff6237-1814-4f3b-abd8-d0e0d6f472be,92b25422-ea11-4b60-bc35-e86c0d73db9f.mirbase21...,Isoform Expression Quantification,TXT,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA
3,07b5663f-9a54-4462-b6c1-6fc8116b8714,TCGA-44-2655,9fcabda1-ea79-4188-8b3f-7d0fd060a819,Primary Tumor,TCGA-44-2655-01A,5c628172-65f9-4bd7-b608-c24f6745f5ab,af6115c8-f05b-43ea-9e95-5e9cc78e2e89.somatic.S...,Structural Rearrangement,BEDPE,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA
4,07b5663f-9a54-4462-b6c1-6fc8116b8714,TCGA-44-2655,9fcabda1-ea79-4188-8b3f-7d0fd060a819,Primary Tumor,TCGA-44-2655-01A,6773903f-ed74-4bb1-8fe4-583ef441861b,HILLY_p_TCGA_b90_wRedos_SNP_N_GenomeWideSNP_6_...,Simple Germline Variation,TSV,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA

In [17]:
df3 = df_samples[df_samples.sample_type == 'Primary Tumor']
print(len(df_samples), len(df2), len(df3))
df3.head()

403 278 252

,case_id,submitter_id,sample_id,sample_type,barcode_id,file_id,file_name,data_type,data_format,pid,subtype_global,tumor_class,subtype_tissue,stage
1,07b5663f-9a54-4462-b6c1-6fc8116b8714,TCGA-44-2655,9fcabda1-ea79-4188-8b3f-7d0fd060a819,Primary Tumor,TCGA-44-2655-01A,b2b7acb4-ece5-4e00-bd05-2de5f985bb8a,deae5c6f-6617-4729-98b2-b89ee95cf663.somatic.S...,Structural Rearrangement,BEDPE,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA
2,07b5663f-9a54-4462-b6c1-6fc8116b8714,TCGA-44-2655,9fcabda1-ea79-4188-8b3f-7d0fd060a819,Primary Tumor,TCGA-44-2655-01A,87ff6237-1814-4f3b-abd8-d0e0d6f472be,92b25422-ea11-4b60-bc35-e86c0d73db9f.mirbase21...,Isoform Expression Quantification,TXT,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA
3,07b5663f-9a54-4462-b6c1-6fc8116b8714,TCGA-44-2655,9fcabda1-ea79-4188-8b3f-7d0fd060a819,Primary Tumor,TCGA-44-2655-01A,5c628172-65f9-4bd7-b608-c24f6745f5ab,af6115c8-f05b-43ea-9e95-5e9cc78e2e89.somatic.S...,Structural Rearrangement,BEDPE,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA
4,07b5663f-9a54-4462-b6c1-6fc8116b8714,TCGA-44-2655,9fcabda1-ea79-4188-8b3f-7d0fd060a819,Primary Tumor,TCGA-44-2655-01A,6773903f-ed74-4bb1-8fe4-583ef441861b,HILLY_p_TCGA_b90_wRedos_SNP_N_GenomeWideSNP_6_...,Simple Germline Variation,TSV,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA
5,07b5663f-9a54-4462-b6c1-6fc8116b8714,TCGA-44-2655,9fcabda1-ea79-4188-8b3f-7d0fd060a819,Primary Tumor,TCGA-44-2655-01A,e256a770-8d9c-4fc7-87ea-4f986948407a,HILLY_p_TCGA_b90_wRedos_SNP_N_GenomeWideSNP_6_...,Copy Number Segment,TXT,TCGA-LUAD,adenocarcinoma_generic,adenocarcinoma,lung_adenocarcinoma,Stage IA

### CBioPortal studies

In [18]:
study_list = gdc.cbioportal_studies()

study_list.sort()


lista = [x for x in study_list if 'luad' in x]

print("\n".join(lista))

luad_broad
luad_cas_2020
luad_cptac_2020
luad_cptac_gdc
luad_msk_npjpo_2021
luad_mskcc_2015
luad_mskcc_2020
luad_mskcc_2023_met_organotropism
luad_mskimpact_2021
luad_oncosg_2020
luad_tcga
luad_tcga_gdc
luad_tcga_pan_can_atlas_2018
luad_tcga_pub
luad_tsp

### GDC barcodes ~ submitter

In [19]:
barcodes = list(np.unique(df3.barcode_id))
len(barcodes)

10

In [20]:
# if len(barcodes[0].split('-')[-1]) == 3:
#    barcodes = [x[:-1] for x in barcodes]
barcodes

['TCGA-44-2655-01A',
 'TCGA-62-A471-01A',
 'TCGA-62-A471-01Z',
 'TCGA-67-3773-01A',
 'TCGA-67-3773-01Z',
 'TCGA-86-6851-01A',
 'TCGA-86-6851-01Z',
 'TCGA-91-6848-01A',
 'TCGA-NJ-A7XG-01A',
 'TCGA-NJ-A7XG-01Z']

In [21]:
pid

'TCGA-LUAD'

In [22]:
# mat = pid.lower().split('-')
# study_id = mat[1] + '_' + mat[0]
# print(">>>", study_id)

In [23]:
study_id = pid

df_mut = gdc.get_mutations_from_samples(sample_ids=barcodes, study_id=study_id)
len(df_mut)

>>> luad_tcga len = 10 - ['TCGA-44-2655-01', 'TCGA-62-A471-01', 'TCGA-62-A471-01', 'TCGA-67-3773-01', 'TCGA-67-3773-01']...
>>> luad_tcga_pan_can_atlas_2018 len = 10 - ['TCGA-44-2655-01', 'TCGA-62-A471-01', 'TCGA-62-A471-01', 'TCGA-67-3773-01', 'TCGA-67-3773-01']...
>>> https://www.cbioportal.org/api/molecular-profiles/luad_tcga_pan_can_atlas_2018_mutations/mutations/fetch

1773

In [24]:
df_mut.head(3).T

,0,1,2
sampleId,TCGA-44-2655-01,TCGA-44-2655-01,TCGA-44-2655-01
patientId,TCGA-44-2655,TCGA-44-2655,TCGA-44-2655
studyId,luad_tcga_pan_can_atlas_2018,luad_tcga_pan_can_atlas_2018,luad_tcga_pan_can_atlas_2018
molecularProfileId,luad_tcga_pan_can_atlas_2018_mutations,luad_tcga_pan_can_atlas_2018_mutations,luad_tcga_pan_can_atlas_2018_mutations
entrezGeneId,912,1087,1143
proteinChange,L263I,G70V,V253F
mutationType,Missense_Mutation,Missense_Mutation,Missense_Mutation
mutationStatus,.,.,.
variantType,SNP,SNP,SNP
chr,1,19,15
startPosition,158152847,42191008,78921890
endPosition,158152847,42191008,78921890
referenceAllele,C,C,C
uniqueSampleKey,VENHQS00NC0yNjU1LTAxOmx1YWRfdGNnYV9wYW5fY2FuX2...,VENHQS00NC0yNjU1LTAxOmx1YWRfdGNnYV9wYW5fY2FuX2...,VENHQS00NC0yNjU1LTAxOmx1YWRfdGNnYV9wYW5fY2FuX2...
uniquePatientKey,VENHQS00NC0yNjU1Omx1YWRfdGNnYV9wYW5fY2FuX2F0bG...,VENHQS00NC0yNjU1Omx1YWRfdGNnYV9wYW5fY2FuX2F0bG...,VENHQS00NC0yNjU1Omx1YWRfdGNnYV9wYW5fY2FuX2F0bG...
center,.,.,.
validationStatus,.,.,.
tumorAltCount,30,18,18
tumorRefCount,137,148,98
normalAltCount,0,0,1
normalRefCount,140,199,118
ncbiBuild,GRCh37,GRCh37,GRCh37
keyword,CD1D L263 missense,CEACAM7 G70 missense,CHRNB4 V253 missense
variantAllele,A,A,A
refseqMrnaId,NM_001766.3,NM_006890.3,NM_000750.3
proteinPosStart,263,70,253
proteinPosEnd,263,70,253

In [27]:
df_mut.columns

Index(['sampleId', 'patientId', 'studyId', 'molecularProfileId',
       'entrezGeneId', 'proteinChange', 'mutationType', 'mutationStatus',
       'variantType', 'chr', 'startPosition', 'endPosition', 'referenceAllele',
       'uniqueSampleKey', 'uniquePatientKey', 'center', 'validationStatus',
       'tumorAltCount', 'tumorRefCount', 'normalAltCount', 'normalRefCount',
       'ncbiBuild', 'keyword', 'variantAllele', 'refseqMrnaId',
       'proteinPosStart', 'proteinPosEnd'],
      dtype='object')

In [25]:
df_mut.groupby(['patientId', 'proteinChange'])

In [ ]:
def map_patient_mutations_simple(df_mut: pd.DataFrame):
    patient_gene_protein = (
        df_mut.groupby("patientId")
        .apply(lambda g: sorted(set(
            f"{row.keyword}:{row.entrezGeneId}:{row.proteinChange}:{row.variantType}:{row.chr}"
            for row in g.itertuples(index=False)
            if pd.notna(row.entrezGeneId) and pd.notna(row.proteinChange)
        )))
        .to_dict()
    )
    return patient_gene_protein

In [35]:
patient_mut_map = map_patient_mutations_simple(df_mut)
patient_mut_map

/tmp/ipykernel_163631/1271118666.py:4: FutureWarning: DataFrameGroupBy.apply operated on the grouping columns. This behavior is deprecated, and in a future version of pandas the grouping columns will be excluded from the operation. Either pass `include_groups=False` to exclude the groupings or explicitly select the grouping columns after groupby to silence this warning.
  .apply(lambda g: sorted(set(

{'TCGA-44-2655': ['10527:N973S:SNP:11',
  '10721:D1543H:SNP:3',
  '10758:A52S:SNP:6',
  '10777:P738H:SNP:3',
  '1087:G70V:SNP:19',
  '10880:M41I:SNP:9',
  '11064:E1521*:SNP:9',
  '11085:Q67H:SNP:1',
  '11211:D435Afs*24:DEL:12',
  '112574:E325*:SNP:5',
  '113146:D2351E:SNP:14',
  '1143:V253F:SNP:15',
  '114805:P526T:SNP:2',
  '115019:D362N:SNP:1',
  '115350:P255L:SNP:1',
  '116154:P229T:SNP:20',
  '126205:G582V:SNP:19',
  '127733:P64L:SNP:1',
  '128371:A48E:SNP:1',
  '137970:L704V:SNP:8',
  '140893:D142N:SNP:20',
  '1436:Q448H:SNP:5',
  '1447:A104G:SNP:4',
  '152007:W109L:SNP:9',
  '1663:A572S:SNP:12',
  '169044:X714_splice:SNP:8',
  '1770:I2216N:SNP:17',
  '1903:S361*:SNP:9',
  '200420:X103_splice:SNP:2',
  '2122:N814K:SNP:3',
  '2131:K730Tfs*15:INS:8',
  '222962:A300S:SNP:7',
  '2267:G273C:SNP:8',
  '22873:H361Y:SNP:13',
  '23049:S874C:SNP:16',
  '2317:G1263V:SNP:3',
  '23229:K120M:SNP:23',
  '23236:K1172N:SNP:20',
  '23251:E748K:SNP:15',
  '23269:D2223Y:SNP:15',
  '23345:A15D:SNP:6',
  '23420:D1124Y:SNP:16',
  '23544:G319V:SNP:22',
  '23544:Q934*:SNP:22',
  '23768:G545V:SNP:14',
  '24141:L58I:SNP:20',
  '246213:P175L:SNP:12',
  '246213:X158_splice:SNP:12',
  '254065:R566L:SNP:23',
  '254879:P167Q:SNP:1',
  '254879:P53H:SNP:1',
  '255631:R641S:SNP:1',
  '255743:S362T:SNP:4',
  '2569:Y272N:SNP:6',
  '259232:I1017F:SNP:13',
  '259266:T3382S:SNP:1',
  '26278:D842Y:SNP:13',
  '26529:I172L:SNP:6',
  '27035:A29Dfs*2:DEL:23',
  '27327:S1852C:SNP:16',
  '27328:G442C:SNP:23',
  '285195:G627V:SNP:3',
  '28691:Y108*:DEL:14',
  '3371:G1784S:SNP:9',
  '338675:F200L:SNP:11',
  '339479:A9S:SNP:1',
  '340578:A430G:SNP:23',
  '343169:T110S:SNP:1',
  '3459:S475F:SNP:6',
  '3502:S370C:SNP:14',
  '3603:P783H:SNP:15',
  '3603:P783T:SNP:15',
  '3626:G156C:SNP:12',
  '3660:W305L:SNP:4',
  '3792:Q493K:SNP:7',
  '390077:H26N:SNP:11',
  '3934:L27M:SNP:9',
  '4018:V995A:SNP:6',
  '401992:K91N:SNP:1',
  '4052:V851D:SNP:2',
  '4161:S233R:SNP:18',
  '4308:S22R:SNP:15',
  '4817:A38S:SNP:1',
  '4817:M37I:SNP:1',
  '4855:L412F:SNP:6',
  '4897:A1103S:SNP:7',
  '5049:G200W:SNP:11',
  '50810:K153N:SNP:15',
  '50943:F374Y:SNP:23',
  '5105:T108Qfs*27:DEL:20',
  '51096:X371_splice:SNP:17',
  '51105:X310_splice:SNP:8',
  '51366:P2740L:SNP:8',
  '5150:G397V:SNP:8',
  '51529:D43Y:SNP:17',
  '5207:E386D:SNP:23',
  '5244:K1258N:SNP:7',
  '5267:R335M:SNP:14',
  '5276:P370T:SNP:3',
  '5364:R1150L:SNP:3',
  '55553:G738V:SNP:11',
  '55703:K394*:SNP:12',
  '56113:I365T:SNP:5',
  '56130:H618Q:SNP:5',
  '5618:T165K:SNP:5',
  '56776:L902R:SNP:1',
  '56899:D587Y:SNP:12',
  '57105:D84H:SNP:13',
  '57144:G258V:SNP:20',
  '57467:P284T:SNP:3',
  '57481:R1514M:SNP:23',
  '57484:A225S:SNP:4',
  '57508:X152_splice:SNP:17',
  '57523:A1445S:SNP:14',
  '57540:C333F:SNP:1',
  '57568:A1298S:SNP:1',
  '57692:E600*:SNP:23',
  '5799:G628C:SNP:7',
  '5898:G88W:SNP:7',
  '59341:R746L:SNP:12',
  '5939:S108P:SNP:12',
  '6262:D2707E:SNP:1',
  '63926:Y459C:SNP:20',
  '64218:P95R:SNP:1',
  '642938:D221Y:SNP:10',
  '6648:L176R:SNP:6',
  '6874:Q907*:SNP:20',
  '6910:N286I:SNP:12',
  '7143:M1021I:SNP:1',
  '7412:P55Hfs*9:DEL:1',
  '7477:N233K:SNP:22',
  '7547:P217R:SNP:23',
  '7681:R213G:SNP:15',
  '7718:R392*:SNP:6',
  '7915:A198P:SNP:6',
  '79633:N880K:SNP:4',
  '79722:K193N:SNP:5',
  '79722:Y307N:SNP:5',
  '79776:N1106I:SNP:8',
  '79858:X321_splice:SNP:3',
  '79983:G161R:SNP:23',
  '81341:L73M:SNP:11',
  '81559:G277V:SNP:1',
  '81832:D430H:SNP:18',
  '83638:V93L:SNP:11',
  '83894:E206K:SNP:4',
  '84189:D217N:SNP:13',
  '84919:M695V:SNP:1',
  '84970:S551Y:SNP:1',
  '8559:R212C:SNP:10',
  '8672:L697F:SNP:1',
  '8737:M351I:SNP:6',
  '8880:X280_splice:SNP:1',
  '89932:Q574R:SNP:14',
  '9064:X685_splice:SNP:1',
  '90987:G171V:SNP:8',
  '912:L263I:SNP:1',
  '92235:G764V:SNP:1',
  '9228:D480Y:SNP:8',
  '92749:K360N:SNP:2',
  '94025:P8611T:SNP:19',
  '94025:T11642N:SNP:19',
  '9767:E718D:SNP:23',
  '9817:S144F:SNP:19'],
 'TCGA-62-A471': ['1008:R230K:SNP:5',
  '10401:R240L:SNP:1',
  '10466:G561R:SNP:7',
  '1048:S626C:SNP:19',
  '1121:S197G:SNP:23',
  '114791:X458_splice:SNP:15',
  '124535:R223W:SNP:17',
  '129684:S1060F:SNP:2',
  '133690:E27K:SNP:5',
  '1407:C402F:SNP:12',
  '144453:E530Q:SNP:12',
  '158405:S92C:SNP:9',
  '161514:I27Lfs*36:DEL:15',
  '1785:Q283E:SNP:19',
  '2042:D832H:SNP:3',
  '2042:D838N:SNP:3',
  '2065:E1218K:SNP:12',
  '217:F427L:SNP:12',
  '219965:F100L:SNP:11',
  '22997:Q273*:SNP:11',
  '255101:P1577H:SNP:2',
  '2571:E499K:SNP:2',
  '2626:R283C:SNP:8',
  '2651:P183S:SNP:6',
  '2697:S306N:SNP:6',
  '28985:R74K:SNP:23',
  '29102:S960L:SNP:5',
  '337969:G23*:SNP:21',
  '359787:G13E:SNP:12',
  '360200:F401C:SNP:19',
  '374786:K246N:SNP:17',
  '3841:P384R:SNP:6',
  '390212:E171K:SNP:11',
  '394:R1140K:SNP:14',
  '4053:E1041K:SNP:14',
  '4325:A121T:SNP:8',
  '4430:E1028Q:SNP:2',
  '4548:S1073C:SNP:1',
  '4780:A384V:SNP:2',
  '4926:R770*:SNP:11',
  '51086:Q328E:SNP:1',
  '51098:L77V:SNP:20',
  '51133:K739R:SNP:1',
  '51514:L460V:SNP:1',
  '5157:E239D:SNP:8',
  '54825:A415V:SNP:5',
  '54894:R256G:SNP:17',
  '55107:A568V:SNP:11',
  '55188:H343Y:SNP:12',
  '55714:D1540Y:SNP:4',
  '55764:Q26E:SNP:3',
  '56137:L196I:SNP:5',
  '56913:D163H:SNP:7',
  '56979:S705T:SNP:5',
  '57488:X217_splice:SNP:7',
  '6252:R514Q:SNP:14',
  '64478:S616L:SNP:8',
  '6476:H1660R:SNP:3',
  '64844:R7S:SNP:2',
  '654463:X149_splice:SNP:8',
  '6614:R1316W:SNP:20',
  '6777:Q36P:SNP:17',
  '7157:Y236C:SNP:17',
  '7249:Y587C:SNP:16',
  '7273:X8510_splice:SNP:2',
  '727:V734I:SNP:9',
  '7436:H356Y:SNP:9',
  '7582:E473Q:SNP:10',
  '7625:E115Dfs*4:DEL:22',
  '776:R419W:SNP:3',
  '79705:W155C:SNP:15',
  '79741:E402Q:SNP:10',
  '79977:M168L:SNP:8',
  '80005:Q1013*:SNP:8',
  '80740:X18_splice:SNP:6',
  '81602:D383N:SNP:13',
  '84417:E79K:SNP:2',
  '84467:R1793L:SNP:19',
  '84647:C118W:SNP:10',
  '8477:Q316E:SNP:14',
  '84964:Y37C:SNP:19',
  '85458:X64_splice:SNP:11',
  '8568:E144K:SNP:21',
  '8787:E333K:SNP:17',
  '8843:S247T:SNP:12',
  '89857:D225N:SNP:3',
  '9096:G459A:SNP:6',
  '9175:R430T:SNP:3',
  '9918:S1034F:SNP:12',
  '9980:L278F:SNP:21'],
 'TCGA-67-3773': ['10346:P440L:SNP:11',
  '10788:E654*:SNP:5',
  '1106:C440*:DEL:15',
  '119679:A187T:SNP:11',
  '126638:Y403F:SNP:1',
  '127062:D265Ifs*21:DEL:1',
  '127254:A1100E:SNP:1',
  '1303:R1953C:SNP:6',
  '144132:E4033K:SNP:11',
  '146325:P225A:SNP:16',
  '1500:R378L:SNP:11',
  '160335:L152F:SNP:12',
  '164592:Q510*:SNP:22',
  '170961:P601H:SNP:19',
  '200162:D1436Y:SNP:1',
  '203111:P301S:SNP:8',
  '219957:G253D:SNP:11',
  '221178:V150F:SNP:13',
  '22936:R626G:SNP:5',
  '23039:A766S:SNP:8',
  '23275:E252D:SNP:21',
  '25970:E79K:SNP:16',
  '26040:G1105V:SNP:18',
  '2669:A96S:SNP:8',
  '27040:V10M:SNP:16',
  '2747:G279V:SNP:23',
  '2747:G279W:SNP:23',
  '2817:Q181K:SNP:2',
  '28316:Q40K:SNP:18',
  '284312:W136C:SNP:19',
  '285220:V496L:SNP:3',
  '3207:N300H:SNP:7',
  '3207:N300I:SNP:7',
  '3290:E30*:SNP:1',
  '3290:X30_splice:SNP:1',
  '3361:E277K:SNP:7',
  '338699:G65V:SNP:11',
  '3598:W325C:SNP:23',
  '3791:A1168T:SNP:4',
  '3822:S171P:SNP:12',
  '3845:G12V:SNP:12',
  '389158:Q63K:SNP:3',
  '401666:C191S:SNP:11',
  '403282:I44N:SNP:12',
  '4051:S170C:SNP:19',
  '4052:X1334_splice:SNP:2',
  '4193:X143_splice:SNP:12',
  '4312:Q139K:SNP:11',
  '4343:R11L:SNP:1',
  '51077:L86V:SNP:14',
  '51555:P582R:SNP:3',
  '540:I698V:SNP:13',
  '54212:W381C:SNP:8',
  '54212:W381L:SNP:8',
  '54551:V388*:DEL:15',
  '54623:W297L:SNP:19',
  '5495:N270S:SNP:2',
  '55362:R607M:SNP:6',
  '55876:Q184*:SNP:17',
  '56140:R92H:SNP:5',
  '5649:S2548L:SNP:7',
  '57336:E119K:SNP:17',
  '57556:S928R:SNP:5',
  '57613:L533H:SNP:12',
  '5789:R123S:SNP:9',
  '5797:Q205R:SNP:18',
  '58512:A360V:SNP:1',
  '5917:I375V:SNP:5',
  '64779:R342Q:SNP:16',
  '66002:S81T:SNP:19',
  '6708:G928S:SNP:1',
  '7007:C285F:SNP:11',
  '7399:P2441S:SNP:1',
  '7594:G450*:SNP:19',
  '7594:G450V:SNP:19',
  '7704:R538L:SNP:11',
  '775:S1990R:SNP:12',
  '79875:E667K:SNP:15',
  '80816:V1358A:SNP:18',
  '81061:C256Vfs*20:DEL:22',
  '83552:V47I:SNP:11',
  '84182:K63N:SNP:7',
  '84643:A639S:SNP:17',
  '84658:T287M:SNP:19',
  '84726:A1878S:SNP:9',
  '85315:R8H:SNP:6',
  '8715:R509L:SNP:18',
  '89795:R1575L:SNP:12',
  '90025:G16*:SNP:6',
  '9223:G180C:SNP:3',
  '93185:V593D:SNP:1',
  '9344:E519D:SNP:16',
  '94137:P1441T:SNP:8',
  '9627:L301I:SNP:5',
  '9890:S711R:SNP:1'],
 'TCGA-86-6851': ['10044:D375Y:SNP:9',
  '10079:R281L:SNP:20',
  '10082:L553M:SNP:13',
  '10083:Q320K:SNP:11',
  '1010:P22T:SNP:5',
  '1015:I286V:SNP:8',
  '10178:N279K:SNP:23',
  '10178:R297*:SNP:23',
  '10196:X258_splice:SNP:11',
  '10199:F237del:DEL:2',
  '10267:E38*:SNP:2',
  '10288:R178S:SNP:19',
  '10291:P414H:SNP:22',
  '10319:C273*:SNP:9',
  '10324:G299R:SNP:2',
  '10349:N429T:SNP:17',
  '10350:G9C:SNP:17',
  '10396:G746W:SNP:4',
  '10404:W294C:SNP:8',
  '10446:C29S:SNP:1',
  '1044:P226Q:SNP:5',
  '10457:L563I:SNP:7',
  '10469:Q318H:SNP:19',
  '10499:L672F:SNP:8',
  '10562:S229T:SNP:13',
  '10640:R296M:SNP:14',
  '10694:E75Q:SNP:21',
  '10785:H144P:SNP:21',
  '107:X383_splice:SNP:7',
  '10864:G500W:SNP:6',
  '10878:H115N:SNP:1',
  '10892:G720V:SNP:18',
  '1089:H141Q:SNP:19',
  '108:L50M:SNP:5',
  '10936:Q343H:SNP:2',
  '10940:V293Cfs*5:DEL:8',
  '10973:G2092V:SNP:6',
  '10973:G2092W:SNP:6',
  '10992:P249L:SNP:11',
  '11026:R179Q:SNP:19',
  '11027:Q22K:SNP:19',
  '11085:Q242K:SNP:1',
  '11131:K352N:SNP:6',
  '11149:R226I:SNP:6',
  '11173:Q179H:SNP:15',
  '11187:G644W:SNP:11',
  '11219:R208L:SNP:23',
  '1124:T221K:SNP:7',
  '1130:W3329L:SNP:1',
  '1131:C561F:SNP:1',
  '1131:F168I:SNP:1',
  '1142:V443F:SNP:8',
  '114780:Q72*:SNP:16',
  '114784:P419T:SNP:1',
  '114788:E1563D:SNP:8',
  '114788:G869V:SNP:8',
  '114788:Q868H:SNP:8',
  '114815:R120L:SNP:10',
  '114:A359S:SNP:8',
  '115350:A75V:SNP:1',
  '115795:P91L:SNP:3',
  '116512:Y64C:SNP:11',
  '116984:S511I:SNP:4',
  '117154:G584*:SNP:23',
  '1187:L56I:SNP:1',
  '119682:L32I:SNP:11',
  '119764:L257P:SNP:11',
  '120114:C4064W:SNP:11',
  '120114:P1359A:SNP:11',
  '120237:K226R:SNP:11',
  '120406:G140*:SNP:11',
  '120892:S764C:SNP:12',
  '121278:D46Y:SNP:12',
  '121601:E775V:SNP:12',
  '121601:N59D:SNP:12',
  '122740:P80L:SNP:14',
  '123355:H269R:SNP:15',
  '123745:E135D:SNP:15',
  '124401:M615I:SNP:16',
  '1244:C385F:SNP:10',
  '124599:Y225*:SNP:17',
  '126204:S823*:SNP:19',
  '126205:E961*:SNP:19',
  '126637:G691*:SNP:1',
  '126820:V90G:SNP:1',
  '127064:A237S:SNP:1',
  '127665:P60Q:SNP:1',
  '128360:K139Q:SNP:1',
  '128387:X228_splice:SNP:1',
  '128553:V1009L:SNP:20',
  '1293:L9F:SNP:2',
  '129446:A1987E:SNP:2',
  '129446:G1993E:SNP:2',
  '129446:S2270C:SNP:2',
  '129684:I526F:SNP:2',
  '1299:G145V:SNP:20',
  '1301:G908V:SNP:1',
  '1305:X333_splice:SNP:10',
  '131096:E51*:SNP:3',
  '1310:T197N:SNP:6',
  '131831:R544S:SNP:3',
  '132724:I6T:SNP:4',
  '132949:G345V:SNP:4',
  '132949:T291I:SNP:4',
  '134829:F86L:SNP:6',
  '134860:F313L:SNP:6',
  '135644:C60S:SNP:6',
  '136306:R244S:SNP:7',
  '1373:L1258F:SNP:2',
  '138009:S369Y:SNP:8',
  '138474:R725Q:SNP:9',
  '138716:X12_splice:SNP:9',
  '138882:L302Q:SNP:9',
  '139065:G197V:SNP:23',
  '140685:K84N:SNP:20',
  '140690:Q139K:SNP:20',
  '140801:N144K:SNP:14',
  '140831:V249L:SNP:20',
  '142678:G692V:SNP:1',
  '142685:E132*:SNP:7',
  '143384:V317L:SNP:10',
  '144165:Q630E:SNP:12',
  '1443:R160G:SNP:17',
  '144423:I76V:SNP:12',
  '144577:N376S:SNP:12',
  '1454:G175V:SNP:22',
  '145581:H195N:SNP:14',
  '145858:W52R:SNP:15',
  '146183:R571M:SNP:16',
  '1462:L676V:SNP:5',
  '1464:A828P:SNP:15',
  '147381:R50L:SNP:18',
  '147687:R288L:SNP:19',
  '147965:G316V:SNP:19',
  '147:S173C:SNP:5',
  '1496:P14H:SNP:2',
  '1500:N397S:SNP:11',
  '150350:M581I:SNP:22',
  '151887:E229*:SNP:3',
  '151963:K79N:SNP:3',
  '152110:Q317H:SNP:3',
  '152573:L138I:SNP:4',
  '1525:D114H:SNP:21',
  '154664:P3526Q:SNP:7',
  '1556:X233_splice:SNP:19',
  '158158:G504W:SNP:9',
  '1582:K274N:SNP:3',
  '158401:Q590L:SNP:9',
  '158471:R697T:SNP:9',
  '158471:T2597S:SNP:9',
  '158983:L89Q:SNP:23',
  '160065:N112Y:SNP:11',
  '161176:G185W:SNP:14',
  '1612:V1134L:SNP:9',
  '163351:S425I:SNP:1',
  '1638:N37K:SNP:13',
  '1639:P918L:SNP:2',
  '1657:D2914H:SNP:5',
  '167127:F253I:SNP:5',
  '167838:C648*:SNP:6',
  '168090:A329Rfs*10:DEL:6',
  '168374:C511F:SNP:7',
  '168507:E2277K:SNP:7',
  '171019:W985C:SNP:5',
  '1731:E382Q:SNP:16',
  '1735:S212T:SNP:14',
  '173:D563V:SNP:4',
  '1749:G53Efs*28:DEL:7',
  '1767:M3320I:SNP:5',
  '1767:Y1106C:SNP:5',
  '1812:T343Pfs*3:DEL:5',
  '1837:P572T:SNP:18',
  '1880:L68F:SNP:13',
  '1894:R147T:SNP:3',
  '1910:A78Qfs*46:DEL:13',
  '1912:N557K:SNP:1',
  '1917:X258_splice:SNP:20',
  '196335:V213L:SNP:11',
  '196335:Y66*:SNP:11',
  '196385:A2983S:SNP:12',
  '196477:N350K:SNP:12',
  '196528:V768L:SNP:12',
  '197:E183V:SNP:3',
  '1996:P275Q:SNP:1',
  '1996:P275T:SNP:1',
  '200162:L937H:SNP:1',
  '200424:W47S:SNP:2',
  '200879:M129I:SNP:3',
  '2011:N541Y:SNP:11',
  '2015:R547M:SNP:19',
  '2017:X30_splice:SNP:11',
  '202500:D179H:SNP:6',
  '203062:M1?:SNP:8',
  '203430:E122*:SNP:23',
  '204219:T109R:SNP:15',
  '2047:R372L:SNP:3',
  '204962:V699L:SNP:1',
  '2058:S990C:SNP:1',
  '2058:V1205F:SNP:1',
  '2153:P1392S:SNP:1',
  '2153:V300L:SNP:1',
  '2155:S207I:SNP:13',
  '2155:T332S:SNP:13',
  '2162:X636_splice:SNP:6',
  '2165:N393S:SNP:1',
  '2192:E127Q:SNP:22',
  '219437:M212I:SNP:11',
  '219482:P146H:SNP:11',
  '219858:H55L:SNP:11',
  '219983:C240*:SNP:11',
  '219:M1?:SNP:9',
  '220032:R524*:SNP:11',
  '220047:P367T:SNP:11',
  '2200:L11Wfs*7:DEL:15',
  '2201:S2516L:SNP:5',
  '220965:R148I:SNP:10',
  '221061:G258C:SNP:10',
  '221458:V16F:SNP:6',
  '221935:W890C:SNP:7',
  '222584:T956N:SNP:6',
  '222950:C804F:SNP:7',
  '222962:G44S:SNP:7',
  '2241:K40*:SNP:5',
  '2245:P150T:SNP:23',
  '2262:V454L:SNP:13',
  '22795:P104Q:SNP:14',
  '22795:P1354T:SNP:14',
  '22798:V1385L:SNP:7',
  '22853:I143F:SNP:7',
  '22864:R590S:SNP:12',
  '22865:E549Q:SNP:3',
  '22897:E253Q:SNP:11',
  '22897:R941T:SNP:11',
  '22925:D1200V:SNP:2',
  '22981:R451L:SNP:20',
  '22995:G1140*:SNP:15',
  '22996:H353R:SNP:1',
  '23040:R459S:SNP:2',
  '23064:P1266S:SNP:9',
  '23064:R2168L:SNP:9',
  '23071:P262L:SNP:9',
  '23114:T500N:SNP:1',
  '23145:X4003_splice:SNP:7',
  '231:Q27K:SNP:7',
  '23205:R143S:SNP:15',
  '23224:S3537C:SNP:14',
  '23230:A1735T:SNP:9',
  '23250:E392*:SNP:13',
  '23258:G1216Afs*38:DEL:11',
  '23261:P159L:SNP:1',
  '23275:A376P:SNP:21',
  '23283:Q259H:SNP:10',
  '23284:P393L:SNP:4',
  '23293:S258I:SNP:17',
  '23313:F288L:SNP:22',
  '23345:E1468*:SNP:6',
  '23389:X746_splice:SNP:12',
  '23414:A518D:SNP:8',
  '2346:D173Y:SNP:11',
  '23510:E211Q:SNP:17',
  '23534:R769L:SNP:7',
  '23627:C14S:SNP:20',
  '23666:A198E:SNP:17',
  '245913:C56F:SNP:6',
  '245934:C44R:SNP:20',
  '2529:A220D:SNP:9',
  '253725:A656S:SNP:10',
  '254050:G318E:SNP:12',
  '255426:L98M:SNP:5',
  '255631:X1246_splice:SNP:1',
  '255631:X771_splice:SNP:1',
  '256076:T51K:SNP:3',
  '2560:D442E:SNP:4',
  '256144:H253N:SNP:11',
  '2565:X377_splice:SNP:4',
  '2569:Q104H:SNP:6',
  '257629:F194L:SNP:16',
  '25791:K511N:SNP:2',
  '2581:E242*:SNP:14',
  '25878:S1253T:SNP:23',
  '25920:Q148H:SNP:9',
  '259232:V120Ffs*13:DEL:13',
  '25924:S250I:SNP:3',
  '25925:G1039W:SNP:18',
  '25925:H1038L:SNP:18',
  '259293:S77I:SNP:12',
  '2595:F217L:SNP:15',
  '26005:H1275R:SNP:11',
  '26009:G820V:SNP:1',
  '26032:I253F:SNP:3',
  '26037:E1587*:SNP:14',
  '26039:G149W:SNP:20',
  '2649:G234R:SNP:9',
  '2651:A17S:SNP:6',
  '26574:G113C:SNP:17',
  '266747:X388_splice:SNP:22',
  '26985:*419=:DEL:10',
  '27010:G189*:SNP:7',
  '27013:V101L:SNP:2',
  '27022:S165R:SNP:1',
  '27067:Q343H:SNP:8',
  '27178:N195K:SNP:2',
  '2737:P651Q:SNP:7',
  '27436:K128E:SNP:2',
  '27445:E1470D:SNP:7',
  '27445:R4389M:SNP:7',
  '27445:R4389S:SNP:7',
  '2778:C3Y:SNP:20',
  '283284:H384Q:SNP:11',
  '283455:R404C:SNP:12',
  '28388:W55C:SNP:14',
  '283951:S26*:SNP:16',
  '284217:P76H:SNP:18',
  '284459:G531V:SNP:19',
  '28450:R106T:SNP:14',
  '28466:D2Y:SNP:14',
  '28474:P72L:SNP:14',
  '285180:L497S:SNP:2',
  '285195:G627C:SNP:3',
  '285220:A991S:SNP:3',
  '28591:R28S:SNP:7',
  '286148:X669_splice:SNP:8',
  '2861:P235L:SNP:7',
  '28783:A122D:SNP:22',
  '28891:T42N:SNP:2',
  '28901:D92Y:SNP:2',
  '28937:S48G:SNP:2',
  '28969:L45F:SNP:7',
  '2903:L1052I:SNP:16',
  '2904:G1128V:SNP:12',
  '2904:Y1070N:SNP:12',
  '29109:F976L:SNP:16',
  '2911:V583L:SNP:6',
  '2917:X293_splice:SNP:3',
  '2969:P154S:SNP:7',
  '3001:R75M:SNP:5',
  '3009:R57L:SNP:6',
  '3055:D34Y:SNP:20',
  '3059:E35G:SNP:3',
  '3062:R297G:SNP:6',
  '3069:R283H:SNP:2',
  '3073:E91G:SNP:15',
  '3082:G185R:SNP:7',
  '3096:E1290*:SNP:6',
  '3097:E1194Q:SNP:6',
  '3097:E890Q:SNP:6',
  '309:R624T:SNP:5',
  '3172:A61P:SNP:20',
  '3202:P154T:SNP:7',
  '3231:G319C:SNP:2',
  '3284:S324N:SNP:1',
  '3300:D211Y:SNP:2',
  '3316:E172K:SNP:11',
  '3340:D317Y:SNP:5',
  '3354:L342Q:SNP:6',
  '3354:S322Y:SNP:6',
  '335:E258Q:SNP:11',
  '338321:P207Q:SNP:19',
  '338:Q546L:SNP:2',
  '339230:R176L:SNP:17',
  '339479:C217*:SNP:1',
  '340526:R111G:SNP:23',
  '340533:G514V:SNP:23',
  '341359:L295I:SNP:12',
  '343066:R152L:SNP:1',
  '343173:E25K:SNP:1',
  '346007:W43C:SNP:6',
  '346171:T214K:SNP:6',
  '348093:R102S:SNP:15',
  '3480:Q45H:SNP:15',
  '348158:S237I:SNP:16',
  '348980:P785T:SNP:5',
  '3514:Q48K:SNP:2',
  '3551:X612_splice:SNP:8',
  '3553:Y184*:SNP:2',
  '357:S433N:SNP:23',
  '358:V103L:SNP:7',
  '3614:L505R:SNP:7',
  '3624:A81E:SNP:7',
  '364:Q30L:SNP:9',
  '3655:P721H:SNP:2',
  '367:W752C:SNP:23',
  '3694:E748Q:SNP:2',
  '3696:P554L:SNP:7',
  '3698:G138C:SNP:10',
  '3698:K439N:SNP:10',
  '3720:K240I:SNP:6',
  '375387:Q78L:SNP:3',
  '3755:Q148K:SNP:20',
  '3758:T332K:SNP:11',
  '3762:A29D:SNP:11',
  '3805:Y63H:SNP:19',
  '386617:P403Hfs*32:DEL:4',
  '388697:G670E:SNP:1',
  '389015:T148P:SNP:2',
  '389090:S65Y:SNP:2',
  '3891:X210_splice:SNP:12',
  '389763:E1503V:SNP:9',
  '390054:Y295H:SNP:11',
  '390083:G246V:SNP:11',
  '390093:V57F:SNP:11',
  '390142:L70M:SNP:11',
  '390157:H250N:SNP:11',
  '390191:I278V:SNP:11',
  '390928:F219L:SNP:19',
  '391112:A304E:SNP:1',
  '391114:P154H:SNP:1',
  '391:Q74E:SNP:11',
  '394263:R539S:SNP:6',
  '4008:E388K:SNP:13',
  '401145:P46S:SNP:4',
  '401992:L87Q:SNP:1',
  '403239:Y123*:SNP:1',
  '403277:E108Q:SNP:3',
  '4036:I2799N:SNP:2',
  '4036:M1588K:SNP:2',
  '4052:C430S:SNP:2',
  '4052:P850T:SNP:2',
  '4115:D231Y:SNP:23',
  '4147:E108*:SNP:8',
  '4158:E28*:SNP:18',
  '4190:X226_splice:SNP:2',
  '4249:R727L:SNP:2',
  '4253:S241L:SNP:14',
  '4288:G1779V:SNP:10',
  '431705:G285V:SNP:2',
  '4324:R169H:SNP:16',
  '4356:A302S:SNP:17',
  '4360:R1357G:SNP:10',
  '440279:Q1575H:SNP:15',
  '441061:S339Y:SNP:5',
  '442444:K336N:SNP:23',
  '442444:K99N:SNP:23',
  '4478:V65L:SNP:23',
  '4481:G69V:SNP:8',
  '4528:D401H:SNP:2',
  '4595:X116_splice:SNP:1',
  '4619:E99*:SNP:17',
  '4645:G291A:SNP:18',
  '4674:D252E:SNP:23',
  '4775:S296L:SNP:16',
  '480:A548S:SNP:1',
  '4853:L2184F:SNP:1',
  '4855:X813_splice:SNP:6',
  '4857:G260C:SNP:14',
  '488:S178L:SNP:12',
  '4892:F1388L:SNP:10',
  '4916:Q172H:SNP:15',
  '4920:Y786C:SNP:9',
  '493861:R185Q:SNP:12',
  '4952:F210L:SNP:23',
  '5023:R20P:SNP:17',
  '503835:F149L:SNP:19',
  '503835:R152Q:SNP:19',
  '5045:Y495C:SNP:15',
  '50618:L195V:SNP:2',
  '5078:M1?:SNP:7',
  '50809:S442L:SNP:1',
  '50852:T97N:SNP:3',
  '5087:D232V:SNP:1',
  '5099:I505M:SNP:4',
  '51059:I1209L:SNP:8',
  '5105:R100G:SNP:20',
  '51151:G399C:SNP:5',
  '51156:N155K:SNP:14',
  '51297:G136S:SNP:20',
  '5136:P401Q:SNP:2',
  '5139:L240M:SNP:12',
  '5139:Y567*:SNP:12',
  '51555:R96M:SNP:3',
  '5167:A205V:SNP:6',
  '51696:G507W:SNP:6',
  '51728:D50H:SNP:16',
  '51776:D753Y:SNP:2',
  '51780:A656S:SNP:5',
  '51802:C315*:SNP:4',
  '5251:V274L:SNP:23',
  '5287:L240F:SNP:1',
  '5314:D2069Y:SNP:6',
  '5314:Q225H:SNP:6',
  '53349:S260*:SNP:14',
  '53353:Q687K:SNP:2',
  '5340:D665Y:SNP:6',
  '5340:R629S:SNP:6',
  '5411:R6K:SNP:14',
  '5426:A1751S:SNP:12',
  '54328:D68Y:SNP:23',
  '54490:A60S:SNP:4',
  '54494:D79Y:SNP:11',
  '54517:R178L:SNP:7',
  '54549:Q1262K:SNP:17',
  '54578:A425S:SNP:2',
  '54661:Y402F:SNP:5',